import type { Locale } from "@rabaed/domain";
import type { NumberingCountersLabels } from "../components/numbering/numbering-counters.tsx";
import type { NumberingPatternLabels } from "../components/numbering/numbering-pattern.tsx";
import type { ParticipantCodesLabels } from "../components/numbering/participant-codes.tsx";

// Story copy for Numbering: the labels the app passes from its messages
// (apps/web/messages), in English and Arabic.

export const numberingPatternLabels: Record<Locale, NumberingPatternLabels> = {
  en: {
    kinds: {
      project: "Project",
      type: "Work Item Type",
      trade: "Trade",
      participant: "Participant Code",
      location: "Location level",
      text: "Fixed text",
    },
    levels: ["Zone", "Building", "Floor"],
    segments: "Segments",
    segment: (n) => `Segment ${n}`,
    level: "Level",
    text: "Text",
    textHint: "1 to 10 capital letters or digits.",
    textInvalid: "Use 1 to 10 capital letters or digits.",
    counted: "Counted separately",
    countedHint: "The sequence runs on its own for each value of a ticked segment.",
    moveUp: (n) => `Move segment ${n} up`,
    moveDown: (n) => `Move segment ${n} down`,
    remove: (n) => `Remove segment ${n}`,
    add: "Add segment",
    separator: "Separator",
    digits: "Sequence digits",
    example: "Example",
    exampleHint: "The first number this pattern gives.",
    sharedTitle: "One shared count",
    sharedBody:
      "The sequence doesn't count separately for the Participant Code, so every Company's items share one count. Each Company can then tell how many items the others numbered from the gaps in its own numbers.",
    sharedAccept: "I accept that every Company can tell the others' volume from the gaps",
    sharedReadOnly: "Every Company's items share one count, accepted by the Project Admin.",
    save: "Save pattern",
    saving: "Saving…",
    afterChange: "A change applies only to items numbered after it; issued numbers never change.",
    countedBadge: "Counted",
  },
  ar: {
    kinds: {
      project: "المشروع",
      type: "نوع البند",
      trade: "التخصص",
      participant: "رمز المشارك",
      location: "مستوى الموقع",
      text: "نص ثابت",
    },
    levels: ["المنطقة", "المبنى", "الطابق"],
    segments: "الأجزاء",
    segment: (n) => `الجزء ${n}`,
    level: "المستوى",
    text: "النص",
    textHint: "من 1 إلى 10 أحرف إنجليزية كبيرة أو أرقام.",
    textInvalid: "استخدم من 1 إلى 10 أحرف إنجليزية كبيرة أو أرقام.",
    counted: "يُعدّ منفصلًا",
    countedHint: "يبدأ التسلسل عدًّا مستقلًا لكل قيمة من قيم الجزء المحدد.",
    moveUp: (n) => `نقل الجزء ${n} إلى الأعلى`,
    moveDown: (n) => `نقل الجزء ${n} إلى الأسفل`,
    remove: (n) => `إزالة الجزء ${n}`,
    add: "إضافة جزء",
    separator: "الفاصل",
    digits: "عدد خانات التسلسل",
    example: "مثال",
    exampleHint: "أول رقم يعطيه هذا النمط.",
    sharedTitle: "عدّ مشترك واحد",
    sharedBody:
      "لا يُعدّ التسلسل منفصلًا حسب رمز المشارك، لذا تشترك بنود كل الشركات في عدّ واحد. وعندها تستطيع كل شركة أن تعرف من الفجوات في أرقامها عدد البنود التي رقّمتها الشركات الأخرى.",
    sharedAccept: "أقبل أن كل شركة تستطيع معرفة حجم عمل الشركات الأخرى من الفجوات",
    sharedReadOnly: "تشترك بنود كل الشركات في عدّ واحد، بقبول مسؤول المشروع.",
    save: "حفظ النمط",
    saving: "جارٍ الحفظ…",
    afterChange: "يسري التغيير على البنود التي تُرقَّم بعده فقط، ولا تتغير الأرقام الصادرة أبدًا.",
    countedBadge: "يُعدّ",
  },
};

export const numberingCountersLabels: Record<Locale, NumberingCountersLabels> = {
  en: {
    title: "Counters",
    intro: "Each counter issues the sequence of the numbers it counts. Only Project Admins see counters.",
    counter: "Counter",
    lastNumber: "Last number",
    state: "State",
    none: "No counters yet. A counter starts with the first number it issues.",
    inUse: "In use",
    startsAt: (n) => `Starts at ${n}`,
    startTitle: "Set a starting number",
    startIntro:
      "Continuing a paper register? Set the number the counter issues next, before it issues its first. It can't change after that.",
    type: "Work Item Type",
    participant: "Participant",
    trade: "Trade",
    location: "Location",
    notCounted: "Not counted",
    startingNumber: "Starting number",
    next: "The next number will be",
    used: (n) => `This counter has already issued numbers, up to ${n}. Its starting number can't change.`,
    save: "Set starting number",
    saved: "Starting number set. The next number will be",
    refusals: {
      participant_required: "Choose a Participant: the Numbering Pattern counts by it.",
      trade_required: "Choose a Trade: the Numbering Pattern counts by it.",
      location_required: "Choose a Location: the Numbering Pattern counts by it.",
      value_not_found: "That choice is no longer on the Project. Reload the page.",
      type_not_found: "That Work Item Type is no longer on the Project. Reload the page.",
      counter_used: "This counter has issued a number since. Its starting number can't change.",
      project_closed: "The Project is closed.",
      not_found: "You can't change numbering on this Project.",
      invalid: "Enter a whole number from 1 to 9,999,999.",
      unavailable: "That didn't work. Try again.",
    },
  },
  ar: {
    title: "العدّادات",
    intro: "يُصدر كل عدّاد تسلسل الأرقام التي يعدّها. لا يرى العدّادات إلا مسؤولو المشروع.",
    counter: "العدّاد",
    lastNumber: "آخر رقم",
    state: "الحالة",
    none: "لا توجد عدّادات بعد. يبدأ العدّاد بأول رقم يُصدره.",
    inUse: "مستخدم",
    startsAt: (n) => `يبدأ من ${n}`,
    startTitle: "تحديد رقم البداية",
    startIntro: "هل تواصلون سجلًا ورقيًا؟ حدّدوا الرقم الذي يُصدره العدّاد تاليًا قبل أن يُصدر أول رقم. لا يمكن تغييره بعد ذلك.",
    type: "نوع البند",
    participant: "المشارك",
    trade: "التخصص",
    location: "الموقع",
    notCounted: "غير معدود",
    startingNumber: "رقم البداية",
    next: "سيكون الرقم التالي",
    used: (n) => `أصدر هذا العدّاد أرقامًا بالفعل حتى ${n}. لا يمكن تغيير رقم بدايته.`,
    save: "تحديد رقم البداية",
    saved: "تم تحديد رقم البداية. سيكون الرقم التالي",
    refusals: {
      participant_required: "اختر مشاركًا: نمط الترقيم يعدّ حسبه.",
      trade_required: "اختر تخصصًا: نمط الترقيم يعدّ حسبه.",
      location_required: "اختر موقعًا: نمط الترقيم يعدّ حسبه.",
      value_not_found: "لم يعد هذا الاختيار في المشروع. أعد تحميل الصفحة.",
      type_not_found: "لم يعد نوع البند هذا في المشروع. أعد تحميل الصفحة.",
      counter_used: "أصدر هذا العدّاد رقمًا منذ ذلك الحين. لا يمكن تغيير رقم بدايته.",
      project_closed: "المشروع مغلق.",
      not_found: "لا يمكنك تغيير الترقيم في هذا المشروع.",
      invalid: "أدخل عددًا صحيحًا من 1 إلى 9,999,999.",
      unavailable: "لم ينجح ذلك. حاول مرة أخرى.",
    },
  },
};

export const participantCodesLabels: Record<Locale, ParticipantCodesLabels> = {
  en: {
    title: "Participant Codes",
    intro:
      "Each Participant's code in Document Numbers: 2 to 6 letters or digits, at least one a letter. Until a code is set, numbers show the Participant's order on the Project. A code is fixed once a number uses it.",
    participants: "Participants",
    code: "Participant Code",
    order: "Order on the Project, until a code is set",
    noCode: "No code yet",
    save: "Save code",
    saved: "Participant Code saved.",
    refusals: {
      invalid: "Use 2 to 6 letters or digits, with at least one letter.",
      duplicate_code: "Another Participant on this Project already has that code.",
      code_in_use: "A Document Number already uses this code, so it can no longer change.",
      forbidden: "Only a Project Admin can set Participant Codes.",
      unavailable: "Something went wrong. Try again.",
    },
  },
  ar: {
    title: "رموز المشاركين",
    intro:
      "رمز كل مشارك في أرقام المستندات: من حرفين إلى 6 أحرف أو أرقام، على أن يكون بينها حرف واحد على الأقل. ما لم يُحدَّد الرمز، تعرض الأرقام ترتيب المشارك في المشروع. ويُثبَّت الرمز بمجرد أن يستخدمه رقم.",
    participants: "المشاركون",
    code: "رمز المشارك",
    order: "الترتيب في المشروع، إلى أن يُحدَّد رمز",
    noCode: "لا رمز بعد",
    save: "حفظ الرمز",
    saved: "تم حفظ رمز المشارك.",
    refusals: {
      invalid: "استخدم من حرفين إلى 6 أحرف أو أرقام، مع حرف واحد على الأقل.",
      duplicate_code: "يوجد مشارك آخر في هذا المشروع يستخدم هذا الرمز.",
      code_in_use: "يستخدم رقم مستند هذا الرمز بالفعل، فلم يعد قابلًا للتغيير.",
      forbidden: "لا يحدد رموز المشاركين إلا مسؤول المشروع.",
      unavailable: "حدث خطأ. حاول مرة أخرى.",
    },
  },
};
