import type { Locale } from "@rabaed/domain";
import type { WorkItemBoardLabels, WorkItemViewSwitchLabels } from "../components/views/work-item-board.tsx";
import type { WorkItemListLabels } from "../components/views/work-item-list.tsx";
import type { ProjectCardsLabels } from "../components/views/project-cards.tsx";
import type { ActivityFeedPanelLabels } from "../components/views/activity-feed-panel.tsx";
import type { ProjectDashboardLabels } from "../components/views/project-dashboard.tsx";

// Story copy for the views: the labels the app passes from its messages
// (apps/web/messages), in English and Arabic.

export const projectCardsLabels: Record<Locale, ProjectCardsLabels> = {
  en: { list: "Projects", needMyAction: "Need My Action", closed: "Closed", projectAdmin: "Project Admin" },
  ar: { list: "المشاريع", needMyAction: "بحاجة لإجرائي", closed: "مغلق", projectAdmin: "مسؤول المشروع" },
};

export const workItemListLabels: Record<Locale, WorkItemListLabels> = {
  en: {
    toolbar: "Filters and sort",
    all: "All",
    type: "Type",
    stage: "Stage",
    with: "With",
    withMe: "Me",
    notPickedUp: "not picked up",
    anyNotPickedUp: "Not picked up",
    trade: "Trade",
    location: "Location",
    outcome: "Review Code / Result",
    stepAge: "Step Age",
    weeksOrMore: (weeks, count) => (count === 1 ? `${weeks} week or more` : `${weeks} weeks or more`),
    sort: "Sort by",
    sortStepAge: "Step Age, oldest first",
    sortDocumentNumber: "Document Number",
    sortSubmissionDate: "Submission Date, latest first",
    submissionDate: "Submission Date",
    creationDate: "Creation Date",
    submittedFrom: "Submitted from",
    submittedTo: "Submitted to",
    allRevisions: "Show all Revisions",
    needMyAction: "Need My Action",
    clear: "Clear filters",
    stageCounts: "Items in each Stage",
    table: "Submittals",
    documentNumber: "Document Number",
    subject: "Subject",
    noNumber: "No number yet",
    revisionNoNumber: (revision) => `Revision ${revision}: no number yet`,
    empty: "No items you can see match these filters.",
    search: "Search",
    searchHelp: "Document Number, Subject, Type, Trade, Location or Company",
    noResults: "No items you can see match this search.",
    pages: "Pages",
    firstPage: "First page",
    nextPage: "Next page",
    cancelled: "Cancelled",
    dashboardFigure: "From the Dashboard",
    buckets: { pending: "Pending", in_preparation: "In preparation", approved: "Approved", rejected: "Rejected", cancelled: "Cancelled" },
    codeCStates: { approvedOnRevision: "approved on revision", awaitingRevision: "awaiting revision", noRevisionYet: "no Revision yet", revisionInProgress: "Revision in progress", rejectedAfterC: "rejected after C" },
  },
  ar: {
    toolbar: "التصفية والترتيب",
    all: "الكل",
    type: "النوع",
    stage: "المرحلة",
    with: "لدى",
    withMe: "أنا",
    notPickedUp: "لم تُستلَم",
    anyNotPickedUp: "لم تُستلَم",
    trade: "التخصص",
    location: "الموقع",
    outcome: "رمز المراجعة / النتيجة",
    stepAge: "عمر الخطوة",
    weeksOrMore: (weeks, count) => (count === 1 ? `${weeks} أسبوع أو أكثر` : `${weeks} أسابيع أو أكثر`),
    sort: "الترتيب حسب",
    sortStepAge: "عمر الخطوة، الأقدم أولًا",
    sortDocumentNumber: "رقم المستند",
    sortSubmissionDate: "تاريخ التقديم، الأحدث أولًا",
    submissionDate: "تاريخ التقديم",
    creationDate: "تاريخ الإنشاء",
    submittedFrom: "قُدِّم من",
    submittedTo: "قُدِّم حتى",
    allRevisions: "عرض كل المراجعات",
    needMyAction: "بحاجة لإجرائي",
    clear: "مسح التصفية",
    stageCounts: "العناصر في كل مرحلة",
    table: "الاعتمادات",
    documentNumber: "رقم المستند",
    subject: "الموضوع",
    noNumber: "بلا رقم بعد",
    revisionNoNumber: (revision) => `المراجعة ${revision}: بلا رقم بعد`,
    empty: "لا توجد عناصر يمكنك رؤيتها تطابق هذه التصفية.",
    search: "بحث",
    searchHelp: "رقم المستند أو الموضوع أو النوع أو التخصص أو الموقع أو الشركة",
    noResults: "لا توجد عناصر يمكنك رؤيتها تطابق هذا البحث.",
    pages: "الصفحات",
    firstPage: "الصفحة الأولى",
    nextPage: "الصفحة التالية",
    cancelled: "ملغى",
    dashboardFigure: "من لوحة المعلومات",
    buckets: { pending: "قيد الانتظار", in_preparation: "قيد الإعداد", approved: "معتمد", rejected: "مرفوض", cancelled: "ملغى" },
    codeCStates: { approvedOnRevision: "معتمد بعد التعديل", awaitingRevision: "بانتظار التعديل", noRevisionYet: "لا تعديل بعد", revisionInProgress: "التعديل جارٍ", rejectedAfterC: "مرفوض بعد C" },
  },
};

export const workItemBoardLabels: Record<Locale, WorkItemBoardLabels> = {
  en: {
    board: "Kanban",
    noNumber: "No number yet",
    revisionNoNumber: (revision) => `Revision ${revision}: no number yet`,
    notPickedUp: "not picked up",
    noItems: "No items",
    closedSince: (days) => `Closed in the last ${days} days`,
    total: (count) => `${count} in total`,
    showAll: "Show all",
    showAllIn: (stage) => `Show all in ${stage}`,
    move: "Move",
    moveItem: (subject) => `Move ${subject}`,
    moveTo: (stage) => `To ${stage}`,
    dragging: "Drop on a highlighted column to move the item.",
    cancelled: "Cancelled",
  },
  ar: {
    board: "كانبان",
    noNumber: "بلا رقم بعد",
    revisionNoNumber: (revision) => `المراجعة ${revision}: بلا رقم بعد`,
    notPickedUp: "لم تُستلَم",
    noItems: "لا توجد عناصر",
    closedSince: (days) => `أُغلقت خلال آخر ${days} يومًا`,
    total: (count) => `${count} إجمالًا`,
    showAll: "عرض الكل",
    showAllIn: (stage) => `عرض الكل في ${stage}`,
    move: "نقل",
    moveItem: (subject) => `نقل ${subject}`,
    moveTo: (stage) => `إلى ${stage}`,
    dragging: "أفلت العنصر على عمود مظلَّل لنقله.",
    cancelled: "ملغى",
  },
};

export const viewSwitchLabels: Record<Locale, WorkItemViewSwitchLabels> = {
  en: { view: "View", list: "List", kanban: "Kanban" },
  ar: { view: "طريقة العرض", list: "قائمة", kanban: "كانبان" },
};

export const projectDashboardLabels: Record<Locale, ProjectDashboardLabels> = {
  en: {
    items: (count) => `${count} items`,
    inPreparation: "In preparation",
    open: "Open",
    closed: "Closed",
    empty: "No Work Item Types on this Project yet.",
    codeC: "Code C",
    buckets: workItemListLabels.en.buckets,
    codeCStates: workItemListLabels.en.codeCStates,
    approved: { review_code: "Approved (A+B)", inspection_result: "Passed, with or without Comments", approval: "Approved", none: "Approved" },
  },
  ar: {
    items: (count) => `عدد العناصر: ${count}`,
    inPreparation: "قيد الإعداد",
    open: "مفتوحة",
    closed: "مغلقة",
    empty: "لا توجد أنواع عناصر عمل في هذا المشروع بعد.",
    codeC: "الرمز C",
    buckets: workItemListLabels.ar.buckets,
    codeCStates: workItemListLabels.ar.codeCStates,
    approved: { review_code: "المعتمد (A+B)", inspection_result: "الناجح، مع ملاحظات أو بدونها", approval: "المعتمد", none: "المعتمد" },
  },
};

export const activityFeedPanelLabels: Record<Locale, ActivityFeedPanelLabels> = {
  en: {
    title: "Activity Feed",
    module: "Module",
    type: "Type",
    all: "All",
    mine: "Only items I'm on",
    viewAll: "View all",
    loadMore: "Load more",
    loading: "Loading…",
    empty: "Nothing has happened on the items you can see yet.",
    internal: "Only your Company sees this",
    noNumber: "No number yet",
    pickedUp: "picked up",
    returnedToPool: "returned to the pool",
    assigned: "assigned",
    internalNote: "wrote an Internal Note with",
    recommended: "recommended a Code on",
    cancelled: "cancelled",
    updated: "updated",
  },
  ar: {
    title: "النشاط",
    module: "الوحدة",
    type: "النوع",
    all: "الكل",
    mine: "العناصر التي أشارك فيها فقط",
    viewAll: "عرض الكل",
    loadMore: "تحميل المزيد",
    loading: "جارٍ التحميل…",
    empty: "لم يحدث شيء بعد على العناصر التي يمكنك رؤيتها.",
    internal: "لا يراه إلا شركتك",
    noNumber: "بلا رقم بعد",
    pickedUp: "استلم",
    returnedToPool: "أعاد إلى المجموعة",
    assigned: "أسند",
    internalNote: "كتب ملاحظة داخلية مع",
    recommended: "أوصى برمز على",
    cancelled: "ألغى",
    updated: "حدّث",
  },
};
