import type { Locale, WorkItemOutcome } from "@rabaed/domain";
import type { WorkItemBoardLabels, WorkItemViewSwitchLabels } from "../components/views/work-item-board.tsx";
import type { WorkItemListLabels } from "../components/views/work-item-list.tsx";
import type { ProjectCardsLabels } from "../components/views/project-cards.tsx";

// Story copy for the views: the labels the app passes from its messages
// (apps/web/messages), in English and Arabic.

export const projectCardsLabels: Record<Locale, ProjectCardsLabels> = {
  en: { list: "Projects", needMyAction: "Need My Action", closed: "Closed", projectAdmin: "Project Admin" },
  ar: { list: "المشاريع", needMyAction: "بحاجة لإجرائي", closed: "مغلق", projectAdmin: "مسؤول المشروع" },
};

const outcomes: Record<Locale, Record<WorkItemOutcome, string>> = {
  en: {
    A: "Code A",
    B: "Code B",
    C: "Code C",
    D: "Code D",
    passed: "Passed",
    passed_with_comments: "Passed with Comments",
    failed: "Failed",
    cancelled: "Cancelled",
    closed: "Closed",
  },
  ar: {
    A: "الرمز A",
    B: "الرمز B",
    C: "الرمز C",
    D: "الرمز D",
    passed: "ناجح",
    passed_with_comments: "ناجح مع ملاحظات",
    failed: "راسب",
    cancelled: "ملغى",
    closed: "مغلق",
  },
};

export const workItemListLabels: Record<Locale, WorkItemListLabels> = {
  en: {
    toolbar: "Filters and sort",
    all: "All",
    type: "Type",
    stage: "Stage",
    with: "With",
    withMe: "Me",
    unclaimed: "unclaimed",
    anyUnclaimed: "Unclaimed",
    trade: "Trade",
    location: "Location",
    outcome: "Review Code / Result",
    stepAge: "Step Age",
    weeksOrMore: (weeks) => `${weeks} weeks or more`,
    sort: "Sort by",
    sortStepAge: "Step Age, oldest first",
    sortDocumentNumber: "Document Number",
    sortSubmissionDate: "Submission Date, latest first",
    submissionDate: "Submission Date",
    creationDate: "Creation Date",
    submittedFrom: "Submitted from",
    submittedTo: "Submitted to",
    allRevisions: "Show all Revisions",
    needMyAction: "Need My Action",
    clear: "Clear filters",
    stageCounts: "Items in each Stage",
    table: "Submittals",
    documentNumber: "Document Number",
    subject: "Subject",
    noNumber: "No number yet",
    revisionNoNumber: (revision) => `Revision ${revision}: no number yet`,
    empty: "No items you can see match these filters.",
    search: "Search",
    searchHelp: "Document Number, Subject, Type, Trade, Location or Company",
    noResults: "No items you can see match this search.",
    pages: "Pages",
    firstPage: "First page",
    nextPage: "Next page",
    outcomes: outcomes.en,
    dashboardFigure: "From the Dashboard",
    buckets: { pending: "Pending", in_preparation: "In preparation", A: "Approved (A)", B: "Approved (B)", C: "Revise (C)", D: "Rejected (D)", passed: "Passed", passed_with_comments: "Passed with Comments", failed: "Failed", approved: "Approved", rejected: "Rejected", cancelled: "Cancelled" },
    codeCStates: { approvedOnRevision: "approved on revision", awaitingRevision: "awaiting revision", noRevisionYet: "no Revision yet", revisionInProgress: "Revision in progress", rejectedAfterC: "rejected after C" },
  },
  ar: {
    toolbar: "التصفية والترتيب",
    all: "الكل",
    type: "النوع",
    stage: "المرحلة",
    with: "لدى",
    withMe: "أنا",
    unclaimed: "لم تُستلَم",
    anyUnclaimed: "لم تُستلَم",
    trade: "التخصص",
    location: "الموقع",
    outcome: "رمز المراجعة / النتيجة",
    stepAge: "عمر الخطوة",
    weeksOrMore: (weeks) => `${weeks} أسابيع أو أكثر`,
    sort: "الترتيب حسب",
    sortStepAge: "عمر الخطوة، الأقدم أولًا",
    sortDocumentNumber: "رقم المستند",
    sortSubmissionDate: "تاريخ التقديم، الأحدث أولًا",
    submissionDate: "تاريخ التقديم",
    creationDate: "تاريخ الإنشاء",
    submittedFrom: "قُدِّم من",
    submittedTo: "قُدِّم حتى",
    allRevisions: "عرض كل المراجعات",
    needMyAction: "بحاجة لإجرائي",
    clear: "مسح التصفية",
    stageCounts: "العناصر في كل مرحلة",
    table: "الاعتمادات",
    documentNumber: "رقم المستند",
    subject: "الموضوع",
    noNumber: "بلا رقم بعد",
    revisionNoNumber: (revision) => `المراجعة ${revision}: بلا رقم بعد`,
    empty: "لا توجد عناصر يمكنك رؤيتها تطابق هذه التصفية.",
    search: "بحث",
    searchHelp: "رقم المستند أو الموضوع أو النوع أو التخصص أو الموقع أو الشركة",
    noResults: "لا توجد عناصر يمكنك رؤيتها تطابق هذا البحث.",
    pages: "الصفحات",
    firstPage: "الصفحة الأولى",
    nextPage: "الصفحة التالية",
    outcomes: outcomes.ar,
    dashboardFigure: "من لوحة المعلومات",
    buckets: { pending: "قيد الانتظار", in_preparation: "قيد الإعداد", A: "معتمد (A)", B: "معتمد (B)", C: "للتعديل (C)", D: "مرفوض (D)", passed: "ناجح", passed_with_comments: "ناجح مع ملاحظات", failed: "راسب", approved: "معتمد", rejected: "مرفوض", cancelled: "ملغى" },
    codeCStates: { approvedOnRevision: "معتمد بعد التعديل", awaitingRevision: "بانتظار التعديل", noRevisionYet: "لا تعديل بعد", revisionInProgress: "التعديل جارٍ", rejectedAfterC: "مرفوض بعد C" },
  },
};

export const workItemBoardLabels: Record<Locale, WorkItemBoardLabels> = {
  en: {
    board: "Kanban",
    noNumber: "No number yet",
    revisionNoNumber: (revision) => `Revision ${revision}: no number yet`,
    unclaimed: "unclaimed",
    noItems: "No items",
    closedSince: (days) => `Closed in the last ${days} days`,
    total: (count) => `${count} in total`,
    showAll: "Show all",
    showAllIn: (stage) => `Show all in ${stage}`,
    move: "Move",
    moveItem: (subject) => `Move ${subject}`,
    moveTo: (stage) => `To ${stage}`,
    dragging: "Drop on a highlighted column to move the item.",
    outcomes: outcomes.en,
  },
  ar: {
    board: "كانبان",
    noNumber: "بلا رقم بعد",
    revisionNoNumber: (revision) => `المراجعة ${revision}: بلا رقم بعد`,
    unclaimed: "لم تُستلَم",
    noItems: "لا توجد عناصر",
    closedSince: (days) => `أُغلقت خلال آخر ${days} يومًا`,
    total: (count) => `${count} إجمالًا`,
    showAll: "عرض الكل",
    showAllIn: (stage) => `عرض الكل في ${stage}`,
    move: "نقل",
    moveItem: (subject) => `نقل ${subject}`,
    moveTo: (stage) => `إلى ${stage}`,
    dragging: "أفلت العنصر على عمود مظلَّل لنقله.",
    outcomes: outcomes.ar,
  },
};

export const viewSwitchLabels: Record<Locale, WorkItemViewSwitchLabels> = {
  en: { view: "View", list: "List", kanban: "Kanban" },
  ar: { view: "طريقة العرض", list: "قائمة", kanban: "كانبان" },
};
