// Part B — View workflow inside a submittal. Exposes window.WV.
(function(){
const S=RS.S,{END,CO,VERS,W,H,renderDiagram,box}=WF;
const L=(e,a)=>S.lang==='ar'?a:e;const esc=RS.esc;
const P={hafiz:['Hafiz Hamdan','حافظ حمدان','ctr','Contractor Engineer','مهندس المقاول'],ali:['Ali Sonour','علي سنور','ctr','Contractor PM','مدير مشروع المقاول'],ahmed:['Ahmed bin Said','أحمد بن سعيد','cns','Consultant Engineer','مهندس الاستشاري'],shamsi:['Mohammed Al Shamsi','محمد الشامسي','cns','Consultant Manager','مدير الاستشاري'],hassan:['Hassan Al Marri','حسن المري','own','Owner Representative','ممثل المالك']};
const VIEW={ctrpm:{en:'Contractor PM (Ali)',ar:'مدير المقاول (علي)',co:'ctr',me:'ali'},ctr:{en:'Contractor Engineer',ar:'مهندس المقاول',co:'ctr',me:'hafiz'},cns:{en:'Consultant Manager',ar:'مدير الاستشاري',co:'cns',me:'shamsi'},own:{en:'Owner Rep',ar:'ممثل المالك',co:'own',me:'hassan'}};
// scenarios: path = [{s, by, t (transition taken out of s), at, sign, rec}]
const SC={
 internal:{no:'TWR-TMC-EL-MAR-052',t:['Cable Trays & Supports','حوامل ودعامات الكابلات'],rev:0,v:3,stage:['Internal Review','مراجعة داخلية','blue'],path:[{s:'s1',by:'hafiz',t:'t1',at:'23/09/2026 10:02'}],cur:'s2',holder:'ali',wk:1},
 pending:{no:'TWR-TMC-EL-MAR-041',t:['Lighting Fixtures','وحدات الإنارة'],rev:1,v:2,stage:['Pending Approval','بانتظار الاعتماد','violet'],path:[{s:'s1',by:'hafiz',t:'t1',at:'12/06/2025 09:14'},{s:'s2',by:'ali',t:'t2',at:'15/06/2025 11:40',ret:1},{s:'s1',by:'hafiz',t:'t1',at:'17/06/2025 08:55'},{s:'s2',by:'ali',t:'t3',at:'19/06/2025 16:19',sign:1},{s:'s3',by:'ahmed',t:'t4',at:'24/06/2025 13:05',rec:'B'}],cur:'s4',pool:['shamsi','ahmed'],wk:2},
 closed:{no:'TWR-TMC-EL-MAR-041',t:['Lighting Fixtures','وحدات الإنارة'],rev:0,v:2,stage:['Revise & Resubmit','مراجعة وإعادة تقديم','orange'],path:[{s:'s1',by:'hafiz',t:'t1',at:'02/06/2025 09:30'},{s:'s2',by:'ali',t:'t3',at:'04/06/2025 15:10',sign:1},{s:'s3',by:'ahmed',t:'t4',at:'10/06/2025 12:00',rec:'C'},{s:'s4',by:'shamsi',t:'t8',at:'21/06/2025 10:22',sign:1}],cur:'eC',wk:0}};
const X={view:'ctr',sc:'pending',open:false,phone:false,peek:false,toast:null};
const ageDots=w=>{const n=Math.min(4,Math.max(1,Math.round(w)));const c=n>=4?'#e5484d':n===3?'#ee964b':'#9aa0ad';return `<span class="age">${[1,2,3,4].map(i=>`<i style="${i<=n?`background:${c};box-shadow:none`:''}"></i>`).join('')}</span>`};
const nm=p=>L(P[p][0],P[p][1]),role=p=>L(P[p][3],P[p][4]);
const CODEC={A:'green',B:'green',C:'orange',D:'red'};
const cdb=c=>`<span class="cdb" style="background:var(--tone-${CODEC[c]}-tint);color:var(--tone-${CODEC[c]}-fg)"><i class="ti ${c==='B'?'ti-message-circle':c==='C'?'ti-refresh':c==='D'?'ti-x':'ti-check'}"></i>Code ${c}</span>`;
function model(){const sc=SC[X.sc],vv=VIEW[X.view],ver=VERS.find(v=>v.v===sc.v);const St=ver.S,T=ver.T,rtl=S.lang==='ar';
 const other=id=>{const s=St[id];return s&&!s.end&&s.co!==vv.co};
 const cos=[...new Set(Object.keys(St).filter(other).map(id=>St[id].co))];
 const groups=cos.map(co=>{const ids=Object.keys(St).filter(id=>other(id)&&St[id].co===co);const xs=ids.map(i=>St[i].x),ys=ids.map(i=>St[i].y);let x=Math.min(...xs)-10,y=Math.min(...ys)-10,w=Math.max(...xs)+WF.CW+10-x,h=Math.max(...ys)+WF.CH+10-y;if(rtl)x=W-x-w;
  const inHere=ids.includes(sc.cur);const passed=sc.path.some(p=>ids.includes(p.s));const fin=sc.path.find(p=>ids.includes(p.s)&&T[p.t]&&St[T[p.t].to].end);
  let an='';if(fin)an=`${cdb(T[fin.t].code)} ${L('issued','صدر')} · <span class="num">${fin.at.split(' ')[0]}</span> ✍ ${nm(fin.by)}, ${role(fin.by)}`;else if(inHere)an=`${L('In review','قيد المراجعة')} · ${ageDots(sc.wk)} ${L(sc.wk+' weeks at this step',sc.wk+' أسابيع في هذه الخطوة')}`;
  return {ids,x,y,w,h,co,title:co==='ctr'?L('TMC Constructions internal review','المراجعة الداخلية لـ تي إم سي'):co==='cns'?L('Design Consultants LLC review','مراجعة ديزاين للاستشارات'):L('Al Futtaim PMC review','مراجعة الفطيم لإدارة المشاريع'),sub:L(co==='ctr'?'Drafts · Internal Review':'Pending Approval',co==='ctr'?'المسودات · مراجعة داخلية':'بانتظار الاعتماد'),an,cls:inHere?'cur':passed||fin?'done':'fade'}});
 const gOf=id=>groups.find(g=>g.ids.includes(id));
 const hide={};Object.entries(T).forEach(([k,t])=>{const a=gOf(t.f),b=gOf(t.to);if(a&&b&&a===b)hide[k]=1;else if(a&&!sc.path.some(p=>p.t===k)&&!(k===Object.keys(T).find(x=>T[x].f===t.f&&!gOf(T[x].to)&&false)))hide[k]=1});
 // keep edges entering a group
 Object.entries(T).forEach(([k,t])=>{if(!gOf(t.f)&&gOf(t.to))delete hide[k]});
 const scls={},ecls={},annot={};const passed=new Set(sc.path.map(p=>p.s));
 Object.keys(St).forEach(id=>{scls[id]=passed.has(id)?'done':'fade'});scls[sc.cur]='cur';
 Object.keys(T).forEach(k=>{ecls[k]=sc.path.some(p=>p.t===k)?'done':'fade'});
 const holds=sc.holder===vv.me||(sc.pool&&sc.pool.includes(vv.me));
 if(!St[sc.cur].end)Object.entries(T).forEach(([k,t])=>{if(t.f===sc.cur&&!hide[k])ecls[k]='next'+(holds?'':' info')});
 sc.path.forEach(p=>{if(gOf(p.s))return;const t=T[p.t];const ev=`${nm(p.by)} · ${role(p.by)} · ${p.ret?L('Returned','أرجع'):esc(L(t.en,t.ar))} · <span class="num">${p.at}</span>${p.sign?' ✍':''}${p.rec&&St[p.s].co===vv.co?`<br>${L('Recommended','أوصى بـ')} ${cdb(p.rec)}`:''}`;annot[p.s]=(annot[p.s]?annot[p.s]+'<hr style="border:0;border-top:1px dashed var(--ui-border);margin:4px 0">':'')+ev});
 if(!St[sc.cur].end&&!gOf(sc.cur))annot[sc.cur]=(annot[sc.cur]?annot[sc.cur]+'<hr style="border:0;border-top:1px dashed var(--ui-border);margin:4px 0">':'')+`<b style="font-size:11px">${sc.holder?nm(sc.holder):L(`Pool: Design Consultants LLC (${sc.pool.length} people)`,`مجموعة: ديزاين للاستشارات (${sc.pool.length} أشخاص)`)}</b> · ${ageDots(sc.wk)} ${L(sc.wk+(sc.wk===1?' week':' weeks'),sc.wk+' أسابيع')}`;
 if(St[sc.cur].end){const last=sc.path[sc.path.length-1];annot[sc.cur]=`<span class="num">${last.at.split(' ')[0]}</span>`}
 return {sc,vv,ver,St,T,rtl,groups,hide,scls,ecls,annot,holds,gOf}}
function diagram(m){return renderDiagram({L,S:m.St,T:m.T,rtl:m.rtl,groups:m.groups,hide:m.hide,scls:m.scls,ecls:m.ecls,annot:m.annot,hideOut:1})}
function timeline(m){const items=[];const seen=new Set();
 m.sc.path.forEach(p=>{const g=m.gOf(p.s);if(g){if(seen.has(g))return;seen.add(g);items.push({g});return}items.push({p})});
 if(!m.St[m.sc.cur].end&&!m.gOf(m.sc.cur))items.push({cur:1});else if(m.gOf(m.sc.cur)&&!seen.has(m.gOf(m.sc.cur)))items.push({g:m.gOf(m.sc.cur)});
 if(m.St[m.sc.cur].end)items.push({end:1});
 return `<div class="ptl">${items.map(it=>{if(it.g)return `<div class="pti ${it.g.cls}"><span class="d" style="background:var(--tone-violet-solid)"><i class="ti ti-lock"></i></span><div class="c"><b>${esc(it.g.title)}</b><small>${it.g.sub}</small>${it.g.an?`<div class="an">${it.g.an}</div>`:''}</div></div>`;
  if(it.p){const s=m.St[it.p.s],t=m.T[it.p.t];return `<div class="pti done"><span class="d"><i class="ti ${it.p.ret?'ti-arrow-back-up':'ti-check'}"></i></span><div class="c"><b>${esc(L(s.en,s.ar))}</b><div class="an">${nm(it.p.by)} · ${it.p.ret?L('Returned','أرجع'):esc(L(t.en,t.ar))}<br><span class="num">${it.p.at}</span>${it.p.sign?' ✍':''}</div></div></div>`}
  if(it.end){const e=END[m.St[m.sc.cur].end];return `<div class="pti done"><span class="d" style="background:var(--tone-${e[2]}-solid)"><i class="ti ${e[3]}"></i></span><div class="c"><b>${L(e[0],e[1])}</b></div></div>`}
  const s=m.St[m.sc.cur];return `<div class="pti cur"><span class="d"><i class="ti ti-player-play"></i></span><div class="c"><b>${esc(L(s.en,s.ar))}</b><div class="an">${m.annot[m.sc.cur]}</div><div class="nx">${Object.entries(m.T).filter(([k,t])=>t.f===m.sc.cur&&!m.hide[k]).map(([k,t])=>`<button class="cb sm${m.holds?' pri':''}" ${m.holds?`data-do="${k}"`:'disabled'}>${t.sign?'<i class="ti ti-signature"></i>':''}${esc(L(t.en,t.ar))}</button>`).join('')}</div></div></div>`}).join('')}</div>`}
function drawer(){if(!X.open)return '';const m=model(),sc=m.sc;const newer=sc.v<3;
 return `<div class="scrim" data-close="1"><div class="wvd" data-stop>
 <div class="wvh"><div style="min-width:0"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><span class="num" style="font-size:12.5px;font-weight:700;color:var(--ui-muted)">${sc.no}</span><span class="vs pub">Rev ${sc.rev}</span></div><h3>${L('Material Submittal – 2-tier review','اعتماد المواد – مراجعة على مستويين')} · v${sc.v}</h3></div><span style="flex:1"></span>
 <span class="segv" title="${L('Demo · view as','عرض توضيحي · العرض بصفة')}">${Object.entries(VIEW).map(([k,v])=>`<button class="${X.view===k?'on':''}" data-vw="${k}">${L(v.en,v.ar)}</button>`).join('')}</span><span class="segv"><button class="${!X.phone?'on':''}" data-ph="0"><i class="ti ti-device-desktop"></i></button><button class="${X.phone?'on':''}" data-ph="1"><i class="ti ti-device-mobile"></i></button></span><button class="cb ter ic" data-close="1"><i class="ti ti-x"></i></button></div>
 <div class="wvb">${sc.rev?`<div class="rch"><span>${L('Revisions','المراجعات')}</span><button data-sc="closed">Rev 0 ${cdb('C')}</button><i class="ti ti-chevron-right"></i><button class="on" data-sc="pending">Rev 1 · ${L('current','الحالي')}</button></div>`:sc.no.endsWith('041')?`<div class="rch"><span>${L('Revisions','المراجعات')}</span><button class="on">Rev 0 ${cdb('C')}</button><i class="ti ti-chevron-right"></i><button data-sc="pending">Rev 1</button></div>`:''}
 ${newer?`<div class="lockb" style="background:var(--tone-blue-tint);color:var(--tone-blue-fg)"><i class="ti ti-info-circle"></i>${L(`This item follows v${sc.v}. The workflow was updated to v3.`,`يتبع هذا العنصر v${sc.v}. تم تحديث سير العمل إلى v3.`)}<a class="cb sm" style="margin-inline-start:auto;text-decoration:none" href="settings-workflows.html">${L('View v3','عرض v3')}</a></div>`:''}
 ${X.phone?`<div class="phone" style="margin:0 auto;height:720px"><div class="scr" style="background:var(--ui-canvas)"><div class="notch"></div><div class="sm-hd2"><b>${L('Workflow','سير العمل')}</b><small class="num">${sc.no} · v${sc.v}</small></div><div style="position:absolute;inset:100px 0 0;overflow:auto;padding:0 14px 30px">${m.groups.length?note():''}${timeline(m)}</div><div class="m-home"></div></div></div>`:`<div class="wcv" style="flex:1;min-height:420px"><div class="wstage" id="wst">${diagram(m)}</div><div class="wctl"><button data-z="out"><i class="ti ti-zoom-out"></i></button><button data-z="in"><i class="ti ti-zoom-in"></i></button><button data-z="fit"><i class="ti ti-maximize"></i></button></div></div>${m.groups.length?note():''}`}
 </div></div></div>`}
const note=()=>`<div class="gnote"><i class="ti ti-info-circle"></i>${L('Some steps are grouped because they are internal to another company.','بعض الخطوات مجمّعة لأنها داخلية لشركة أخرى.')}</div>`;
function page(){if(X.open)setTimeout(applyFit,40);const m=model(),sc=m.sc,vv=m.vv;const g=m.gOf(sc.cur);const st=sc.stage;
 const holderTxt=m.St[sc.cur].end?L('Closed','مغلق'):g?esc(g.title):sc.holder?`${nm(sc.holder)} · ${role(sc.holder)}`:L(`Pool: Design Consultants LLC (${sc.pool.length})`,`مجموعة: ديزاين للاستشارات (${sc.pool.length})`);
 const log=sc.path.filter(p=>!m.gOf(p.s)||(m.T[p.t]&&m.St[m.T[p.t].to].end)).map(p=>{const t=m.T[p.t];const fin=m.St[t.to].end;return `<div class="alog"><span class="av" style="width:28px;height:28px;font-size:10px;background:${P[p.by][2]==='ctr'?'#f8552f':'#3d6db5'}">${RS.ini(P[p.by][0])}</span><div><b>${nm(p.by)}</b> <small>${role(p.by)}</small><div>${p.ret?L('Returned','أرجع'):esc(L(t.en,t.ar))}${p.sign?' ✍':''}${fin?' '+cdb(t.code):''}</div><small class="num">${p.at}</small></div></div>`}).reverse().join('');
 return `<div class="sp-hd"><button class="cb ter sm"><i class="ti ti-arrow-left"></i></button><div style="min-width:0"><div style="display:flex;gap:8px;align-items:center;flex-wrap:wrap"><span class="num" style="font-size:12.5px;font-weight:700;color:var(--ui-muted)">${sc.no}</span><span class="vs pub">Rev ${sc.rev}</span><span class="stp" style="background:var(--tone-${st[2]}-tint);color:var(--tone-${st[2]}-fg)"><i></i>${L(st[0],st[1])}</span></div><h1>${esc(L(sc.t[0],sc.t[1]))}</h1></div><span style="flex:1"></span><span class="segv" title="demo">${Object.entries(SC).map(([k,s])=>`<button class="${X.sc===k?'on':''}" data-sc="${k}">${k==='internal'?L('Internal Review','مراجعة داخلية'):k==='pending'?L('Pending Approval','بانتظار الاعتماد'):L('Closed · Code C','مغلق · Code C')}</button>`).join('')}</span><span class="rel"><button class="vis" data-menu="vw"><i class="ti ti-eye"></i>${L(vv.en,vv.ar)}<i class="ti ti-chevron-down"></i></button>${X.menu?`<div class="pop end" data-stop>${Object.entries(VIEW).map(([k,v])=>`<button class="mi${X.view===k?' on':''}" data-vw="${k}">${L(v.en,v.ar)}</button>`).join('')}</div>`:''}</span></div>
 <div class="sp-body"><div class="card" style="overflow:hidden"><div class="wtabs" style="padding:0 18px;margin:0">${[L('Submittal Details','تفاصيل التقديم'),L('Chat','المحادثة'),L('Internal Communication','التواصل الداخلي')].map((t,i)=>`<button class="${i?'':'on'}">${t}</button>`).join('')}</div><div style="padding:18px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px 24px;font-size:13px">${[[L('Type','النوع'),'MAR · Material Approval Request'],[L('Trade','التخصص'),L('Electrical','كهرباء')],[L('Location','الموقع'),L('Tower 1 · Floor 02','البرج ١ · الطابق ٠٢')],[L('Supplier','المورّد'),'Thorn Lighting'],[L('Cost impact','أثر التكلفة'),'<span class="num">320,000 SAR</span>'],[L('Contractor','المقاول'),'TMC Constructions']].map(k=>`<div><div style="color:var(--ui-muted);margin-bottom:3px">${k[0]}</div><b>${k[1]}</b></div>`).join('')}</div></div>
 <aside style="display:flex;flex-direction:column;gap:12px"><div class="card" style="padding:16px;display:flex;flex-direction:column;gap:10px"><div style="display:flex;align-items:center;gap:8px"><b style="font-size:14px">${L('Status','الحالة')}</b><button class="cb sm" data-act="open" style="margin-inline-start:auto"><i class="ti ti-git-branch"></i>${L('View workflow','عرض سير العمل')}</button></div><span class="stp" style="align-self:flex-start;background:var(--tone-${st[2]}-tint);color:var(--tone-${st[2]}-fg)"><i></i>${L(st[0],st[1])}</span><div style="font-size:13px"><span style="color:var(--ui-muted)">${L('With','لدى')}</span> <b>${holderTxt}</b></div>${!m.St[sc.cur].end?`<div style="font-size:12.5px;color:var(--ui-muted);display:flex;gap:8px;align-items:center">${ageDots(sc.wk)} ${L(sc.wk+(sc.wk===1?' week':' weeks')+' at this step',sc.wk+' أسابيع في هذه الخطوة')}</div>`:''}${sc.v<3?`<div style="font-size:12px;color:var(--tone-blue-fg);display:flex;gap:6px"><i class="ti ti-info-circle"></i>${L('Workflow updated to v3','تم تحديث سير العمل إلى v3')} · <a data-act="open" style="cursor:pointer;font-weight:600">${L('View new version','عرض الإصدار الجديد')}</a></div>`:''}</div>
 <div class="card" style="padding:16px"><b style="font-size:14px">${L('Approvals Log','سجل الاعتمادات')}</b>${log||`<div style="font-size:12.5px;color:var(--ui-faint);margin-top:8px">—</div>`}</div></aside></div>${drawer()}${X.toast?`<div class="toast"><i class="ti ti-circle-check"></i>${X.toast}</div>`:''}`}
function applyFit(){const s=document.getElementById('wst');if(!s)return;const w=s.querySelector('.wworld');const r=s.getBoundingClientRect();const k=X.k||Math.min(r.width/W,r.height/(H+30))*.98;X.kk=k;w.style.transform=`translate(${(r.width-W*k)/2+(X.dx||0)}px,${6+(X.dy||0)}px) scale(${k})`}
function bind(root,R){let tt;const flash=m=>{X.toast=m;R();clearTimeout(tt);tt=setTimeout(()=>{X.toast=null;R()},2200)};
 root.addEventListener('click',e=>{const b=e.target.closest('[data-act],[data-vw],[data-sc],[data-ph],[data-close],[data-menu],[data-do],[data-z],.wl.next:not(.info)');if(!b){if(X.menu){X.menu=null;R()}return}if(b.closest('.hd,.tabs,.sb'))return;const d=b.dataset;
  if(d.close!==undefined){if(e.target.closest('[data-stop]')&&!b.closest('button'))return;X.open=false;return R()}
  if(d.menu){X.menu=!X.menu;return R()}
  if(d.vw){X.view=d.vw;X.menu=null;X.k=0;X.dx=X.dy=0;return R()}
  if(d.sc){X.sc=d.sc;if(d.sc==='internal')X.view='ctrpm';X.k=0;return R()}
  if(d.ph!==undefined){X.phone=d.ph==='1';return R()}
  if(d.act==='open'){X.open=true;X.k=0;X.dx=X.dy=0;return R()}
  if(d.z){if(d.z==='fit'){X.k=0;X.dx=X.dy=0}else X.k=(X.kk||.7)*(d.z==='in'?1.2:1/1.2);return applyFit()}
  const tid=d.do||d.t;if(tid){const t=VERS.find(v=>v.v===SC[X.sc].v).T[tid];return flash(L(`“${t.en}”${t.sign?' — signature & confirmation':''} would open here`,`«${t.ar}» سيُفتح هنا`))}
 });
 let D=null;root.addEventListener('pointerdown',e=>{if(e.target.closest('#wst')&&!e.target.closest('.wl'))D={x:e.clientX,y:e.clientY,dx:X.dx||0,dy:X.dy||0}});
 addEventListener('pointermove',e=>{if(!D)return;X.dx=D.dx+e.clientX-D.x;X.dy=D.dy+e.clientY-D.y;applyFit()});addEventListener('pointerup',()=>D=null);
 addEventListener('resize',applyFit);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&X.open){X.open=false;R()}});
}
window.WV={X,page,bind,applyFit};
})();
