// Settings → Workflows (Part A). Exposes window.WA.
(function(){
const S=RS.S,{STG,END,CO,FIELDS,VERS,LIB,W,H,renderDiagram,clone}=WF;
const L=(e,a)=>S.lang==='ar'?a:e;const esc=RS.esc;
const V={page:'list',tab:'project',dtab:'diagram',ver:3,empty:false,menu:null,modal:null,toast:null,
 ed:null,sel:null,undo:[],redo:[],dirty:false,k:.72,tx:14,ty:14,sim:null,cost:620000,types:{MAR:'mat',SAR:'mat',DAR:'doc',IR:'ir',SNG:'snag',CMT:'snag',DSR:'dsr'},pubNote:'',noteErr:false};
const draft=()=>VERS.find(v=>v.st==='draft');
const vsel=()=>VERS.find(v=>v.v===V.ver);
/* ---- validation ---- */
function validate(d){const out=[];const {S:St,T}=d;
 Object.entries(St).forEach(([id,s])=>{if(s.end)return;if(!Object.values(T).some(t=>t.f===id))out.push({lv:'err',id,msg:[`Step “${s.en}” has no way forward`,`الخطوة «${s.ar}» ليس لها مسار للأمام`]})});
 Object.entries(T).forEach(([id,t])=>{const a=St[t.f],b=St[t.to];if(!a||!b)return;
  if((t.type==='submit'||t.code)&&!t.sign)out.push({lv:'err',id,msg:[`“${t.en}” sets a hand-over or final code and must require signature`,`«${t.ar}» يجب أن يتطلب توقيعًا`]});
  if(t.type==='return'&&!b.end&&a.co!==b.co)out.push({lv:'err',id,msg:[`Return “${t.en}” crosses companies — Return can only go back within the same company`,`الإرجاع «${t.ar}» يعبر بين الشركات — مسموح داخل نفس الشركة فقط`]});
  if(t.type==='send'&&!b.end&&a.co!==b.co)out.push({lv:'err',id,msg:[`“${t.en}” is a Send but goes to another company — use Submit`,`«${t.ar}» إرسال إلى شركة أخرى — استخدم تقديم`]});
  (t.cond||[]).forEach(c=>{if(!FIELDS.includes(c.f))out.push({lv:'err',id,msg:[`Condition uses field “${c.f}” that doesn’t exist in the form`,`الشرط يستخدم الحقل «${c.f}» غير الموجود في النموذج`]})})});
 const byF={};Object.entries(T).forEach(([id,t])=>{if(t.cond&&t.cond.length)(byF[t.f]=byF[t.f]||[]).push(id)});Object.values(byF).forEach(ids=>{if(ids.length>1)out.push({lv:'warn',id:ids[1],msg:['Two conditions from the same step can both match','شرطان من نفس الخطوة قد يتحققان معًا']})});
 return out}
/* ---- shared chrome ---- */
function nav(){const it=[['general','ti-settings','General','عام'],['participants','ti-users','Participants','المشاركون'],['visibility','ti-eye','Visibility','الظهور'],['positions','ti-user-circle','Positions','المناصب'],['trades','ti-map-pin','Trades & Locations','التخصصات والمواقع'],['stages','ti-list-check','Stages','المراحل'],['numbering','ti-list','Document Numbering','ترقيم المستندات'],['workflows','ti-refresh','Workflows','سير العمل'],['types','ti-file-text','Work Item Types','أنواع العناصر'],['forms','ti-clipboard-text','Forms','النماذج'],['suppliers','ti-building','Approved Suppliers','الموردون المعتمدون'],['activity','ti-clock','Activity','النشاط']];
 return `<nav class="st-nav"><h6>${L('Project settings','إعدادات المشروع')}</h6>${it.map(i=>`<button class="${(V.page==='types'?'types':'workflows')===i[0]?'on':''}" data-snav="${i[0]}"><i class="ti ${i[1]}"></i>${L(i[2],i[3])}</button>`).join('')}</nav>`}
const vst=w=>w.ro?`<span class="vs ro"><i class="ti ti-lock"></i>${L('Read-only','للقراءة فقط')}</span>`:w.lib?`<span class="vs pub">${L('Library','المكتبة')}</span>`:`<span class="vs pub"><i class="ti ti-check"></i>${L('Published','منشور')} v${w.runs.length}</span>${w.draft?` <span class="vs draft"><i class="ti ti-pencil"></i>${L('Draft','مسودة')} v${w.draft}</span>`:''}`;
function list(){const rows=V.empty&&V.tab==='project'?[]:LIB[V.tab];
 return `<div class="st-hd"><div><h1>${L('Workflows','سير العمل')}</h1><p>${L('Each Work Item Type follows one workflow. Publishing a new version never changes items already running.','يتبع كل نوع عنصر سير عمل واحدًا. نشر إصدار جديد لا يغيّر العناصر الجارية.')}</p></div><div class="act"><span class="rel"><button class="cb pri" data-menu="new"><i class="ti ti-plus"></i>${L('New workflow','سير عمل جديد')}<i class="ti ti-chevron-down"></i></button>${V.menu==='new'?`<div class="pop end" data-stop style="min-width:260px"><button class="mi" data-act="newblank"><i class="ti ti-file"></i>${L('Start blank','البدء من الصفر')}</button><button class="mi" data-tab="rabaed"><i class="ti ti-copy"></i>${L('Copy from Rabaed Default','نسخ من إعدادات ربائد')}</button><button class="mi" data-tab="company"><i class="ti ti-building"></i>${L('Copy from Company library','نسخ من مكتبة الشركة')}</button></div>`:''}</span><button class="cb ic" data-act="toggleempty" title="${L('Demo: empty state','عرض: حالة فارغة')}"><i class="ti ti-dots"></i></button></div></div>
 <div class="wtabs">${[['project',L('In this project','في هذا المشروع'),LIB.project.length],['company',L('Company library','مكتبة الشركة'),LIB.company.length],['rabaed',L('Rabaed Defaults','إعدادات ربائد'),LIB.rabaed.length]].map(t=>`<button class="${V.tab===t[0]?'on':''}" data-tab="${t[0]}">${t[1]}<span class="n" style="font:600 11px var(--font-ui);color:var(--ui-faint)">${t[2]}</span></button>`).join('')}</div>
 ${rows.length?`<section class="card" style="overflow:hidden"><div style="overflow-x:auto"><div style="min-width:980px"><div class="wrow h"><span>${L('Workflow','سير العمل')}</span><span>${L('Version','الإصدار')}</span><span>${L('Used by','يستخدمه')}</span><span>${L('Items running','عناصر جارية')}</span><span>${L('Last published','آخر نشر')}</span><span></span></div>
 ${rows.map(w=>`<div class="wrow"><span><b data-open="${w.id}">${esc(L(w.en,w.ar))}</b></span><span>${vst(w)}</span><span style="display:flex;gap:4px;flex-wrap:wrap">${w.types.map(t=>`<span class="wtc">${t}</span>`).join('')||'<span style="color:var(--ui-faint)">—</span>'}</span><span class="runs">${w.runs.map((n,i)=>`<span>v${i+1}: <b>${n}</b></span>`).join('')||'<span style="background:none;box-shadow:none;color:var(--ui-faint)">—</span>'}</span><span style="font-size:12.5px;color:var(--ui-muted)">${w.date}<br>${esc(w.by)}</span><span style="display:flex;gap:4px;justify-content:flex-end">${w.ro||w.lib?`<button class="cb sm" data-act="copy">${L('Use in project','استخدام في المشروع')}</button>`:`<button class="cb sm" data-open="${w.id}">${L('Open','فتح')}</button>`}<span class="rel"><button class="cb sm ter ic" data-menu="row-${w.id}"><i class="ti ti-dots"></i></button>${V.menu==='row-'+w.id?`<div class="pop end" data-stop><button class="mi" data-act="copy"><i class="ti ti-copy"></i>${L('Duplicate','تكرار')}</button><button class="mi" data-act="tolib"><i class="ti ti-building"></i>${L('Copy to company library','نسخ لمكتبة الشركة')}</button><div class="sep"></div><button class="mi" data-act="arch"><i class="ti ti-archive"></i>${L('Archive','أرشفة')}</button></div>`:''}</span></span></div>`).join('')}</div></div></section>`:`<section class="card"><div class="empty" style="padding:56px 20px;text-align:center"><div style="width:56px;height:56px;border-radius:16px;background:var(--tone-tomato-tint);color:var(--btn-pri);margin:0 auto 12px;display:flex;align-items:center;justify-content:center;font-size:26px"><i class="ti ti-refresh"></i></div><b style="display:block;font-size:17px;color:var(--ui-text)">${L('No custom workflows yet','لا يوجد سير عمل مخصص بعد')}</b><p style="color:var(--ui-muted);font-size:13.5px;max-width:420px;margin:6px auto 14px">${L('Your Work Item Types use Rabaed Defaults. Copy one to adjust steps, buttons and who holds each step.','تستخدم أنواع العناصر إعدادات ربائد. انسخ واحدًا لتعديل الخطوات والأزرار.')}</p><div style="display:flex;gap:8px;justify-content:center"><button class="cb pri" data-tab="rabaed"><i class="ti ti-copy"></i>${L('Copy a Rabaed Default','نسخ إعداد من ربائد')}</button><button class="cb" data-act="newblank">${L('Start blank','البدء من الصفر')}</button></div></div></section>`}
 <p style="font-size:12px;color:var(--ui-muted);display:flex;gap:6px;align-items:center"><i class="ti ti-info-circle"></i>${L('Using a workflow always makes a copy — it never stays linked to the library.','استخدام سير عمل ينشئ نسخة دائمًا — ولا يبقى مرتبطًا بالمكتبة.')}</p>`}
function types(){const T=[['MAR','Material Approval Request','طلب اعتماد مواد'],['DSR','Daily Site Report','تقرير الموقع اليومي'],['CMT','Comment','تعليق'],['SAR','Shop Drawing','مخطط تنفيذي'],['DAR','Document','مستند'],['IR','Inspection Request','طلب فحص'],['SNG','Snag','ملاحظة']];const opts=[...LIB.project.map(w=>[w.id,L(w.en,w.ar)]),['rabaed',L('Rabaed Default','الإعداد الافتراضي')]];
 return `<div class="st-hd"><div><h1>${L('Work Item Types','أنواع العناصر')}</h1><p>${L('Choose which workflow each type follows.','اختر سير العمل لكل نوع.')}</p></div></div><section class="card" style="overflow:hidden">${T.map(t=>`<div class="wrow" style="grid-template-columns:70px minmax(0,1fr) 320px"><span class="wtc">${t[0]}</span><b style="cursor:default">${L(t[1],t[2])}</b><select data-wit="${t[0]}" style="height:34px;border:0;border-radius:6px;padding:0 9px;background:var(--fld-bg);box-shadow:inset 0 0 0 1px var(--fld-bd);font:inherit;font-size:13px;color:var(--fld-txt)">${opts.map(o=>`<option value="${o[0]}"${V.types[t[0]]===o[0]?' selected':''}>${esc(o[1])}</option>`).join('')}</select></div>`).join('')}</section>`}
function detail(){const w=LIB.project.find(x=>x.id===V.wid)||LIB.project[0];const v=w.wf?{S:w.wf.S,T:w.wf.T,run:w.runs[0]}:vsel();
 const tabs=[['diagram',L('Diagram','المخطط')],['versions',L('Versions & history','الإصدارات والسجل')],['used',L('Used by','يستخدمه')],['activity',L('Activity','النشاط')]];let body='';
 if(V.dtab==='diagram')body=`<div class="wcv" style="height:520px"><div class="wstage" id="wst"><div id="wwrap">${renderDiagram({L,S:v.S,T:v.T,rtl:S.lang==='ar'})}</div></div>${ctl()}</div>`;
 if(V.dtab==='versions'&&w.wf)body=`<div class="tl"><div class="tli"><span class="dt" style="background:var(--tone-green-solid)">v1</span><div class="tx"><div style="flex:1;min-width:220px"><b style="font-size:14px">v1 <span class="vs pub">${L('Published','منشور')}</span></b><div style="font-size:12.5px;color:var(--ui-muted);margin-top:3px">${w.date} · ${esc(w.by)}</div><div style="font-size:13px;margin-top:6px">${L('Initial version.','الإصدار الأولي.')}</div></div><span class="runs"><span>${w.runs[0]} ${L('running','جارٍ')}</span></span></div></div></div>`;
 else if(V.dtab==='versions')body=`<div class="tl">${VERS.slice().reverse().map(x=>`<div class="tli"><span class="dt" style="background:${x.st==='draft'?'var(--tone-amber-solid)':'var(--tone-green-solid)'}">v${x.v}</span><div class="tx"><div style="flex:1;min-width:220px"><b style="font-size:14px">v${x.v} ${x.st==='draft'?`<span class="vs draft">${L('Draft','مسودة')}</span>`:`<span class="vs pub">${L('Published','منشور')}</span>`}</b><div style="font-size:12.5px;color:var(--ui-muted);margin-top:3px">${x.st==='draft'?L('In progress · Sara Al Mansoori','قيد العمل · سارة المنصوري'):`${x.date} · ${esc(x.by)}`}</div>${x.note[0]?`<div style="font-size:13px;margin-top:6px">${esc(L(x.note[0],x.note[1]))}</div>`:''}</div><span class="runs"><span>${x.run} ${L('running','جارٍ')}</span></span>${x.v>1?`<button class="cb sm" data-cmp="${x.v}"><i class="ti ti-arrows-diff"></i>${L('Compare with','مقارنة مع')} v${x.v-1}</button>`:''}</div></div>`).join('')}</div>`;
 if(V.dtab==='used')body=`<section class="card" style="overflow:hidden">${w.types.map((t,ti)=>`<div class="wrow" style="grid-template-columns:70px 1fr auto"><span class="wtc">${t}</span><span class="runs">${w.wf?`<span>v1: <b>${ti===0?Math.round(w.runs[0]*(w.types.length>1?.7:1)):w.runs[0]-Math.round(w.runs[0]*.7)}</b></span>`:VERS.filter(x=>x.st==='pub').map(x=>`<span>v${x.v}: <b>${t==='MAR'?[1,9,20][x.v-1]:[1,5,11][x.v-1]}</b></span>`).join('')}</span><a class="cb sm" href="submittals-list.html"><i class="ti ti-list"></i>${L('Open list by version','فتح القائمة حسب الإصدار')}</a></div>`).join('')}</section>`;
 if(V.dtab==='activity')body=`<section class="card" style="padding:6px 0">${[['Sara Al Mansoori','edited Draft v4 — added “Consultant QA check”','عدّلت المسودة v4 — أضافت «تدقيق الجودة»','2d'],['Mohammed Al Shamsi','published v3','نشر v3','14 Aug'],['Sara Al Mansoori','attached to SAR','ربطت بـ SAR','02 Apr'],['Sara Al Mansoori','published v2','نشرت v2','02 Apr'],['Sara Al Mansoori','published v1','نشرت v1','11 Jan']].map(a=>`<div class="wrow" style="grid-template-columns:1fr auto;padding-block:11px"><span><b style="font-size:13px;cursor:default">${a[0]}</b> <span style="color:var(--ui-text-2)">${L(a[1],a[2])}</span></span><span class="num" style="color:var(--ui-muted);font-size:12px">${a[3]}</span></div>`).join('')}</section>`;
 return `<div class="st-hd"><div><button class="cb ter sm" data-page="list"><i class="ti ti-arrow-left"></i>${L('Workflows','سير العمل')}</button><h1 style="margin-top:6px">${esc(L(w.en,w.ar))}</h1><p style="display:flex;gap:6px;align-items:center;flex-wrap:wrap">${vst(w)}${w.types.map(t=>`<span class="wtc">${t}</span>`).join('')}</p></div><div class="act">${w.wf?`<span class="vs pub" style="height:34px;padding:0 12px">v1 · ${L('published','منشور')}</span>`:`<select data-ver style="height:34px;border:0;border-radius:6px;padding:0 9px;background:var(--fld-bg);box-shadow:inset 0 0 0 1px var(--fld-bd);font:inherit;font-size:13px">${VERS.map(x=>`<option value="${x.v}"${x.v===V.ver?' selected':''}>v${x.v} · ${x.st==='draft'?L('draft','مسودة'):L('published','منشور')}</option>`).join('')}</select>`}<button class="cb" data-act="copy"><i class="ti ti-copy"></i>${L('Duplicate','تكرار')}</button>${w.wf?'':`<button class="cb" data-page="builder"><i class="ti ti-pencil"></i>${L('Edit draft','تعديل المسودة')} v4</button>`}${w.wf?'':`<button class="cb pri" data-act="publish"><i class="ti ti-upload"></i>${L('Publish','نشر')}</button>`}</div></div>
 <div class="wtabs">${tabs.map(t=>`<button class="${V.dtab===t[0]?'on':''}" data-dtab="${t[0]}">${t[1]}</button>`).join('')}</div>${V.dtab==='diagram'&&!w.wf&&V.ver<3?`<div class="lockb" style="background:var(--tone-blue-tint);color:var(--tone-blue-fg)"><i class="ti ti-info-circle"></i>${L(`v${V.ver} is read-only. ${vsel().run} items still run on it.`,`v${V.ver} للقراءة فقط. ${vsel().run} عناصر لا تزال عليه.`)}</div>`:''}${body}`}
const ctl=()=>`<div class="wctl"><button data-z="out"><i class="ti ti-zoom-out"></i></button><button data-z="in"><i class="ti ti-zoom-in"></i></button><button data-z="fit"><i class="ti ti-maximize"></i></button></div>`;
/* ---- builder ---- */
function side(){const d=V.ed;if(!V.sel)return `<h6>${L('Nothing selected','لا يوجد تحديد')}</h6><p style="font-size:13px;color:var(--ui-muted);margin:0;line-height:1.5">${L('Click a step or an arrow to edit it. Drag steps to move them.','انقر على خطوة أو سهم لتعديله. اسحب الخطوات لنقلها.')}</p><h6>${L('This draft','هذه المسودة')}</h6><div style="font-size:13px">${Object.values(d.S).filter(s=>!s.end).length} ${L('steps','خطوات')} · ${Object.keys(d.T).length} ${L('transitions','انتقالات')}</div>`;
 const inp=(k,v,ph)=>`<input data-f="${k}" value="${esc(v||'')}" placeholder="${ph||''}">`;
 if(d.S[V.sel]){const s=d.S[V.sel];if(s.end)return `<h6>${L('End','نهاية')}</h6><b>${L(END[s.end][0],END[s.end][1])}</b><button class="cb sm" data-act="del" style="color:var(--tone-red-fg)"><i class="ti ti-trash"></i>${L('Delete','حذف')}</button>`;
  const pool=s.co==='ctr'?'TMC Constructions → Nasser, Ahmed':s.co==='cns'?'Design Consultants LLC → pool: Ahmed, Sara':'Al Futtaim PMC → Hassan';
  return `<h6>${L('Step','خطوة')}</h6><label class="f">${L('Name (EN)','الاسم (EN)')}${inp('en',s.en)}</label><label class="f">${L('Name (AR)','الاسم (AR)')}<input data-f="ar" dir="rtl" value="${esc(s.ar)}"></label><label class="f">${L('Stage','المرحلة')}<select data-f="stage">${['drafts','internal','pending'].map(k=>`<option value="${k}"${s.stage===k?' selected':''}>${L(STG[k][0],STG[k][1])}</option>`).join('')}</select></label>
  <h6>${L('Who holds it','من يتولاها')}</h6><div class="g2"><select data-f="co">${Object.keys(CO).map(k=>`<option value="${k}"${s.co===k?' selected':''}>${L(CO[k][2],CO[k][3])}</option>`).join('')}</select><select data-f="perm">${['Create','Review','Approve'].map(p=>`<option${s.perm===p?' selected':''}>${p}</option>`).join('')}</select></div><div class="live"><i class="ti ti-users"></i> ${L('In this project:','في هذا المشروع:')} ${pool}</div><label class="f">${L('Default person (optional)','الشخص الافتراضي (اختياري)')}<select><option>${L('None — anyone in the pool','لا أحد — أي شخص في المجموعة')}</option></select></label>
  <h6>${L('Outcome','النتيجة')}</h6><select data-f="out">${[['none',L('None','بدون')],['recommend',L('Recommend a code (for the manager)','يوصي برمز')],['final',L('Issue the final code','يصدر الرمز النهائي')],['insp',L('Inspection result','نتيجة الفحص')]].map(o=>`<option value="${o[0]}"${s.out===o[0]?' selected':''}>${o[1]}</option>`).join('')}</select>
  <h6>${L('Editable form sections','أقسام النموذج القابلة للتعديل')}</h6>${['General','Items & quantities','Attachments','Review comments'].map((x,i)=>`<label class="chk3"><span class="ck${(s.co==='ctr'?i<3:i===3||i===2)?' on':''}">${(s.co==='ctr'?i<3:i===3||i===2)?'<i class="ti ti-check"></i>':''}</span>${x}</label>`).join('')}
  <button class="cb sm" data-act="del" style="color:var(--tone-red-fg);align-self:flex-start"><i class="ti ti-trash"></i>${L('Delete step','حذف الخطوة')}</button>`}
 const t=d.T[V.sel];if(!t)return '';
 return `<h6>${L('Transition (button)','انتقال (زر)')} · ${esc(L(d.S[t.f].en||'',d.S[t.f].ar||''))} → ${d.S[t.to].end?L(END[d.S[t.to].end][0],END[d.S[t.to].end][1]):esc(L(d.S[t.to].en,d.S[t.to].ar))}</h6><label class="f">${L('Button label (EN)','نص الزر (EN)')}${inp('en',t.en)}</label><label class="f">${L('Button label (AR)','نص الزر (AR)')}<input data-f="ar" dir="rtl" value="${esc(t.ar)}"></label>
 <label class="f">${L('Type','النوع')}<span class="segv">${['send','submit','return','close','cancel'].map(k=>`<button class="${t.type===k?'on':''}" data-tt="${k}" style="padding:0 8px;font-size:12px">${({send:L('Send','إرسال'),submit:L('Submit','تقديم'),return:L('Return','إرجاع'),close:L('Close','إغلاق'),cancel:L('Cancel','إلغاء')})[k]}</button>`).join('')}</span></label>
 <label class="f">${L('Outcome · Review Code','النتيجة · رمز المراجعة')}<select data-f="code"><option value="">—</option>${['A','B','C','D'].map(c=>`<option${t.code===c?' selected':''}>${c}</option>`).join('')}</select></label>
 <label class="chk3" data-act="sign"><span class="swc${t.sign?' on':''}"></span>${L('Requires signature + confirmation','يتطلب توقيعًا وتأكيدًا')}</label>
 <h6>${L('Condition','الشرط')}</h6>${(t.cond||[]).map((c,i)=>`<div class="crow"><select data-cf="${i}:f">${[...FIELDS,...(FIELDS.includes(c.f)?[]:[c.f])].map(f=>`<option${c.f===f?' selected':''}>${f}</option>`).join('')}</select><select data-cf="${i}:op">${['>','<','=','≠'].map(o=>`<option${c.op===o?' selected':''}>${o}</option>`).join('')}</select><input data-cf="${i}:v" value="${esc(c.v)}"><button class="cb ter sm ic" data-crm="${i}"><i class="ti ti-x"></i></button></div>${i<t.cond.length-1?`<small style="font-weight:700;color:var(--ui-muted)">AND</small>`:''}`).join('')}<button class="cb sm" data-act="cadd" style="align-self:flex-start"><i class="ti ti-plus"></i>${L('Add rule','إضافة قاعدة')}</button>
 <h6>${L('Action form (pop-up)','نموذج الإجراء (نافذة)')}</h6>${[['comment',L('Comments','ملاحظات')],['files',L('Attach files','إرفاق ملفات')],['code',L('Pick review code','اختيار الرمز')]].map(f=>{const on=(t.form||['comment']).includes(f[0])||(f[0]==='code'&&t.code);return `<label class="chk3" data-ff="${f[0]}"><span class="ck${on?' on':''}">${on?'<i class="ti ti-check"></i>':''}</span>${f[1]}</label>`}).join('')}
 <div class="fprev"><b>${esc(L(t.en,t.ar))}</b>${t.code?`<div style="display:flex;gap:4px">${['A','B','C','D'].map(c=>`<span class="cdb" style="background:var(--tone-${c==='C'?'orange':c==='D'?'red':'green'}-${c===t.code?'solid':'tint'});color:${c===t.code?'#fff':`var(--tone-${c==='C'?'orange':c==='D'?'red':'green'}-fg)`}">Code ${c}</span>`).join('')}</div>`:''}${(t.form||['comment']).includes('comment')?`<span class="fl">${L('Comments…','ملاحظات…')}</span>`:''}${(t.form||[]).includes('files')?`<span class="fl"><i class="ti ti-paperclip"></i>&nbsp;${L('Attach files','إرفاق')}</span>`:''}${t.sign?`<span class="sg"><i class="ti ti-signature"></i>${L('Your signature will be applied','سيتم تطبيق توقيعك')}</span>`:''}<span class="cb pri sm" style="align-self:flex-end">${L('Confirm','تأكيد')}</span></div>
 <h6>${L('Notifications','الإشعارات')}</h6><div style="display:flex;flex-wrap:wrap;gap:6px">${[L('Next holder','المتولي التالي'),L('Raiser','المُنشئ'),L('Company admins','مسؤولو الشركة'),L('Distribution list','قائمة التوزيع')].map((x,i)=>`<span class="m-chip" style="height:28px;font-size:12px;${i<2?'background:var(--ui-text);color:var(--ui-surface);box-shadow:none':''}">${x}</span>`).join('')}</div><div style="font-size:12px;color:var(--ui-muted)">${L('Channels: in-app · email','القنوات: داخل التطبيق · البريد')}</div>
 <button class="cb sm" data-act="del" style="color:var(--tone-red-fg);align-self:flex-start"><i class="ti ti-trash"></i>${L('Delete transition','حذف الانتقال')}</button>`}
function builder(){const d=V.ed,errs=validate(d);const ne=errs.filter(e=>e.lv==='err').length;const sim=V.sim;
 let scls={},ecls={};if(sim){Object.keys(d.S).forEach(k=>scls[k]=sim.path.includes(k)?'done':'fade');scls[sim.at]='cur';Object.entries(d.T).forEach(([k,t])=>{ecls[k]=sim.edges.includes(k)?'done':t.f===sim.at&&ok(t)?'next':'fade'})}
 return `<div class="bld"><div class="btop"><button class="cb ter sm" data-page="detail"><i class="ti ti-arrow-left"></i></button><h2>${L('Material Submittal – 2-tier review','اعتماد المواد – مراجعة على مستويين')}</h2><span class="vs draft">${L('Draft','مسودة')} v4${V.dirty?' · '+L('unsaved changes','تغييرات غير محفوظة'):''}</span><span class="sp"></span><button class="cb ic" data-act="undo"${V.undo.length?'':' disabled'}><i class="ti ti-arrow-back-up"></i></button><button class="cb ic" data-act="redo"${V.redo.length?'':' disabled'}><i class="ti ti-arrow-forward-up"></i></button><button class="cb" data-act="layout"><i class="ti ti-layout-grid"></i>${L('Auto-layout','ترتيب تلقائي')}</button><button class="cb${sim?' on':''}" data-act="sim"><i class="ti ti-player-play"></i>${L('Test run','تشغيل تجريبي')}</button><button class="cb" data-act="val"><i class="ti ti-${ne?'alert-triangle':'circle-check'}"></i>${L('Validate','تحقق')}</button><button class="cb pri" data-act="publish"><i class="ti ti-upload"></i>${L('Publish','نشر')}</button></div>
 <div class="bgrid"><aside class="card bpal"><h6>${L('Add','إضافة')}</h6><button class="pal" data-add="step"><i class="ti ti-square-plus"></i>${L('Step','خطوة')}</button>${Object.entries(END).map(([k,e])=>`<button class="pal" data-add="end:${k}"><i class="e" style="background:var(--tone-${e[2]}-tint);box-shadow:inset 0 0 0 2px var(--tone-${e[2]}-solid)"></i>${L('End · ','نهاية · ')}${L(e[0],e[1])}</button>`).join('')}<h6>${L('Templates','قوالب')}</h6><button class="pal" data-add="tpl1"><i class="ti ti-template"></i>${L('2-tier internal review','مراجعة داخلية على مستويين')}</button><button class="pal" data-add="tpl2"><i class="ti ti-template"></i>${L('Consultant engineer → manager','مهندس الاستشاري ← المدير')}</button></aside>
 <section class="wcv"><div class="wstage" id="wst"><div id="wwrap">${renderDiagram({L,S:d.S,T:d.T,sel:V.sel,rtl:false,scls,ecls})}</div></div>${ctl()}<div class="wmini">${Object.values(d.S).map(s=>`<i style="left:${s.x/W*170}px;top:${s.y/H*85}px;width:${(s.end?170:200)/W*170}px;height:${(s.end?46:78)/H*85}px"></i>`).join('')}<em id="wmv"></em></div>
 ${sim?`<div class="simbar"><i class="ti ti-player-play"></i><b>${L('Test run','تشغيل تجريبي')}</b><span>${L('Sample: MAR · cost impact','عينة: MAR · أثر التكلفة')} <select data-cost style="height:26px;border-radius:5px;border:0;font:inherit;font-size:12px"><option value="620000"${V.cost>500000?' selected':''}>620,000 SAR</option><option value="120000"${V.cost<=500000?' selected':''}>120,000 SAR</option></select></span><span style="opacity:.7">·</span>${d.S[sim.at].end?`<b>${L('Finished: ','انتهى: ')}${L(END[d.S[sim.at].end][0],END[d.S[sim.at].end][1])}</b>`:`${L('At','عند')} <b>${esc(L(d.S[sim.at].en,d.S[sim.at].ar))}</b> — ${Object.entries(d.T).filter(([k,t])=>t.f===sim.at&&ok(t)).map(([k,t])=>`<button class="cb sm pri" data-go="${k}">${esc(L(t.en,t.ar))}</button>`).join('')}`}<span style="flex:1"></span><button class="cb sm ter" data-act="simreset"><i class="ti ti-refresh"></i>${L('Restart','إعادة')}</button><button class="cb sm ter" data-act="sim"><i class="ti ti-x"></i></button></div>`:''}</section>
 <aside class="card bside">${side()}</aside>
 <section class="card bval"><div class="h"><i class="ti ti-${ne?'alert-triangle':'circle-check'}" style="color:var(--tone-${ne?'red':'green'}-solid)"></i>${ne?L(`${ne} errors`,`${ne} أخطاء`):L('No errors','لا أخطاء')}${errs.length-ne?` · ${errs.length-ne} ${L('warning','تحذير')}`:''}</div>${errs.map(e=>`<button class="vi" data-vgo="${e.id}"><i class="ti ti-${e.lv==='err'?'circle-x':'alert-triangle'}" style="color:var(--tone-${e.lv==='err'?'red':'amber'}-solid)"></i>${esc(L(e.msg[0],e.msg[1]))}<i class="ti ti-focus-2" style="margin-inline-start:auto;color:var(--ui-faint)"></i></button>`).join('')}</section></div></div>`}
const ok=t=>!t.cond||t.cond.every(c=>c.f!=='cost_impact'&&c.f!=='cost_impact_sar'||(c.op==='>'?V.cost>+c.v:V.cost<+c.v));
/* ---- modals ---- */
function diff(a,b){const out={add:[],rem:[],chg:[]};const ks=(x,y)=>[...new Set([...Object.keys(x),...Object.keys(y)])];
 ks(a.S,b.S).forEach(k=>{if(!a.S[k])out.add.push(['s',k]);else if(!b.S[k])out.rem.push(['s',k]);else if(a.S[k].en!==b.S[k].en||a.S[k].co!==b.S[k].co||a.S[k].out!==b.S[k].out)out.chg.push(['s',k])});
 ks(a.T,b.T).forEach(k=>{if(!a.T[k])out.add.push(['t',k]);else if(!b.T[k])out.rem.push(['t',k]);else if(JSON.stringify(a.T[k])!==JSON.stringify(b.T[k]))out.chg.push(['t',k])});return out}
const nm=(d,x)=>x[0]==='s'?(d.S[x[1]].end?L(END[d.S[x[1]].end][0],END[d.S[x[1]].end][1]):L(d.S[x[1]].en,d.S[x[1]].ar)):L(d.T[x[1]].en,d.T[x[1]].ar)+' ('+L('button','زر')+')';
function chList(a,b,df){return `<div class="chg">${df.add.map(x=>`<div><i class="ti ti-plus" style="color:var(--tone-green-solid)"></i>${L('Added','أُضيف')} ${esc(nm(b,x))}</div>`).join('')}${df.rem.map(x=>`<div><i class="ti ti-minus" style="color:var(--tone-red-solid)"></i>${L('Removed','أُزيل')} ${esc(nm(a,x))}</div>`).join('')}${df.chg.map(x=>`<div><i class="ti ti-pencil" style="color:var(--tone-orange-solid)"></i>${L('Changed','تغيّر')} ${esc(nm(b,x))}${x[0]==='t'&&a.T[x[1]].sign!==b.T[x[1]].sign?` — ${L('signature','التوقيع')} ${b.T[x[1]].sign?L('on','مفعّل'):L('off','معطّل')}`:''}${x[0]==='t'&&JSON.stringify(a.T[x[1]].cond)!==JSON.stringify(b.T[x[1]].cond)?` — ${L('condition','الشرط')}`:''}</div>`).join('')||`<div style="color:var(--ui-muted)">${L('No changes','لا تغييرات')}</div>`}</div>`}
function modal(){if(!V.modal)return '';const x=`<button class="cb ter sm ic x" data-close="1"><i class="ti ti-x"></i></button>`;
 if(V.modal==='publish'){const d=V.ed||draft();const a=VERS.find(v=>v.v===3);const df=diff(a,d);const errs=validate(d).filter(e=>e.lv==='err');
  return `<div class="scrim" data-close="1"><div class="wmdl" data-stop><div class="mh"><i class="ti ti-upload" style="color:var(--btn-pri)"></i><b>${L('Publish v4','نشر v4')}</b>${x}</div><div class="mb"><h6 style="margin:0;font-size:11px;color:var(--ui-faint);text-transform:uppercase;letter-spacing:.06em">${L('Changes since v3','التغييرات منذ v3')}</h6>${chList(a,d,df)}
  ${errs.length?`<div class="okb" style="background:var(--tone-red-tint);color:var(--tone-red-fg)"><i class="ti ti-circle-x"></i>${L(`${errs.length} validation errors — fix them before publishing.`,`${errs.length} أخطاء تحقق — أصلحها قبل النشر.`)}<button class="cb sm" data-act="tobuilder" style="margin-inline-start:auto">${L('Open builder','فتح المحرر')}</button></div>`:`<div class="okb" style="background:var(--tone-green-tint);color:var(--tone-green-fg)"><i class="ti ti-circle-check"></i>${L('Validation passed','اجتاز التحقق')}</div>`}
  <label style="display:flex;flex-direction:column;gap:6px;font-size:12.5px;font-weight:600">${L('Change note','ملاحظة التغيير')} *<textarea id="pnote" rows="3" style="border:0;border-radius:6px;padding:8px 10px;background:var(--fld-bg);box-shadow:inset 0 0 0 1px ${V.noteErr?'var(--tone-red-solid)':'var(--fld-bd)'};font:inherit;font-size:13.5px;color:var(--fld-txt)" placeholder="${L('What changed and why?','ما الذي تغيّر ولماذا؟')}">${esc(V.pubNote)}</textarea></label>
  <div class="okb" style="background:var(--tone-blue-tint);color:var(--tone-blue-fg);font-weight:500"><i class="ti ti-info-circle"></i>${L('31 items on v3 and 16 on older versions keep their version. New items will use v4.','31 عنصرًا على v3 و16 على إصدارات أقدم تحتفظ بإصداراتها. العناصر الجديدة ستستخدم v4.')}</div></div>
  <div class="mf"><button class="cb" data-close="1">${L('Cancel','إلغاء')}</button><button class="cb pri" data-act="dopub"${errs.length?' disabled':''}><i class="ti ti-upload"></i>${L('Publish v4','نشر v4')}</button></div></div></div>`}
 if(V.modal.startsWith('cmp')){const bv=+V.modal.slice(3),a=VERS.find(v=>v.v===bv-1),b=VERS.find(v=>v.v===bv);const df=diff(a,b);const sa={},sb={},ea={},eb={};df.add.forEach(x=>(x[0]==='s'?sb:eb)[x[1]]='add');df.rem.forEach(x=>(x[0]==='s'?sa:ea)[x[1]]='rem');df.chg.forEach(x=>{(x[0]==='s'?sa:ea)[x[1]]='chg';(x[0]==='s'?sb:eb)[x[1]]='chg'});
  return `<div class="scrim" data-close="1"><div class="wmdl wide" data-stop><div class="mh"><i class="ti ti-arrows-diff"></i><b>${L('Compare','مقارنة')} v${a.v} → v${b.v}</b><span style="display:flex;gap:10px;font-size:12px;margin-inline-start:12px"><span style="color:var(--tone-green-fg)">■ ${L('added','مضاف')}</span><span style="color:var(--tone-red-fg)">■ ${L('removed','محذوف')}</span><span style="color:var(--tone-orange-fg)">■ ${L('changed','متغيّر')}</span></span>${x}</div><div class="mb"><div class="cmpg"><div><b style="font-size:13px">v${a.v}</b><div class="wcv"><div class="wstage cmps">${renderDiagram({L,S:a.S,T:a.T,scls:sa,ecls:ea})}</div></div></div><div><b style="font-size:13px">v${b.v}</b><div class="wcv"><div class="wstage cmps">${renderDiagram({L,S:b.S,T:b.T,scls:sb,ecls:eb})}</div></div></div></div>${chList(a,b,df)}</div></div></div>`}
 return ''}
function view(){if(V.page==='builder')return builder()+modal()+toast();return `<div class="st-wrap">${nav()}<div class="st-main">${V.page==='types'?types():V.page==='detail'?detail():list()}</div></div>${modal()}${toast()}`}
const toast=()=>V.toast?`<div class="toast"><i class="ti ti-circle-check"></i>${V.toast}</div>`:'';
/* ---- transform ---- */
function applyT(){const w=document.querySelector('#wst .wworld');if(!w)return;w.style.transform=`translate(${V.tx}px,${V.ty}px) scale(${V.k})`;const m=document.getElementById('wmv'),s=document.getElementById('wst');if(m&&s){const r=s.getBoundingClientRect();m.style.left=(-V.tx/V.k)/W*170+'px';m.style.top=(-V.ty/V.k)/H*85+'px';m.style.width=r.width/V.k/W*170+'px';m.style.height=r.height/V.k/H*85+'px'}
 document.querySelectorAll('.cmps .wworld').forEach(x=>{const r=x.parentElement.getBoundingClientRect();const k=Math.min(r.width/W,r.height/H);x.style.transform=`translate(${(r.width-W*k)/2}px,6px) scale(${k})`})}
function fit(){const s=document.getElementById('wst');if(!s)return;const r=s.getBoundingClientRect();V.k=Math.min(r.width/W,r.height/(H+40))*.97;V.tx=(r.width-W*V.k)/2;V.ty=10;applyT()}
function after(){if(V.fitNext){V.fitNext=false;fit()}else applyT()}
/* ---- bind ---- */
function bind(root,R){let tt;const flash=m=>{V.toast=m;R();clearTimeout(tt);tt=setTimeout(()=>{V.toast=null;R()},2400)};
 const snap=()=>{V.undo.push(JSON.stringify(V.ed));V.redo=[];V.dirty=true};
 const cur=()=>V.ed.S[V.sel]||V.ed.T[V.sel];
 root.addEventListener('click',e=>{const b=e.target.closest('[data-menu],[data-tab],[data-open],[data-page],[data-dtab],[data-cmp],[data-act],[data-snav],[data-z],[data-add],[data-s],[data-t],[data-tt],[data-crm],[data-ff],[data-vgo],[data-go],[data-close]');
  if(!b){if(V.menu){V.menu=null;R()}return}if(b.closest('.hd,.tabs,.sb'))return;const d=b.dataset;
  if(d.close!==undefined){if(e.target.closest('[data-stop]')&&!b.closest('button'))return;V.modal=null;return R()}
  if(d.menu){e.stopPropagation();V.menu=V.menu===d.menu?null:d.menu;return R()}
  if(d.tab){V.tab=d.tab;V.menu=null;V.page='list';return R()}
  if(d.snav){if(d.snav==='numbering'){location.href='settings-numbering.html';return}V.page=d.snav==='types'?'types':d.snav==='workflows'?'list':V.page;if(!['types','workflows'].includes(d.snav))return flash(L('Not designed yet','لم يُصمَّم بعد'));return R()}
  if(d.open){V.wid=d.open;V.page='detail';V.dtab='diagram';V.ver=3;V.fitNext=true;return R()}
  if(d.page){V.page=d.page;V.fitNext=true;V.sim=null;if(d.page==='builder'&&!V.ed){V.ed=clone(draft());V.sel=null}return R()}
  if(d.dtab){V.dtab=d.dtab;V.fitNext=true;return R()}
  if(d.cmp){V.modal='cmp'+d.cmp;R();return requestAnimationFrame(applyT)}
  if(d.z){if(d.z==='fit')return fit();const s=document.getElementById('wst').getBoundingClientRect(),f=d.z==='in'?1.2:1/1.2;V.tx=s.width/2-(s.width/2-V.tx)*f;V.ty=s.height/2-(s.height/2-V.ty)*f;V.k*=f;return applyT()}
  if(d.add){snap();const id='n'+Date.now();if(d.add==='step')V.ed.S[id]={en:'New step',ar:'خطوة جديدة',stage:'internal',co:'ctr',perm:'Review',out:'none',x:300,y:470,ic:'ti-user'};else if(d.add.startsWith('end:'))V.ed.S[id]={end:d.add.slice(4),x:1110,y:600};else{const a=id+'a',c=id+'c';Object.assign(V.ed.S,{[a]:{en:d.add==='tpl1'?'Engineer review':'Consultant engineer',ar:'مراجعة المهندس',stage:d.add==='tpl1'?'internal':'pending',co:d.add==='tpl1'?'ctr':'cns',perm:'Review',out:'none',x:d.add==='tpl1'?280:530,y:520,ic:'ti-user'},[c]:{en:d.add==='tpl1'?'PM review':'Consultant manager',ar:'مراجعة المدير',stage:d.add==='tpl1'?'internal':'pending',co:d.add==='tpl1'?'ctr':'cns',perm:'Approve',out:d.add==='tpl1'?'none':'final',x:d.add==='tpl1'?280:810,y:600,ic:'ti-user-check'}});V.ed.T[id+'t']={f:a,to:c,en:'Send',ar:'إرسال',type:'send'};V.ed.T[id+'r']={f:c,to:a,en:'Return',ar:'إرجاع',type:'return'}}V.sel=d.add==='step'||d.add.startsWith('end')?id:null;return R()}
  if(d.go){const t=V.ed.T[d.go];V.sim.at=t.to;V.sim.path.push(t.to);V.sim.edges.push(d.go);return R()}
  if(d.vgo){V.sel=d.vgo;R();const s=V.ed.S[d.vgo]||V.ed.S[V.ed.T[d.vgo].f];const r=document.getElementById('wst').getBoundingClientRect();V.k=Math.max(V.k,.9);V.tx=r.width/2-(s.x+100)*V.k;V.ty=r.height/2-(s.y+40)*V.k;return applyT()}
  if(d.tt){snap();cur().type=d.tt;if(d.tt==='submit')cur().sign=cur().sign;return R()}
  if(d.crm!==undefined){snap();cur().cond.splice(+d.crm,1);if(!cur().cond.length)delete cur().cond;return R()}
  if(d.ff){snap();const t=cur();t.form=t.form||['comment'];t.form.includes(d.ff)?t.form=t.form.filter(x=>x!==d.ff):t.form.push(d.ff);return R()}
  const a=d.act;
  if(a){V.menu=null;
   if(a==='toggleempty'){V.empty=!V.empty;return R()}
   if(a==='newblank'){V.page='builder';V.ed={S:{s1:{en:'Contractor Engineer',ar:'مهندس المقاول',stage:'drafts',co:'ctr',perm:'Create',out:'none',x:30,y:250,ic:'ti-user'}},T:{}};V.sel='s1';V.fitNext=true;return R()}
   if(a==='copy'||a==='tolib')return flash(a==='copy'?L('Copied into this project as a new draft','تم النسخ إلى المشروع كمسودة جديدة'):L('Copied to company library','تم النسخ إلى مكتبة الشركة'));
   if(a==='arch')return flash(L('Archived','تمت الأرشفة'));
   if(a==='publish'){V.modal='publish';V.pubNote='';V.noteErr=false;if(!V.ed)V.ed=clone(draft());return R()}
   if(a==='tobuilder'){V.modal=null;V.page='builder';V.fitNext=true;return R()}
   if(a==='dopub'){const n=document.getElementById('pnote');V.pubNote=n?n.value:'';if(!V.pubNote.trim()){V.noteErr=true;return R()}const d4=draft();Object.assign(d4,{st:'pub',by:'Sara Al Mansoori',date:'26 Sep 2026',note:[V.pubNote,V.pubNote],S:clone(V.ed.S),T:clone(V.ed.T)});LIB.project[0].runs.push(0);LIB.project[0].draft=0;V.modal=null;V.page='detail';V.dtab='versions';V.dirty=false;V.ed=null;return flash(L('v4 published — new items will use it','تم نشر v4 — العناصر الجديدة ستستخدمه'))}
   if(a==='undo'&&V.undo.length){V.redo.push(JSON.stringify(V.ed));V.ed=JSON.parse(V.undo.pop());return R()}
   if(a==='redo'&&V.redo.length){V.undo.push(JSON.stringify(V.ed));V.ed=JSON.parse(V.redo.pop());return R()}
   if(a==='layout'){snap();const base=WF.S0;Object.keys(V.ed.S).forEach((k,i)=>{if(base[k]){V.ed.S[k].x=base[k].x;V.ed.S[k].y=base[k].y}else{V.ed.S[k].x=Math.round((V.ed.S[k].x)/20)*20;V.ed.S[k].y=Math.round(V.ed.S[k].y/20)*20}});V.fitNext=true;return R()}
   if(a==='sim'){V.sim=V.sim?null:{at:'s1',path:['s1'],edges:[]};V.sel=null;return R()}
   if(a==='simreset'){V.sim={at:'s1',path:['s1'],edges:[]};return R()}
   if(a==='val'){const n=validate(V.ed).filter(x=>x.lv==='err').length;return flash(n?L(`${n} errors to fix`,`${n} أخطاء للإصلاح`):L('Validation passed','اجتاز التحقق'))}
   if(a==='sign'){snap();cur().sign=cur().sign?0:1;return R()}
   if(a==='cadd'){snap();const t=cur();t.cond=t.cond||[];t.cond.push({f:'cost_impact',op:'>',v:'0'});return R()}
   if(a==='del'){snap();if(V.ed.S[V.sel]){delete V.ed.S[V.sel];Object.keys(V.ed.T).forEach(k=>{const t=V.ed.T[k];if(t.f===V.sel||t.to===V.sel)delete V.ed.T[k]})}else delete V.ed.T[V.sel];V.sel=null;return R()}
  }
  if(V.page==='builder'&&!V.sim&&(d.s||d.t)){V.sel=d.s||d.t;return R()}
 });
 root.addEventListener('change',e=>{const i=e.target;if(i.dataset.ver){V.ver=+i.value;V.fitNext=true;return R()}if(i.dataset.cost){V.cost=+i.value;return R()}if(i.dataset.wit){V.types[i.dataset.wit]=i.value;return flash(L('Saved — only new items use the new workflow. Running items keep theirs.','تم الحفظ — العناصر الجديدة فقط تستخدم سير العمل الجديد.'))}
  if(i.dataset.f&&i.tagName==='SELECT'){snap();cur()[i.dataset.f]=i.value;return R()}if(i.dataset.cf){snap();const [n,k]=i.dataset.cf.split(':');cur().cond[+n][k]=i.value;return R()}});
 root.addEventListener('input',e=>{const i=e.target;if(i.dataset.f&&i.tagName==='INPUT'){if(!V.dirty)snap();cur()[i.dataset.f]=i.value;V.dirty=true;const lb=root.querySelector(`.wl[data-t="${V.sel}"]`),nd=root.querySelector(`.wn[data-s="${V.sel}"] b`);const txt=L(cur().en,cur().ar);if(lb)lb.lastChild.textContent=txt;if(nd)nd.textContent=txt}if(i.dataset.cf&&i.tagName==='INPUT'){cur().cond[+i.dataset.cf.split(':')[0]].v=i.value}});
 let P=null;
 root.addEventListener('pointerdown',e=>{const st=e.target.closest('#wst');if(!st||e.button!==0||e.target.closest('.wl'))return;const n=e.target.closest('.wn[data-s]');P={x:e.clientX,y:e.clientY,tx:V.tx,ty:V.ty,n:V.page==='builder'&&!V.sim&&n?n.dataset.s:null,moved:false};if(P.n){const s=V.ed.S[P.n];P.sx=s.x;P.sy=s.y}});
 addEventListener('pointermove',e=>{if(!P)return;const dx=e.clientX-P.x,dy=e.clientY-P.y;if(!P.moved&&Math.hypot(dx,dy)>4){P.moved=true;if(P.n)snap()}if(!P.moved)return;if(P.n){const s=V.ed.S[P.n];s.x=Math.round((P.sx+dx/V.k)/20)*20;s.y=Math.round((P.sy+dy/V.k)/20)*20;const w=document.getElementById('wwrap');w.innerHTML=renderDiagram({L,S:V.ed.S,T:V.ed.T,sel:V.sel});applyT()}else{V.tx=P.tx+dx;V.ty=P.ty+dy;applyT()}});
 addEventListener('pointerup',()=>{if(P&&P.moved&&P.n)R();P=null});
 root.addEventListener('wheel',e=>{const st=e.target.closest('#wst');if(!st)return;e.preventDefault();const r=st.getBoundingClientRect(),cx=e.clientX-r.left,cy=e.clientY-r.top,f=e.deltaY<0?1.1:1/1.1;V.tx=cx-(cx-V.tx)*f;V.ty=cy-(cy-V.ty)*f;V.k*=f;applyT()},{passive:false});
 addEventListener('resize',()=>applyT());
 document.addEventListener('keydown',e=>{if(e.target.closest&&e.target.closest('input,textarea,select'))return;if(e.key==='Escape'){V.modal=null;V.sel=null;R()}if((e.metaKey||e.ctrlKey)&&e.key==='z'&&V.page==='builder'){e.preventDefault();root.querySelector('[data-act='+(e.shiftKey?'redo':'undo')+']')?.click()}});
}
window.WA={V,view,bind,after};
})();
