import { palette } from "./palette.ts";
import { fonts, radii, shadows, typeScale } from "./scales.ts";
import { coolLight, defaultTheme, themes } from "./themes.ts";

/**
 * Builds src/styles/tokens.css: the base palette (layer 1), one block of
 * semantic roles per theme (layer 2) and the Tailwind theme (layer 3), which
 * exposes semantic roles only, so no utility can reach the base palette.
 */
export function generateTokensCss(): string {
  const roles = Object.keys(coolLight);
  const lines = [
    "/* Generated by scripts/generate-tokens.ts from src/tokens. Do not edit by hand. */",
    "",
    "/* Layer 1: base palette. Read by themes only, never by components. */",
    ":root {",
    ...Object.entries(palette).map(([name, value]) => `  --palette-${name}: ${value};`),
    "}",
  ];

  for (const [name, theme] of Object.entries(themes)) {
    const selector = name === defaultTheme ? `:root,\n[data-theme="${name}"]` : `[data-theme="${name}"]`;
    lines.push(
      "",
      `/* Layer 2: semantic roles, theme "${name}". */`,
      `${selector} {`,
      ...Object.entries(theme).map(([role, colour]) => `  --${role}: var(--palette-${colour});`),
      "}",
    );
  }

  lines.push(
    "",
    "/* Layer 3: the Tailwind theme components use. Semantic roles only. */",
    "@theme inline {",
    "  --color-*: initial;",
    ...roles.map((role) => `  --color-${role}: var(--${role});`),
    "}",
    "",
    "/* Type, radii and shadows, always emitted as variables so pages can read them too. */",
    "@theme static {",
    "  --font-*: initial;",
    ...Object.entries(fonts).map(([name, stack]) => `  --font-${name}: ${stack};`),
    `  --default-font-family: ${fonts.ui};`,
    `  --default-mono-font-family: ${fonts.mono};`,
    "",
    "  --text-*: initial;",
    ...Object.entries(typeScale).flatMap(([name, [size, lineHeight]]) => [
      `  --text-${name}: ${size};`,
      `  --text-${name}--line-height: ${lineHeight};`,
    ]),
    "",
    "  --radius-*: initial;",
    ...Object.entries(radii).map(([name, value]) => `  --radius-${name}: ${value};`),
    "",
    "  --shadow-*: initial;",
    ...Object.entries(shadows).map(([name, value]) => `  --shadow-${name}: ${value};`),
    "}",
    "",
  );

  return lines.join("\n");
}
