import { palette } from "./palette.ts";
import { fonts, radii, shadows, typeScale } from "./scales.ts";
import { defaultTheme, greyLight, themes, type Theme } from "./themes.ts";

/**
 * Builds src/styles/tokens.css: the base palette (layer 1), one block of
 * semantic roles per theme (layer 2) and the Tailwind theme (layer 3), which
 * exposes semantic roles only, so no utility can reach the base palette.
 */
export function generateTokensCss(): string {
  const roles = Object.keys(greyLight);
  const lines = [
    "/* Generated by scripts/generate-tokens.ts from src/tokens. Do not edit by hand. */",
    "",
    "/* Layer 1: base palette. Read by themes only, never by components. */",
    ":root {",
    ...Object.entries(palette).map(([name, value]) => `  --palette-${name}: ${value};`),
    "}",
  ];

  // Each Member's Theme and Mode is on <html> (`data-theme`, `data-mode`), set by the server, so the
  // first paint is already right. Mode "system" follows the device: Light, or Dark in the media query.
  const block = (name: string, theme: Theme, selectors: string[], indent = "") => [
    `${indent}${selectors.join(`,\n${indent}`)} {`,
    `${indent}  color-scheme: ${name.endsWith("dark") ? "dark" : "light"};`,
    ...Object.entries(theme).map(([role, colour]) => `${indent}  --${role}: var(--palette-${colour});`),
    `${indent}}`,
  ];
  for (const [name, theme] of Object.entries(themes)) {
    const [family, mode] = name.split("-") as [string, "light" | "dark"];
    const selectors = [
      ...(name === defaultTheme ? [":root"] : []),
      `[data-theme="${family}"][data-mode="${mode}"]`,
      ...(mode === "light" ? [`[data-theme="${family}"][data-mode="system"]`] : []),
    ];
    lines.push("", `/* Layer 2: semantic roles, theme "${name}". */`, ...block(name, theme, selectors));
    if (mode === "dark") {
      lines.push(
        "",
        `/* "${family}" following a device set to dark. */`,
        "@media (prefers-color-scheme: dark) {",
        ...block(name, theme, [`[data-theme="${family}"][data-mode="system"]`], "  "),
        "}",
      );
    }
  }

  lines.push(
    "",
    "/* Layer 3: the Tailwind theme components use. Semantic roles only. */",
    "@theme inline {",
    "  --color-*: initial;",
    ...roles.map((role) => `  --color-${role}: var(--${role});`),
    "}",
    "",
    "/* Type, radii and shadows, always emitted as variables so pages can read them too. */",
    "@theme static {",
    "  --font-*: initial;",
    ...Object.entries(fonts).map(([name, stack]) => `  --font-${name}: ${stack};`),
    `  --default-font-family: ${fonts.ui};`,
    `  --default-mono-font-family: ${fonts.mono};`,
    "",
    "  --text-*: initial;",
    ...Object.entries(typeScale).flatMap(([name, [size, lineHeight]]) => [
      `  --text-${name}: ${size};`,
      `  --text-${name}--line-height: ${lineHeight};`,
    ]),
    "",
    "  --radius-*: initial;",
    ...Object.entries(radii).map(([name, value]) => `  --radius-${name}: ${value};`),
    "",
    "  --shadow-*: initial;",
    ...Object.entries(shadows).map(([name, value]) => `  --shadow-${name}: ${value};`),
    "}",
    "",
  );

  return lines.join("\n");
}
