#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Sets up the AWS account for one Rabaed environment (dev by default):
#   bash packages/infra/scripts/setup-aws-account.sh [environment]
#
# Re-runnable: every stage either checks first or is safe to repeat, and the
# answers you give are remembered in .env.aws (git-ignored, never committed).
# Nothing secret is written to the repo or to GitHub: GitHub only receives
# role ARNs and the region, as repository variables.

TOTAL_STAGES=7

cd "$(git rev-parse --show-toplevel)"
ENV_FILE=".env.aws"
RABAED_ENV="${1:-dev}"

# pnpm straight from PATH, or through corepack when it is not installed globally.
pnpm_() { if command -v pnpm >/dev/null 2>&1; then pnpm "$@"; else corepack pnpm "$@"; fi; }
cdk_() { pnpm_ --silent --filter @rabaed/infra exec cdk "$@" -c "env=$RABAED_ENV"; }

# ask_required KEY "Prompt": ask until the answer is not empty.
ask_required() {
  ask "$1" "$2"
  while [[ -z "${!1}" ]]; do warn "an answer is needed"; ask "$1" "$2"; done
}

# Hands the profile's short-lived credentials to the CDK, in this process
# only; called before each AWS step so they have not expired.
fresh_credentials() { eval "$(aws configure export-credentials --profile "$AWS_PROFILE" --format env)"; }

stack_output() {
  aws cloudformation describe-stacks --region "$REGION" --stack-name "$STACK" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

banner "Rabaed AWS account setup: ${RABAED_ENV}"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Tools on this computer"
say "You need a current AWS CLI v2 (one that has 'aws login'), the GitHub CLI and Node 24."
while true; do
  missing=()
  aws login help >/dev/null 2>&1 || missing+=("AWS CLI v2, latest: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html")
  command -v gh >/dev/null 2>&1 || missing+=("GitHub CLI: https://cli.github.com")
  [[ "$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)" -ge 24 ]] \
    || missing+=("Node 24 or later: https://nodejs.org")
  (( ${#missing[@]} )) || break
  for m in "${missing[@]}"; do warn "missing $m"; done
  pause "Install them, open a new terminal if needed, then press Enter to check again."
done

# Region, stack and repository come from packages/infra/src/config.ts, the one
# source of truth (Node runs the TypeScript directly).
read -r REGION STACK REPOSITORY OIDC_SUBJECT < <(node --input-type=module -e "
  const c = await import('./packages/infra/src/config.ts');
  const env = c.environmentConfig(process.argv[1]);
  console.log(env.region, c.accountStackName(env), c.repositoryName(env.github), c.oidcSubjectPrefix(env.github));" "$RABAED_ENV")

if ! gh auth status >/dev/null 2>&1; then
  step "Sign the GitHub CLI in to an account that can administer $REPOSITORY:"
  gh auth login || warn "gh sign-in failed; stage 7 will list what to set by hand"
fi
note "✓ $(aws --version 2>&1 | cut -d' ' -f1), gh, node $(node --version); region $REGION"
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "AWS account"
say "Rabaed ${RABAED_ENV} gets its own AWS account, kept apart from anything else."
if confirm "Do you need to create a new AWS account?"; then
  open_url "https://portal.aws.amazon.com/billing/signup"
  step "Sign up with a shared mailbox the company controls (not a personal email)."
  step "Choose the Basic support plan."
  step "Once signed in as the root user: account menu (top right) → Security credentials"
  step "→ Assign MFA device, and protect the root user with MFA before going on."
  pause "Press Enter once the account exists and root MFA is on."
fi
say "Now sign the AWS CLI in with the console. Nothing is stored in the repo;"
say "the CLI keeps short-lived credentials in your home folder."
ask_required AWS_PROFILE "AWS CLI profile name to use (e.g. rabaed-${RABAED_ENV}):"
export AWS_PROFILE
write_env AWS_PROFILE "$AWS_PROFILE"
until aws sts get-caller-identity >/dev/null 2>&1; do
  step "Running: aws login --profile $AWS_PROFILE --region $REGION  (a browser window opens)"
  aws login --profile "$AWS_PROFILE" --region "$REGION" || warn "sign-in did not finish"
  aws sts get-caller-identity >/dev/null 2>&1 || pause "Press Enter to try again (Ctrl-C to stop)."
done
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
note "✓ signed in to account $AWS_ACCOUNT_ID as $(aws sts get-caller-identity --query Arn --output text)"
confirm "Is $AWS_ACCOUNT_ID the account for Rabaed ${RABAED_ENV}?" || { warn "Stopped: sign in to the right account and re-run."; exit 1; }
write_env AWS_ACCOUNT_ID "$AWS_ACCOUNT_ID"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Billing contact"
say "AWS emails invoices and billing notices to the billing contact."
ask_required BILLING_CONTACT_NAME "Billing contact full name:"
ask_required BILLING_CONTACT_TITLE "Their job title:"
ask_required BILLING_CONTACT_EMAIL "Their email:"
ask_required BILLING_CONTACT_PHONE "Their phone, with country code (e.g. +966 5x xxx xxxx):"
write_env BILLING_CONTACT_NAME "$BILLING_CONTACT_NAME"
write_env BILLING_CONTACT_TITLE "$BILLING_CONTACT_TITLE"
write_env BILLING_CONTACT_EMAIL "$BILLING_CONTACT_EMAIL"
write_env BILLING_CONTACT_PHONE "$BILLING_CONTACT_PHONE"
fresh_credentials
if aws account put-alternate-contact --alternate-contact-type BILLING \
    --name "$BILLING_CONTACT_NAME" --title "$BILLING_CONTACT_TITLE" \
    --email-address "$BILLING_CONTACT_EMAIL" --phone-number "$BILLING_CONTACT_PHONE"; then
  note "✓ billing contact set (see it under Account → Alternate contacts)"
else
  SKIPPED+=("billing contact (AWS refused it; check the answers and re-run)")
fi
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Budget alert email"
say "A monthly cost budget emails this address at 80% of actual spend and"
say "when the forecast passes 100%. The amount is monthlyBudgetUsd in"
say "packages/infra/src/config.ts; the email stays out of the repo."
ask_required BUDGET_ALERT_EMAIL "Email for budget alerts:"
write_env BUDGET_ALERT_EMAIL "$BUDGET_ALERT_EMAIL"
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "CDK bootstrap"
say "Bootstrapping creates the CDK's own roles and asset bucket in $REGION,"
say "which every later deploy goes through. Safe to repeat."
if confirm "Bootstrap aws://$AWS_ACCOUNT_ID/$REGION now?"; then
  fresh_credentials
  cdk_ bootstrap "aws://$AWS_ACCOUNT_ID/$REGION"
else
  SKIPPED+=("CDK bootstrap (re-run this wizard)")
fi
pause

# ── 6 ────────────────────────────────────────────────────────────────────
stage "GitHub access and budget ($STACK)"
say "Deploys the account stack from packages/infra/src/account-stack.ts:"
step "trust for GitHub Actions through OIDC (no AWS keys stored in GitHub);"
step "rabaed-${RABAED_ENV}-github-deploy: usable only from $REPOSITORY main;"
step "rabaed-${RABAED_ENV}-github-diff: read-only, for cdk diff on pull requests;"
step "the monthly budget alert to $BUDGET_ALERT_EMAIL."
# The roles trust only tokens whose subject starts with the prefix in config.ts.
actual_subject=$(gh api "repos/$REPOSITORY/actions/oidc/customization/sub" --jq .sub_claim_prefix 2>/dev/null || true)
if [[ -n "$actual_subject" && "$actual_subject" != "$OIDC_SUBJECT" ]]; then
  warn "GitHub signs this repository's tokens as '$actual_subject',"
  warn "but config.ts expects '$OIDC_SUBJECT'. Fix config.ts before deploying."
fi
note "The CDK lists the IAM changes and asks you to approve them."
if confirm "Deploy $STACK now?"; then
  fresh_credentials
  cdk_ deploy "$STACK" --parameters "BudgetAlertEmail=$BUDGET_ALERT_EMAIL"
else
  SKIPPED+=("deploy $STACK (re-run this wizard)")
fi
pause

# ── 7 ────────────────────────────────────────────────────────────────────
stage "GitHub repository variables"
say "Pull request and deploy workflows read these non-secret values."
arn_ok() { [[ -n "$1" && "$1" != None ]]; }
if fresh_credentials && DEPLOY_ROLE_ARN=$(stack_output DeployRoleArn) && DIFF_ROLE_ARN=$(stack_output DiffRoleArn) \
    && arn_ok "$DEPLOY_ROLE_ARN" && arn_ok "$DIFF_ROLE_ARN"; then
  set_var AWS_REGION "$REGION"
  set_var AWS_DEPLOY_ROLE_ARN "$DEPLOY_ROLE_ARN"
  set_var AWS_DIFF_ROLE_ARN "$DIFF_ROLE_ARN"
else
  warn "Could not read the role ARNs from $STACK (not deployed yet, or the sign-in expired)."
  SKIPPED+=("GitHub variables AWS_REGION, AWS_DEPLOY_ROLE_ARN, AWS_DIFF_ROLE_ARN (re-run after stage 6)")
fi
pause

finish
