#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Sets up the AWS account for one Rabaed environment (dev by default):
#   bash packages/infra/scripts/setup-aws-account.sh [environment]
#
# Re-runnable: every stage either checks first or is safe to repeat, and the
# answers you give are remembered in .env.aws (git-ignored, never committed).
# Nothing secret is written to the repo or to GitHub (the budget and alarm
# emails are deploy-time parameters of the account stack): GitHub only receives
# role ARNs, the region, the interim certificate (public) and its ARN, and the
# email sender's address, as repository variables, and the deploy environment
# (main only). The licensed Thmanyah fonts go from this computer
# straight to the private build assets bucket.

TOTAL_STAGES=11

# The repository this script is in, wherever it is run from.
cd "$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
ENV_FILE=".env.aws"
RABAED_ENV="${1:-dev}"

# pnpm straight from PATH, or through corepack when it is not installed globally.
pnpm_() { if command -v pnpm >/dev/null 2>&1; then pnpm "$@"; else corepack pnpm "$@"; fi; }
cdk_() { pnpm_ --silent --filter @rabaed/infra exec cdk "$@" -c "env=$RABAED_ENV"; }

# ask_required KEY "Prompt": ask until the answer is not empty.
ask_required() {
  ask "$1" "$2"
  while [[ -z "${!1}" ]]; do warn "an answer is needed"; ask "$1" "$2"; done
}

# Hands the profile's short-lived credentials to the CDK, in this process
# only; called before each AWS step so they have not expired.
fresh_credentials() { eval "$(aws configure export-credentials --profile "$AWS_PROFILE" --format env)"; }

# stack_output OUTPUT [STACK]: an output of the account stack, or of STACK.
stack_output() {
  aws cloudformation describe-stacks --region "$REGION" --stack-name "${2:-$STACK}" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" --output text
}

# Git Bash hands Windows programs (the AWS CLI) Windows paths.
native_path() { if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi; }

banner "Rabaed AWS account setup: ${RABAED_ENV}"

# ── 1 ────────────────────────────────────────────────────────────────────
stage "Tools on this computer"
say "You need a current AWS CLI v2 (one that has 'aws login'), the GitHub CLI, OpenSSL and Node 24."
while true; do
  missing=()
  aws login help >/dev/null 2>&1 || missing+=("AWS CLI v2, latest: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html")
  command -v gh >/dev/null 2>&1 || missing+=("GitHub CLI: https://cli.github.com")
  command -v openssl >/dev/null 2>&1 || missing+=("OpenSSL (comes with Git for Windows; on macOS/Linux install it with your package manager)")
  [[ "$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)" -ge 24 ]] \
    || missing+=("Node 24 or later: https://nodejs.org")
  (( ${#missing[@]} )) || break
  for m in "${missing[@]}"; do warn "missing $m"; done
  pause "Install them, open a new terminal if needed, then press Enter to check again."
done

# Region, stack and repository come from packages/infra/src/config.ts, the one
# source of truth (Node runs the TypeScript directly).
read -r REGION STACK REPOSITORY OIDC_SUBJECT ACCOUNT_QUALIFIER ACCOUNT_TOOLKIT EXECUTION_POLICY GITHUB_ENVIRONMENT < <(node --input-type=module -e "
  const c = await import('./packages/infra/src/config.ts');
  const env = c.environmentConfig(process.argv[1]);
  const names = c.resourceNames(env);
  console.log(env.region, c.accountStackName(env), c.repositoryName(env.github), c.oidcSubjectPrefix(env.github),
    c.accountBootstrap.qualifier, c.accountBootstrap.toolkitStackName, names.executionPolicy, names.githubEnvironment);" "$RABAED_ENV")

if ! gh auth status >/dev/null 2>&1; then
  step "Sign the GitHub CLI in to an account that can administer $REPOSITORY:"
  gh auth login || warn "gh sign-in failed; stage 8 will list what to set by hand"
fi
note "✓ $(aws --version 2>&1 | cut -d' ' -f1), gh, node $(node --version); region $REGION"
pause

# ── 2 ────────────────────────────────────────────────────────────────────
stage "AWS account"
say "Rabaed ${RABAED_ENV} gets its own AWS account, kept apart from anything else."
if confirm "Do you need to create a new AWS account?"; then
  open_url "https://portal.aws.amazon.com/billing/signup"
  step "Sign up with a shared mailbox the company controls (not a personal email)."
  step "Choose the Basic support plan."
  step "Once signed in as the root user: account menu (top right) → Security credentials"
  step "→ Assign MFA device, and protect the root user with MFA before going on."
  pause "Press Enter once the account exists and root MFA is on."
fi
say "Now sign the AWS CLI in with the console. Nothing is stored in the repo;"
say "the CLI keeps short-lived credentials in your home folder."
ask_required AWS_PROFILE "AWS CLI profile name to use (e.g. rabaed-${RABAED_ENV}):"
export AWS_PROFILE
write_env AWS_PROFILE "$AWS_PROFILE"
until aws sts get-caller-identity >/dev/null 2>&1; do
  step "Running: aws login --profile $AWS_PROFILE --region $REGION  (a browser window opens)"
  aws login --profile "$AWS_PROFILE" --region "$REGION" || warn "sign-in did not finish"
  aws sts get-caller-identity >/dev/null 2>&1 || pause "Press Enter to try again (Ctrl-C to stop)."
done
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
note "✓ signed in to account $AWS_ACCOUNT_ID as $(aws sts get-caller-identity --query Arn --output text)"
confirm "Is $AWS_ACCOUNT_ID the account for Rabaed ${RABAED_ENV}?" || { warn "Stopped: sign in to the right account and re-run."; exit 1; }
write_env AWS_ACCOUNT_ID "$AWS_ACCOUNT_ID"

# ── 3 ────────────────────────────────────────────────────────────────────
stage "Billing contact"
say "AWS emails invoices and billing notices to the billing contact."
ask_required BILLING_CONTACT_NAME "Billing contact full name:"
ask_required BILLING_CONTACT_TITLE "Their job title:"
ask_required BILLING_CONTACT_EMAIL "Their email:"
ask_required BILLING_CONTACT_PHONE "Their phone, with country code (e.g. +966 5x xxx xxxx):"
write_env BILLING_CONTACT_NAME "$BILLING_CONTACT_NAME"
write_env BILLING_CONTACT_TITLE "$BILLING_CONTACT_TITLE"
write_env BILLING_CONTACT_EMAIL "$BILLING_CONTACT_EMAIL"
write_env BILLING_CONTACT_PHONE "$BILLING_CONTACT_PHONE"
fresh_credentials
if aws account put-alternate-contact --alternate-contact-type BILLING \
    --name "$BILLING_CONTACT_NAME" --title "$BILLING_CONTACT_TITLE" \
    --email-address "$BILLING_CONTACT_EMAIL" --phone-number "$BILLING_CONTACT_PHONE"; then
  note "✓ billing contact set (see it under Account → Alternate contacts)"
else
  SKIPPED+=("billing contact (AWS refused it; check the answers and re-run)")
fi
pause

# ── 4 ────────────────────────────────────────────────────────────────────
stage "Alert emails"
say "A monthly cost budget emails this address at 80% of actual spend and"
say "when the forecast passes 100%. The amount is monthlyBudgetUsd in"
say "packages/infra/src/config.ts; the emails stay out of the repo."
ask_required BUDGET_ALERT_EMAIL "Email for budget alerts:"
write_env BUDGET_ALERT_EMAIL "$BUDGET_ALERT_EMAIL"
say "CloudWatch alarms (api errors, unhealthy web, outbox, database) email this"
say "address when they fire and when they clear. It can be the same one."
ask_required ALARM_EMAIL "Email for alarms:"
write_env ALARM_EMAIL "$ALARM_EMAIL"
pause

# ── 5 ────────────────────────────────────────────────────────────────────
stage "GitHub access, deploy limits and budget ($STACK)"
say "First a CDK bootstrap of its own for the account stack ($ACCOUNT_TOOLKIT,"
say "qualifier $ACCOUNT_QUALIFIER): only a person deploys through it, never GitHub."
say "Then the account stack from packages/infra/src/account-stack.ts:"
step "trust for GitHub Actions through OIDC (no AWS keys stored in GitHub);"
step "rabaed-${RABAED_ENV}-github-deploy: usable only by the deploy job in the GitHub"
step "  environment '$GITHUB_ENVIRONMENT' (main only, stage 8), to deploy, push images and run"
step "  the migration task (the storage stack, deployed on merge, also lets it read the"
step "  private fonts);"
step "rabaed-${RABAED_ENV}-github-diff: read-only, for cdk diff on pull requests;"
step "what a deploy may reach: $EXECUTION_POLICY, which CloudFormation runs with"
step "  instead of AdministratorAccess (stage 6), and the permissions boundary"
step "  rabaed-${RABAED_ENV}-boundary on every role a deploy creates;"
step "the monthly budget alert to $BUDGET_ALERT_EMAIL;"
step "the alarm topic rabaed-${RABAED_ENV}-alarms, which emails $ALARM_EMAIL."
# The roles trust only tokens whose subject starts with the prefix in config.ts.
actual_subject=$(gh api "repos/$REPOSITORY/actions/oidc/customization/sub" --jq .sub_claim_prefix 2>/dev/null || true)
if [[ -n "$actual_subject" && "$actual_subject" != "$OIDC_SUBJECT" ]]; then
  warn "GitHub signs this repository's tokens as '$actual_subject',"
  warn "but config.ts expects '$OIDC_SUBJECT'. Fix config.ts before deploying."
fi
note "The CDK lists the IAM changes and asks you to approve them."
if confirm "Bootstrap $ACCOUNT_TOOLKIT and deploy $STACK now?"; then
  fresh_credentials
  cdk_ bootstrap "aws://$AWS_ACCOUNT_ID/$REGION" --qualifier "$ACCOUNT_QUALIFIER" --toolkit-stack-name "$ACCOUNT_TOOLKIT"
  cdk_ deploy "$STACK" --toolkit-stack-name "$ACCOUNT_TOOLKIT" \
    --parameters "BudgetAlertEmail=$BUDGET_ALERT_EMAIL" --parameters "AlarmEmail=$ALARM_EMAIL"
  say "AWS Notifications emails $ALARM_EMAIL once to confirm the alarm subscription"
  say "(subject \"AWS Notification - Subscription Confirmation\"). Alarms reach it only after that."
  pause "Click \"Confirm subscription\" in that email (if this is its first deploy), then press Enter."
else
  SKIPPED+=("deploy $STACK (re-run this wizard)")
fi
pause

# ── 6 ────────────────────────────────────────────────────────────────────
stage "CDK bootstrap for deploys"
say "Bootstrapping creates the CDK's own roles and asset bucket in $REGION,"
say "which every deploy from GitHub goes through. Its CloudFormation role gets"
say "$EXECUTION_POLICY (stage 5), not AdministratorAccess: a deploy can"
say "reach only the services the stacks use, and only roles with the boundary."
say "An account bootstrapped before (with AdministratorAccess) is switched over"
say "here. Safe to repeat."
EXECUTION_POLICY_ARN="arn:aws:iam::$AWS_ACCOUNT_ID:policy/$EXECUTION_POLICY"
if confirm "Bootstrap aws://$AWS_ACCOUNT_ID/$REGION now?"; then
  fresh_credentials
  if aws iam get-policy --policy-arn "$EXECUTION_POLICY_ARN" >/dev/null 2>&1; then
    cdk_ bootstrap "aws://$AWS_ACCOUNT_ID/$REGION" --cloudformation-execution-policies "$EXECUTION_POLICY_ARN"
  else
    warn "$EXECUTION_POLICY does not exist yet: deploy $STACK first (stage 5)."
    SKIPPED+=("CDK bootstrap for deploys (re-run this wizard after stage 5)")
  fi
else
  SKIPPED+=("CDK bootstrap for deploys (re-run this wizard)")
fi
pause

# ── 7 ────────────────────────────────────────────────────────────────────
stage "Interim HTTPS certificate"
say "The load balancer serves HTTPS only. Until Rabaed has a domain, no public"
say "certificate authority can issue one for its AWS address, so this stage makes"
say "a self-signed certificate for *.$REGION.elb.amazonaws.com and imports it into"
say "AWS Certificate Manager. Browsers warn once (\"not private\"); continue past it."
say "The private key goes straight to AWS and is deleted here; it is never saved."
CERT_ARN=$(_existing AWS_CERTIFICATE_ARN || true)
cert_expiry() {
  aws acm describe-certificate --region "$REGION" --certificate-arn "$1" --query Certificate.NotAfter --output text 2>/dev/null
}
if [[ -n "$CERT_ARN" ]] && fresh_credentials && expiry=$(cert_expiry "$CERT_ARN"); then
  note "✓ current certificate expires $expiry"
  confirm "Replace it with a new one (do this within a month of expiry)?" || CERT_ARN_KEEP=1
fi
if [[ -z "${CERT_ARN_KEEP:-}" ]]; then
  if confirm "Create and import the certificate now?"; then
    certdir=$(mktemp -d)
    # Git Bash would otherwise rewrite "/CN=…" as a Windows path.
    MSYS_NO_PATHCONV=1 openssl req -x509 -newkey rsa:2048 -nodes -days 397 \
      -keyout "$(native_path "$certdir/key.pem")" -out "$(native_path "$certdir/cert.pem")" \
      -subj "/CN=rabaed-${RABAED_ENV} interim" \
      -addext "subjectAltName=DNS:*.$REGION.elb.amazonaws.com" 2>/dev/null
    fresh_credentials
    if CERT_ARN=$(aws acm import-certificate --region "$REGION" \
        --certificate "fileb://$(native_path "$certdir/cert.pem")" \
        --private-key "fileb://$(native_path "$certdir/key.pem")" \
        --tags "Key=rabaed-environment,Value=$RABAED_ENV" \
        --query CertificateArn --output text); then
      write_env AWS_CERTIFICATE_ARN "$CERT_ARN"
    else
      SKIPPED+=("interim HTTPS certificate (re-run this wizard)")
    fi
    rm -rf "$certdir"
  else
    SKIPPED+=("interim HTTPS certificate (re-run this wizard)")
  fi
fi
pause

# ── 8 ────────────────────────────────────────────────────────────────────
stage "GitHub repository variables"
say "Pull request and deploy workflows read these non-secret values."
arn_ok() { [[ -n "$1" && "$1" != None ]]; }
if fresh_credentials && DEPLOY_ROLE_ARN=$(stack_output DeployRoleArn) && DIFF_ROLE_ARN=$(stack_output DiffRoleArn) \
    && arn_ok "$DEPLOY_ROLE_ARN" && arn_ok "$DIFF_ROLE_ARN"; then
  set_var AWS_REGION "$REGION"
  set_var AWS_DEPLOY_ROLE_ARN "$DEPLOY_ROLE_ARN"
  set_var AWS_DIFF_ROLE_ARN "$DIFF_ROLE_ARN"
else
  warn "Could not read the role ARNs from $STACK (not deployed yet, or the sign-in expired)."
  SKIPPED+=("GitHub variables AWS_REGION, AWS_DEPLOY_ROLE_ARN, AWS_DIFF_ROLE_ARN (re-run after stage 5)")
fi
# The deploy role trusts only jobs in this environment; it admits only main,
# so a workflow on any other branch cannot run in it.
say "The deploy job runs in the GitHub environment '$GITHUB_ENVIRONMENT', open to main only."
environments="repos/$REPOSITORY/environments/$GITHUB_ENVIRONMENT"
if gh api -X PUT "$environments" --input - >/dev/null 2>&1 \
    <<< '{"deployment_branch_policy":{"protected_branches":false,"custom_branch_policies":true}}' \
  && { gh api "$environments/deployment-branch-policies" --jq '.branch_policies[] | "\(.type // "branch") \(.name)"' 2>/dev/null \
         | grep -qx "branch main" \
       || gh api -X POST "$environments/deployment-branch-policies" -f name=main -f type=branch >/dev/null 2>&1; } \
  && [[ "$(gh api "$environments/deployment-branch-policies" --jq '[.branch_policies[].name] | join(",")' 2>/dev/null)" == main ]]; then
  printf '  %s✓ set%s GitHub environment %s (deployments from main only)\n' "$GREEN" "$RESET" "$GITHUB_ENVIRONMENT"
else
  warn "Could not set up the GitHub environment (needs gh signed in as a repository admin), or it admits more than main."
  SKIPPED+=("GitHub environment '$GITHUB_ENVIRONMENT': Settings → Environments → New environment; Deployment branches → Selected branches → add main, and only main")
fi
# The certificate itself is public; the deploy's smoke test trusts it (and only it).
CERT_ARN=$(_existing AWS_CERTIFICATE_ARN || true)
if [[ -n "$CERT_ARN" ]] && fresh_credentials \
    && CERT_PEM=$(aws acm get-certificate --region "$REGION" --certificate-arn "$CERT_ARN" --query Certificate --output text); then
  set_var AWS_CERTIFICATE_ARN "$CERT_ARN"
  set_var AWS_CERTIFICATE_PEM "$CERT_PEM"
else
  SKIPPED+=("GitHub variables AWS_CERTIFICATE_ARN, AWS_CERTIFICATE_PEM (re-run after stage 7)")
fi
pause

# ── 9 ────────────────────────────────────────────────────────────────────
stage "Email sender (Amazon SES)"
say "Rabaed sends email (Rabaed Admin sign-in codes, invitations) through Amazon SES"
say "in $REGION, from one address. Until Rabaed has a domain, SES verifies that one"
say "address: AWS emails it a link to click. Use a mailbox the company controls."
say "The address stays out of the repo: it is kept in .env.aws and a GitHub variable,"
say "and each deploy passes it to the App stack, whose api may send only from it."
ask_required MAIL_FROM_ADDRESS "Address every email comes from (e.g. no-reply@<company domain>):"
write_env MAIL_FROM_ADDRESS "$MAIL_FROM_ADDRESS"
ses_verified() {
  [[ "$(aws sesv2 get-email-identity --region "$REGION" --email-identity "$MAIL_FROM_ADDRESS" \
    --query VerifiedForSendingStatus --output text 2>/dev/null)" == True ]]
}
MAIL_VERIFIED=""
if fresh_credentials && ses_verified; then
  MAIL_VERIFIED=1
  note "✓ $MAIL_FROM_ADDRESS is verified"
elif confirm "Ask SES to verify $MAIL_FROM_ADDRESS now?"; then
  # SES sends the link when the identity is created; for a new link, delete
  # the identity in the SES console and re-run.
  if ! aws sesv2 get-email-identity --region "$REGION" --email-identity "$MAIL_FROM_ADDRESS" >/dev/null 2>&1; then
    aws sesv2 create-email-identity --region "$REGION" --email-identity "$MAIL_FROM_ADDRESS" >/dev/null \
      || warn "SES refused the address; check it and re-run"
  fi
  step "AWS emails $MAIL_FROM_ADDRESS (subject \"Amazon Web Services – Email Address Verification Request\")."
  step "Click the link in it within 24 hours."
  while true; do
    pause "Press Enter once you have clicked it."
    fresh_credentials
    if ses_verified; then MAIL_VERIFIED=1; note "✓ verified"; break; fi
    warn "SES does not show it verified yet (it can take a minute)."
    confirm "Check again?" || break
  done
fi
if [[ -n "$MAIL_VERIFIED" ]]; then
  set_var MAIL_FROM_ADDRESS "$MAIL_FROM_ADDRESS"
  note "The next deploy lets the api send from it."
else
  SKIPPED+=("email sender: verify $MAIL_FROM_ADDRESS (re-run this wizard)")
fi

# A new account's SES is in the sandbox: it sends only to verified addresses,
# 200 a day. Leaving it needs AWS to review a request, usually within a day.
if [[ -n "$MAIL_VERIFIED" ]] && fresh_credentials; then
  if [[ "$(aws sesv2 get-account --region "$REGION" --query ProductionAccessEnabled --output text)" == True ]]; then
    note "✓ SES production access: on"
  else
    review=$(aws sesv2 get-account --region "$REGION" --query Details.ReviewDetails.Status --output text 2>/dev/null || true)
    if [[ "$review" == PENDING ]]; then
      note "SES production access was requested; AWS is reviewing it. Re-run later to check."
      SKIPPED+=("SES production access (AWS is reviewing the request)")
    else
      say "SES is in the sandbox: it sends only to verified addresses, 200 a day."
      [[ "$review" == DENIED ]] && warn "AWS denied the last request; see the AWS Support case it opened before asking again."
      website=$(stack_output Url "Rabaed-${RABAED_ENV}-App" 2>/dev/null || true)
      arn_ok "$website" || website="https://github.com/$REPOSITORY"
      if ! confirm "Request production access now (transactional email, website $website)?"; then
        SKIPPED+=("SES production access (re-run this wizard)")
      elif aws sesv2 put-account-details --region "$REGION" --production-access-enabled \
          --mail-type TRANSACTIONAL --website-url "$website" --contact-language EN \
          --use-case-description "Rabaed is a business-to-business construction management platform. It sends transactional email only: one-time sign-in codes for its staff portal, and invitations that a company sends to its own colleagues. No marketing email. Each email goes to one recipient who asked for it or was invited by their own company; bounces and complaints are tracked through an SES configuration set and suppressed."; then
        note "✓ requested; AWS answers by email, usually within a day"
        SKIPPED+=("SES production access (AWS is reviewing the request)")
      else
        SKIPPED+=("SES production access (the request failed; re-run this wizard)")
      fi
    fi
  fi
fi

# One test email from the sender to itself, which works even in the sandbox.
if [[ -n "$MAIL_VERIFIED" ]] && confirm "Send a test email from $MAIL_FROM_ADDRESS to itself?"; then
  fresh_credentials
  configuration_set=()
  aws sesv2 get-configuration-set --region "$REGION" --configuration-set-name "rabaed-${RABAED_ENV}" >/dev/null 2>&1 \
    && configuration_set=(--configuration-set-name "rabaed-${RABAED_ENV}")
  # The ${a[@]+…} form expands an empty array safely under set -u in older bash too.
  if aws sesv2 send-email --region "$REGION" ${configuration_set[@]+"${configuration_set[@]}"} \
      --from-email-address "Rabaed <$MAIL_FROM_ADDRESS>" \
      --destination "{\"ToAddresses\":[\"$MAIL_FROM_ADDRESS\"]}" \
      --content '{"Simple":{"Subject":{"Data":"Rabaed email test"},"Body":{"Text":{"Data":"Amazon SES sends Rabaed email. Sent by the AWS setup wizard."}}}}' >/dev/null; then
    confirm "Sent. Did \"Rabaed email test\" reach $MAIL_FROM_ADDRESS (check spam too)?" \
      || SKIPPED+=("test email did not arrive (SES console → Account dashboard; check spam)")
  else
    SKIPPED+=("test email (SES refused it; re-run this wizard)")
  fi
fi
pause

# ── 10 ───────────────────────────────────────────────────────────────────
stage "Thmanyah fonts (private)"
say "Arabic is shown in Thmanyah Sans, which is licensed: its files must never be"
say "in the repo. This stage uploads them to the private build assets bucket; the"
say "deploy bundles them into the web image, which serves them from Rabaed's own"
say "address. Without them, Arabic falls back to IBM Plex Sans Arabic."
STORAGE_STACK="Rabaed-${RABAED_ENV}-Storage"
if fresh_credentials && BUCKET=$(stack_output BuildAssetsBucket "$STORAGE_STACK" 2>/dev/null) && arn_ok "$BUCKET"; then
  note "The thmanyahsans-{Light,Regular,Medium,Bold,Black}.woff2 files, in a folder outside"
  note "the repo or in design/reference/claude-design/assets/fonts/thmanyah (git-ignored)."
  ask_required THMANYAH_FONTS_DIR "Folder with the Thmanyah Sans .woff2 files:"
  # Accept a pasted Windows path (C:\…) or ~ in Git Bash.
  fonts_dir="${THMANYAH_FONTS_DIR/#\~/$HOME}"
  if command -v cygpath >/dev/null 2>&1; then fonts_dir=$(cygpath -u "$fonts_dir"); fi
  shopt -s nocaseglob nullglob
  font_files=("$fonts_dir"/thmanyahsans-*.woff2)
  shopt -u nocaseglob nullglob
  if (( ${#font_files[@]} == 0 )); then
    warn "No thmanyahsans-*.woff2 files in $THMANYAH_FONTS_DIR."
    SKIPPED+=("Thmanyah fonts (re-run this wizard with the folder that holds them)")
  else
    write_env THMANYAH_FONTS_DIR "$THMANYAH_FONTS_DIR"
    for f in "${font_files[@]}"; do note "  $(basename "$f")"; done
    if confirm "Upload these ${#font_files[@]} files to s3://$BUCKET/fonts/thmanyah/?"; then
      fresh_credentials
      failed=0
      for f in "${font_files[@]}"; do
        aws s3 cp "$(native_path "$f")" "s3://$BUCKET/fonts/thmanyah/$(basename "$f")" --region "$REGION" --only-show-errors \
          || failed=$((failed + 1))
      done
      if (( failed == 0 )); then
        note "✓ uploaded; the next merge to main builds dev's web image with them"
      else
        SKIPPED+=("Thmanyah fonts: $failed file(s) failed to upload (re-run this wizard)")
      fi
    else
      SKIPPED+=("Thmanyah fonts (re-run this wizard)")
    fi
  fi
else
  warn "$STORAGE_STACK is not deployed yet (or the sign-in expired); the first deploy creates it."
  SKIPPED+=("Thmanyah fonts (re-run this wizard after the first deploy)")
fi
pause

# ── 11 ───────────────────────────────────────────────────────────────────
stage "Test alarm"
say "Sets one alarm to ALARM for a moment, to prove notifications arrive."
say "CloudWatch puts it back within a few minutes, which sends an OK email too."
TEST_ALARM="rabaed-${RABAED_ENV}-load-balancer-5xx"
if fresh_credentials && aws cloudwatch describe-alarms --region "$REGION" --alarm-names "$TEST_ALARM"     --query 'MetricAlarms[0].AlarmName' --output text 2>/dev/null | grep -q "$TEST_ALARM"; then
  if confirm "Trigger $TEST_ALARM now?"; then
    aws cloudwatch set-alarm-state --region "$REGION" --alarm-name "$TEST_ALARM"       --state-value ALARM --state-reason "Test from the setup wizard: notifications work."
    note "✓ triggered; an \"ALARM: $TEST_ALARM\" email should reach $ALARM_EMAIL within a minute."
    confirm "Did it arrive?" || SKIPPED+=("alarm email (check the subscription is confirmed: SNS → Topics → rabaed-${RABAED_ENV}-alarms)")
  else
    SKIPPED+=("test alarm (re-run this wizard)")
  fi
else
  warn "The alarms are not deployed yet (or the sign-in expired); the monitoring stack comes with the next deploy."
  SKIPPED+=("test alarm (re-run this wizard after the next deploy)")
fi
pause

finish
