// Reports module. Exposes window.RP2 {V, view, bind}.
(function(){
const S=RS.S,{TPL,GROUPS,ST,SORD,days,reps,W1,HSE1,MP,PPL}=RD;const L=(e,a)=>S.lang==='ar'?a:e;const esc=RS.esc;const T=x=>esc(L(x[0],x[1]));
const V={opt:'A',tpl:'daily',sel:7,role:'ctr',open:null,form:null,step:0,pdf:false,toast:null,ask:false,note:'',weekly:false};
const DOW=[['Sun','أحد'],['Mon','اثنين'],['Tue','ثلاثاء'],['Wed','أربعاء'],['Thu','خميس'],['Fri','جمعة'],['Sat','سبت']];
const fd=d=>`${L(DOW[new Date(2025,7,d).getDay()][0],DOW[new Date(2025,7,d).getDay()][1])} ${d} ${L('Aug','أغسطس')} 2025`;
const stp=k=>`<span class="stp" style="background:var(--tone-${ST[k][2]}-tint);color:var(--tone-${ST[k][2]}-fg)"><i></i>${L(ST[k][0],ST[k][1])}</span>`;
const age=w=>{const n=Math.min(4,Math.max(0,w));return n?`<span class="age">${[1,2,3,4].map(i=>`<i style="${i<=n?`background:${n>=3?'#ee964b':'#9aa0ad'};box-shadow:none`:''}"></i>`).join('')}</span>`:''};
const tot=r=>r.mp.reduce((a,b)=>a+b,0);
const rep=d=>reps.find(r=>r.d===d);
const tone=k=>TPL[k].tone;
/* ---- template chooser ---- */
function tplRail(){return GROUPS.map(g=>`<div class="rg"><h6>${L(g[1],g[2])}</h6>${Object.entries(TPL).filter(([k,t])=>t.g===g[0]).map(([k,t])=>`<button class="rt${V.tpl===k?' on':''}" data-tpl="${k}"><span class="ic" style="background:var(--tone-${t.tone}-tint);color:var(--tone-${t.tone}-solid)"><i class="ti ${t.ic}"></i></span><span class="tx"><b>${L(t.en,t.ar)}</b><small>${L(t.d[0],t.d[1])}</small></span></button>`).join('')}</div>`).join('')}
function tplTabs(){return `<div class="rtabs">${GROUPS.map(g=>`<span class="rtg"><small>${L(g[1],g[2])}</small>${Object.entries(TPL).filter(([k,t])=>t.g===g[0]).map(([k,t])=>`<button class="${V.tpl===k?'on':''}" data-tpl="${k}"><i class="ti ${t.ic}" style="color:var(--tone-${t.tone}-solid)"></i>${L(t.en,t.ar)}</button>`).join('')}</span>`).join('')}</div>`}
function tplCards(){return `<div class="rcards">${Object.entries(TPL).map(([k,t])=>`<button class="rcard${V.tpl===k?' on':''}" data-tpl="${k}" style="--c:var(--tone-${t.tone}-solid);--ct:var(--tone-${t.tone}-tint)"><span class="ic"><i class="ti ${t.ic}"></i></span><b>${L(t.en,t.ar)}</b><small>${L(GROUPS.find(g=>g[0]===t.g)[1],GROUPS.find(g=>g[0]===t.g)[2])}</small></button>`).join('')}</div>`}
/* ---- summary ---- */
function strip(){const c={affirmed:0,missing:0,review:0,submitted:0,returned:0,draft:0};days.forEach(x=>{if(c[x.st]!=null)c[x.st]++});
 return `<div class="rstrip"><b>${L('August 2025','أغسطس 2025')}</b>${[['affirmed'],['submitted'],['review'],['returned'],['missing']].map(([k])=>`<span><i style="background:var(--tone-${ST[k][2]}-solid)"></i>${c[k]} ${L(ST[k][0].toLowerCase(),ST[k][1])}</span>`).join('')}</div>`}
/* ---- calendar ---- */
function cal(){const first=new Date(2025,7,1).getDay();const cells=[];for(let i=0;i<first;i++)cells.push('<div class="cd emp"></div>');
 days.forEach(x=>{const r=rep(x.d);const st=x.st;cells.push(`<button class="cd ${st}${V.sel===x.d?' sel':''}" data-day="${x.d}"${st==='off'?' disabled':''}><span class="n">${x.d}</span>${st==='off'?`<small>${L('Off','عطلة')}</small>`:st==='none'?'':st==='missing'?`<span class="chip2 miss"><i class="ti ti-plus"></i>${L('Missing','مفقود')}</span>`:`${stp(st)}<small class="num">${tot(r)} ${L('workers','عامل')}</small>`}</button>`)});
 return `<div class="cal"><div class="cw">${[0,1,2,3,4,5,6].map(i=>`<span>${L(DOW[i][0],DOW[i][1])}</span>`).join('')}</div><div class="cg">${cells.join('')}</div></div>`}
function dayPrev(){const x=days[V.sel-1];if(!x)return '';const r=rep(V.sel);
 if(x.st==='missing')return `<div class="rprev"><span class="bic" style="background:var(--tone-red-tint);color:var(--tone-red-solid)"><i class="ti ti-calendar-x"></i></span><h3>${fd(V.sel)}</h3><p>${L('No Daily Site Report for this working day.','لا يوجد تقرير يومي لهذا اليوم.')}</p><button class="cb pri" data-new="${V.sel}"><i class="ti ti-plus"></i>${L('Add it late','إضافته متأخرًا')}</button></div>`;
 if(!r)return `<div class="rprev"><p>${L('Pick a day','اختر يومًا')}</p></div>`;
 return `<div class="rprev"><div class="rph"><div><span class="num" style="font-size:12px;color:var(--ui-muted);font-weight:700">${r.no}</span><h3>${fd(r.d)}</h3></div>${stp(r.st)}</div>${kpis(r,1)}<div class="rpl">${[[L('Weather','الطقس'),`${r.w==='dust'?L('Dust','غبار'):L('Sunny','مشمس')} · ${r.temp}°C${r.lost?' · '+r.lost+L(' h lost',' س ضائعة'):''}`],[L('Prepared by','أعدّه'),r.by],[L('Issues','المشكلات'),r.iss.length?T(r.iss[0]):L('None','لا يوجد')]].map(k=>`<div><span>${k[0]}</span><b>${k[1]}</b></div>`).join('')}</div><button class="cb" data-open="${r.id}" style="width:100%"><i class="ti ti-eye"></i>${L('Open report','فتح التقرير')}</button></div>`}
function kpis(r,sm){return `<div class="kp${sm?' sm':''}"><div style="--c:var(--tone-blue-solid)"><i class="ti ti-users"></i><b>${tot(r)}</b><span>${L('Manpower','العمالة')}</span></div><div style="--c:var(--tone-green-solid)"><i class="ti ti-tool"></i><b>${r.eq.filter(e=>e[1]).length}/${r.eq.length}</b><span>${L('Equipment working','المعدات العاملة')}</span></div><div style="--c:var(--tone-orange-solid)"><i class="ti ti-sun"></i><b>${r.temp}°</b><span>${r.lost?r.lost+L(' h lost',' س ضائعة'):L('No time lost','لا وقت ضائع')}</span></div><div style="--c:var(--tone-${r.inc?'red':'green'}-solid)"><i class="ti ti-shield"></i><b>${r.inc}</b><span>${L('Incidents','الحوادث')}</span></div></div>`}
/* ---- register (list) ---- */
function list(){const rs=V.tpl==='daily'?reps.slice().reverse():V.tpl==='weekly'?[W1]:V.tpl==='hse'?[HSE1]:[];
 if(!rs.length)return empty();
 return `<div class="tw"><table class="lv"><thead><tr><th>${L('Number','الرقم')}</th><th>${L('Report date','تاريخ التقرير')}</th><th>${L('Prepared by','أعدّه')}</th><th>${L('Summary','الملخص')}</th><th>${L('Stage','المرحلة')}</th><th>${L('Age','العمر')}</th><th></th></tr></thead><tbody>${SORD.filter(s=>rs.some(r=>r.st===s)).map(s=>`<tr class="gh open"><td colspan="7"><span class="ghi">${stp(s)}<small>${rs.filter(r=>r.st===s).length}</small></span></td></tr>${rs.filter(r=>r.st===s).map(r=>`<tr data-open="${r.id}" style="cursor:pointer"><td><span class="num" style="font-weight:600;color:var(--ui-muted);font-size:12.5px">${r.no}</span></td><td>${r.range?`${L('Week','الأسبوع')} 32 · ${r.range[0]}–${r.range[1]} ${L('Aug','أغسطس')}`:fd(r.d)}</td><td>${r.by}</td><td style="font-size:12.5px;color:var(--ui-text-2)">${r.mp?`${tot(r)} ${L('workers','عامل')} · ${r.eq.filter(e=>e[1]).length} ${L('equipment','معدات')}${r.iss.length?' · 1 '+L('issue','مشكلة'):''}`:r.pass?`${r.pass} ${L('pass','ناجح')} · ${r.fail} ${L('fail','راسب')}`:L('5 daily reports · 1 missing','5 تقارير يومية · 1 مفقود')}</td><td>${stp(r.st)}</td><td>${age(r.wk)}</td><td>${r.st==='affirmed'?'<i class="ti ti-file-text" style="color:var(--tone-red-solid)" title="PDF"></i>':''}</td></tr>`).join('')}`).join('')}</tbody></table></div>`}
/* ---- feed ---- */
function feed(){const rs=V.tpl==='daily'?reps.slice().reverse().slice(0,8):V.tpl==='weekly'?[W1]:[];if(!rs.length)return empty();
 return `<div class="feed">${days.filter(x=>x.st==='missing').map(x=>`<div class="fi miss"><span class="dt"><b>${x.d}</b><small>${L('Aug','أغسطس')}</small></span><div class="fc"><b>${L('Daily report missing','التقرير اليومي مفقود')} · ${fd(x.d)}</b><button class="cb sm" data-new="${x.d}"><i class="ti ti-plus"></i>${L('Add it late','إضافته متأخرًا')}</button></div></div>`).join('')}${rs.map(r=>`<div class="fi" data-open="${r.id}"><span class="dt"><b>${r.d||r.range[1]}</b><small>${L('Aug','أغسطس')}</small></span><div class="fc"><div class="fh"><span class="num">${r.no}</span>${stp(r.st)}${age(r.wk)}<span style="flex:1"></span><small>${r.by}</small></div>${r.mp?kpis(r,1):`<div style="font-size:13px;color:var(--ui-muted)">${L('Week 32 · built from 4 daily reports','الأسبوع 32 · من 4 تقارير يومية')}</div>`}</div></div>`).join('')}</div>`}
function empty(){return `<div class="empty2"><span class="ic" style="background:var(--tone-tomato-tint);color:var(--btn-pri)"><i class="ti ${TPL[V.tpl].ic}"></i></span><h2>${L('No reports yet','لا توجد تقارير بعد')}</h2><p>${L(`Start the first ${TPL[V.tpl].en}.`,`ابدأ أول ${TPL[V.tpl].ar}.`)}</p><button class="cb pri" data-new="today"><i class="ti ti-plus"></i>${L('New report','تقرير جديد')}</button></div>`}
/* ---- weekly ---- */
function bars(){const wd=[3,4,5,6,7];const mx=80;return `<div class="bars">${wd.map(d=>{const r=rep(d);const v=r?tot(r):0;return `<div class="bc"><div class="bw">${r?MP.map((m,i)=>`<i style="height:${r.mp[i]/mx*150}px;background:var(--tone-${['blue','cyan','violet','amber'][i]}-solid)"></i>`).join(''):`<em>${L('Missing','مفقود')}</em>`}</div><b class="num">${v||'—'}</b><small>${L(DOW[new Date(2025,7,d).getDay()][0],DOW[new Date(2025,7,d).getDay()][1])} ${d}</small></div>`}).join('')}</div><div class="lgd">${MP.map((m,i)=>`<span><i style="background:var(--tone-${['blue','cyan','violet','amber'][i]}-solid)"></i>${T(m)}</span>`).join('')}</div>`}
function weekly(){return `<div class="wkb">${V.ign?'':`<div class="warnb"><i class="ti ti-calendar-x"></i><div style="flex:1"><b>${L('Daily report for Tue 6 Aug is missing','التقرير اليومي ليوم الثلاثاء 6 أغسطس مفقود')}</b><small>${L('Totals below skip that day.','الإجماليات أدناه لا تشمل ذلك اليوم.')}</small></div><button class="cb sm" data-new="6">${L('Add it late','إضافته متأخرًا')}</button><button class="cb sm ter" data-act="ign">${L('Ignore','تجاهل')}</button></div>`}${V.ign?`<div class="okb" style="background:var(--tone-gray-tint);color:var(--ui-text-2)"><i class="ti ti-info-circle"></i>${L('Missing Tue 6 Aug ignored — recorded in history.','تم تجاهل 6 أغسطس — مسجّل في السجل.')}</div>`:''}
 <div class="okb" style="background:var(--tone-blue-tint);color:var(--tone-blue-fg)"><i class="ti ti-refresh"></i>${L('Pre-filled from 4 affirmed Daily reports (Sun 3 – Thu 7 Aug).','مُعبأ مسبقًا من 4 تقارير يومية معتمدة (3–7 أغسطس).')}</div>
 <div class="g2c"><section class="box"><h6>${L('Manpower per day','العمالة اليومية')}</h6>${bars()}</section><section class="box"><h6>${L('Week totals','إجماليات الأسبوع')}</h6><table class="mt"><tbody>${MP.map((m,i)=>`<tr><td>${T(m)}</td><td class="num">${[3,4,5,7].reduce((a,d)=>a+(rep(d)?rep(d).mp[i]:0),0)}</td></tr>`).join('')}<tr><td><b>${L('Worker-days','أيام العمل')}</b></td><td class="num"><b>${[3,4,5,7].reduce((a,d)=>a+(rep(d)?tot(rep(d)):0),0)}</b></td></tr><tr><td>${L('Crane hours','ساعات الرافعة')}</td><td class="num">${[3,4,5,7].reduce((a,d)=>a+(rep(d)?rep(d).eq[0][2]:0),0)} h</td></tr><tr><td>${L('Hours lost to weather','ساعات ضائعة بسبب الطقس')}</td><td class="num">${[3,4,5,7].reduce((a,d)=>a+(rep(d)?rep(d).lost:0),0)} h</td></tr></tbody></table></section></div>
 <section class="box"><h6>${L('Progress summary · look-ahead','ملخص التقدم · الأسبوع القادم')}</h6><textarea class="ta" rows="3">${L('Floor 07 slab poured; Floor 05 first-fix electrical 70%. Next week: Floor 08 formwork, Floor 06 first-fix.','تم صب بلاطة الطابق ٠٧؛ التمديدات الكهربائية للطابق ٠٥ بنسبة 70٪. الأسبوع القادم: قوالب الطابق ٠٨.')}</textarea></section></div>`}
/* ---- detail ---- */
function flow(r){const steps=[['draft',L('Prepared','أُعد'),'hafiz'],['review',L('Manager review','مراجعة المدير'),'ali'],['submitted',L('Consultant','الاستشاري'),'shamsi'],['affirmed',L('Affirmed','معتمد'),'shamsi']];const i=Math.max(0,SORD.indexOf(r.st==='returned'?'review':r.st));const map={draft:0,review:1,returned:1,submitted:2,affirmed:3};const ci=map[r.st];
 return `<div class="flow">${steps.map((s,j)=>`<div class="fs${j<ci||r.st==='affirmed'?' done':j===ci?' cur':''}"><span>${j<ci||r.st==='affirmed'?'<i class="ti ti-check"></i>':j+1}</span><b>${s[1]}</b><small>${PPL[s[2]][0]}</small></div>`).join('<i class="fl2"></i>')}</div>`}
function acts(r){const R=V.role;const b=[];
 if(R==='ctr'&&(r.st==='draft'||r.st==='returned'))b.push(`<button class="cb pri" data-do="review"><i class="ti ti-send"></i>${L('Send to manager','إرسال للمدير')}</button>`);
 if(R==='pm'&&r.st==='review')b.push(`<button class="cb" data-do="returned"><i class="ti ti-arrow-back-up"></i>${L('Return','إرجاع')}</button><button class="cb pri" data-do="submitted"><i class="ti ti-signature"></i>${L('Submit to consultant ✍','تقديم للاستشاري ✍')}</button>`);
 if(R==='cns'&&r.st==='submitted')b.push(`<button class="cb" data-act="ask"><i class="ti ti-message-question"></i>${L('Ask a question','طرح سؤال')}</button><button class="cb pri" data-do="affirmed"><i class="ti ti-signature"></i>${L('Affirm ✍','اعتماد ✍')}</button>`);
 return b.join('')||`<span style="font-size:12.5px;color:var(--ui-muted)">${r.st==='affirmed'?L('Affirmed — sealed PDF issued.','معتمد — تم إصدار PDF مختوم.'):L('Waiting for the next person.','بانتظار الشخص التالي.')}</span>`}
function detail(){const r=V.open==='w1'?W1:V.open==='h1'?HSE1:reps.find(x=>x.id===V.open);if(!r)return '';const t=TPL[r.tpl];
 const body=r.tpl==='weekly'?weekly():r.tpl==='hse'?`<div class="kp"><div style="--c:var(--tone-green-solid)"><i class="ti ti-check"></i><b>${r.pass}</b><span>Pass</span></div><div style="--c:var(--tone-red-solid)"><i class="ti ti-x"></i><b>${r.fail}</b><span>Fail → ${r.fail} snags</span></div></div><section class="box"><h6>${L('Failed items','البنود الراسبة')}</h6>${[['Missing guardrail at Floor 07 slab edge','حاجز مفقود عند حافة بلاطة الطابق ٠٧'],['Extension cable damaged – Floor 05','كابل تمديد تالف – الطابق ٠٥'],['Fire extinguisher expired – Level B1','طفاية حريق منتهية – القبو ١']].map(x=>`<div class="fli"><i class="ti ti-x"></i>${T(x)}<span class="ty" style="margin-inline-start:auto;background:var(--tone-red-tint);color:var(--tone-red-fg)"><i class="ti ti-alert-triangle"></i>${L('Snag raised','أُنشئت ملاحظة')}</span></div>`).join('')}</section>`:
 `${kpis(r)}<div class="g2c"><section class="box"><h6>${L('Manpower','العمالة')}</h6>${MP.map((m,i)=>`<div class="mpr"><span>${T(m)}</span><i><em style="width:${r.mp[i]/30*100}%"></em></i><b class="num">${r.mp[i]}</b></div>`).join('')}<div class="mpr tot"><span>${L('Total','الإجمالي')}</span><i></i><b class="num">${tot(r)}</b></div></section><section class="box"><h6>${L('Equipment','المعدات')}</h6>${r.eq.map(e=>`<div class="eqr"><span>${T(e[0])}</span>${e[1]?`<span class="ty" style="background:var(--tone-green-tint);color:var(--tone-green-fg)"><i class="ti ti-check"></i>${e[2]} h</span>`:`<span class="ty" style="background:var(--tone-gray-tint);color:var(--ui-muted)">${L('Idle','متوقف')}</span>`}</div>`).join('')}</section><section class="box"><h6>${L('Work done','الأعمال المنجزة')}</h6>${(r.work||[['Floor 05 first-fix electrical','التمديدات الكهربائية — الطابق ٠٥']]).map(w=>`<div class="fli" style="color:var(--ui-text)"><i class="ti ti-check" style="color:var(--tone-green-solid)"></i>${T(w)}</div>`).join('')}</section><section class="box"><h6>${L('Issues & delays','المشكلات والتأخير')}</h6>${r.iss.length?r.iss.map(x=>`<div class="fli" style="background:var(--tone-amber-tint);color:var(--tone-amber-fg)"><i class="ti ti-clock"></i>${T(x)}</div>`).join(''):`<div style="font-size:13px;color:var(--ui-muted)">${L('None reported','لم يُبلّغ عن شيء')}</div>`}</section></div>`;
 return `<div class="scrim" data-close="1"><div class="drw rdrw" data-stop><div class="dh" style="padding-bottom:12px"><div class="t1"><span class="ty" style="background:var(--tone-${t.tone}-tint);color:var(--tone-${t.tone}-fg)"><i class="ti ${t.ic}"></i>${L(t.en,t.ar)}</span><span class="num" style="font-size:12.5px;font-weight:700;color:var(--ui-muted)">${r.no}</span>${stp(r.st)}${age(r.wk)}<span class="segv" style="margin-inline-start:auto" title="demo">${[['ctr',L('Site Engineer','مهندس الموقع')],['pm',L('Contractor PM','مدير المقاول')],['cns',L('Consultant','الاستشاري')]].map(x=>`<button class="${V.role===x[0]?'on':''}" data-role="${x[0]}">${x[1]}</button>`).join('')}</span><button class="cb ter sm ic" data-close="1"><i class="ti ti-x"></i></button></div><h2>${r.range?L('Week 32 · 3–7 Aug 2025','الأسبوع 32 · 3–7 أغسطس 2025'):fd(r.d)}</h2>${flow(r)}<div class="acts">${acts(r)}<span style="flex:1"></span><button class="cb" data-act="pdf"><i class="ti ti-file-download"></i>${L('Export PDF','تصدير PDF')}</button></div>${V.ask?`<div class="actf" style="margin-top:10px"><h4><i class="ti ti-message-question"></i>${L('Ask the contractor','اسأل المقاول')}</h4><textarea id="rq" rows="2" placeholder="${L('e.g. Please confirm helper count — gate log shows 22.','مثال: يرجى تأكيد عدد المساعدين')}"></textarea><div class="row"><button class="cb" data-act="ask">${L('Cancel','إلغاء')}</button><button class="cb pri" data-act="sendq"><i class="ti ti-send"></i>${L('Send & return','إرسال وإرجاع')}</button></div></div>`:''}</div><div class="db">${body}</div></div></div>`}
function pdf(){if(!V.pdf)return '';const r=reps.find(x=>x.id===V.open)||rep(7);
 return `<div class="scrim" data-act="pdfx" style="z-index:95"><div class="a4" data-stop><div class="ph"><span class="lg">R</span><div><b>${L('Daily Site Report','تقرير الموقع اليومي')} / تقرير الموقع اليومي</b><small>Dubai Marina Tower – Phase 2 · TMC Constructions</small></div><div style="margin-inline-start:auto;text-align:end"><b class="num">${r.no}</b><small>${fd(r.d)}</small></div></div><table class="pt"><tr><th>${L('Weather','الطقس')}</th><td>${r.w==='dust'?'Sunny, dust later':'Sunny'} · ${r.temp}°C · ${r.lost} h lost</td></tr></table><table class="pt"><tr><th>${L('Trade','الفئة')}</th><th>${L('Count','العدد')}</th></tr>${MP.map((m,i)=>`<tr><td>${T(m)}</td><td class="num">${r.mp[i]}</td></tr>`).join('')}<tr><td><b>${L('Total','الإجمالي')}</b></td><td class="num"><b>${tot(r)}</b></td></tr></table><table class="pt"><tr><th>${L('Equipment','المعدات')}</th><th>${L('Hours','الساعات')}</th></tr>${r.eq.map(e=>`<tr><td>${T(e[0])}</td><td class="num">${e[2]}</td></tr>`).join('')}</table><div class="pgal">${[1,2,3].map(i=>`<div><span></span><small>${L('Photo','صورة')} ${i} · 10:${10+i*7}</small></div>`).join('')}</div><div class="sig">${[['Prepared','hafiz'],['Reviewed','ali'],['Affirmed','shamsi']].map(s=>`<div><small>${s[0]}</small><b>${PPL[s[1]][0]}</b><em>✍ ${L('signed','موقّع')}</em></div>`).join('')}</div><div class="pf"><span class="qr"></span><small>${L('Verify at rabaed.com/v/','تحقق عبر rabaed.com/v/')}${r.no}</small><span style="margin-inline-start:auto">Page 1 of 1</span></div><div class="pbar2"><button class="cb" data-act="pdfx">${L('Close','إغلاق')}</button><button class="cb pri" data-act="dl"><i class="ti ti-download"></i>${L('Download PDF','تنزيل PDF')}</button></div></div></div>`}
/* ---- create ---- */
const SECS=[['ti-info-circle','General','عام'],['ti-sun','Weather','الطقس'],['ti-users','Manpower','العمالة'],['ti-tool','Equipment','المعدات'],['ti-truck','Materials','المواد'],['ti-checklist','Work done','الأعمال'],['ti-alert-triangle','Issues & safety','المشكلات والسلامة'],['ti-camera','Photos','الصور']];
function create(){if(!V.form)return '';const f=V.form;const sec=V.step;
 let body='';
 if(sec===0)body=`<div class="fg2"><label>${L('Report date','تاريخ التقرير')}<input value="${fd(f.d)}" readonly></label><label>${L('Shift','الوردية')}<select><option>${L('Day','نهاري')}</option><option>${L('Night','ليلي')}</option></select></label><label style="grid-column:1/-1">${L('Locations','المواقع')}<span class="chs">${['Floor 05','Floor 07','Roof'].map((x,i)=>`<button class="${i<2?'on':''}">${x}</button>`).join('')}</span></label></div>`;
 if(sec===1)body=`<div class="wx">${[['sun','ti-sun',L('Sunny','مشمس')],['cloud','ti-cloud',L('Cloudy','غائم')],['dust','ti-wind',L('Dust storm','عاصفة ترابية')],['rain','ti-cloud-rain',L('Rain','مطر')]].map(w=>`<button class="${f.w===w[0]?'on':''}" data-wx="${w[0]}"><i class="ti ${w[1]}"></i>${w[2]}</button>`).join('')}</div><div class="fg2"><label>${L('Temperature','الحرارة')} °C<input type="number" value="${f.temp}"></label><label>${L('Hours lost to weather','ساعات ضائعة')}<input type="number" value="${f.lost}"></label></div>`;
 if(sec===2)body=`<div class="okb" style="background:var(--tone-blue-tint);color:var(--tone-blue-fg)"><i class="ti ti-copy"></i>${L('Manpower changes little day to day.','العمالة تتغير قليلًا يوميًا.')}<button class="cb sm" data-act="copy" style="margin-inline-start:auto">${L('Copy from yesterday','نسخ من الأمس')}</button></div>${f.mp.map((m,i)=>`<div class="mrow"><div><b>${esc(m[0])}</b><small>${esc(m[1])}</small></div><div class="stepr"><button data-st="${i}:-1">−</button><span class="num">${m[2]}</span><button data-st="${i}:1">+</button></div><button class="cb ter sm ic" data-rm="${i}"><i class="ti ti-trash"></i></button></div>`).join('')}<button class="cb" data-act="addrow"><i class="ti ti-plus"></i>${L('Add row','إضافة صف')}</button><div class="mrow tot"><b>${L('Total','الإجمالي')}</b><b class="num">${f.mp.reduce((a,m)=>a+m[2],0)}</b></div>`;
 if(sec>2)body=`<div class="okb" style="background:var(--ui-surface-2);color:var(--ui-muted)"><i class="ti ti-forms"></i>${L('Fields for this section come from the template.','حقول هذا القسم تأتي من القالب.')}</div><textarea class="ta" rows="4" placeholder="${L('Notes…','ملاحظات…')}"></textarea>${sec===7?`<div class="gal2">${[1,2].map(i=>`<div class="ph2"><i class="ti ti-photo"></i><small>10:${14+i*9} · GPS ✓</small></div>`).join('')}<button class="phadd"><i class="ti ti-camera"></i>${L('Take photo','التقاط صورة')}</button></div>`:''}`;
 const done=f.done.length;
 return `<div class="scrim" data-close="1"><div class="cmod" data-stop><div class="ch"><div><b>${L('New Daily Site Report','تقرير يومي جديد')}</b><small>${fd(f.d)} · ${L('template','القالب')} v2 · <span style="color:var(--tone-green-fg)"><i class="ti ti-check"></i> ${L('Saved 10:42','حُفظ 10:42')}</span></small></div><button class="cb ter sm ic" data-close="1" style="margin-inline-start:auto"><i class="ti ti-x"></i></button></div><div class="cbod"><nav class="snav"><div class="prg"><b>${done} ${L('of','من')} ${SECS.length}</b> ${L('sections done','أقسام مكتملة')}<i><em style="width:${done/SECS.length*100}%"></em></i></div>${SECS.map((s,i)=>`<button class="${i===sec?'on':''}${f.done.includes(i)?' dn':''}" data-sec="${i}"><i class="ti ${f.done.includes(i)?'ti-circle-check':s[0]}"></i>${L(s[1],s[2])}</button>`).join('')}</nav><div class="sbody"><h3><i class="ti ${SECS[sec][0]}"></i>${L(SECS[sec][1],SECS[sec][2])}</h3>${body}</div></div><div class="cf2"><button class="cb" data-act="prev"${sec?'':' disabled'}>${L('Previous','السابق')}</button><span style="flex:1"></span><button class="cb" data-act="draft">${L('Save as draft','حفظ كمسودة')}</button>${sec<SECS.length-1?`<button class="cb pri" data-act="next">${L('Next','التالي')}</button>`:`<button class="cb pri" data-act="send"><i class="ti ti-send"></i>${L('Send to manager','إرسال للمدير')}</button>`}</div></div></div>`}
/* ---- page ---- */
function view(){const t=TPL[V.tpl];const head=`<div class="rhd"><div><h1>${L('Reports','التقارير')}</h1><p>${L('Site reports built from templates · Daily · Weekly · Monthly','تقارير الموقع من القوالب · يومي · أسبوعي · شهري')}</p></div><span style="flex:1"></span><span class="segv" title="${L('Design option','خيار التصميم')}">${[['A',L('A · Calendar','أ · التقويم')],['B',L('B · Register','ب · السجل')],['C',L('C · Feed','ج · الموجز')]].map(o=>`<button class="${V.opt===o[0]?'on':''}" data-opt="${o[0]}">${o[1]}</button>`).join('')}</span><button class="cb" data-act="wk"><i class="ti ti-chart-bar"></i>${L('Weekly from dailies','الأسبوعي من اليوميات')}</button><button class="cb pri" data-new="today"><i class="ti ti-plus"></i>${L('New ','جديد: ')}${L(t.en,t.ar)}</button></div>`;
 let main='';
 if(V.opt==='A')main=`<div class="la"><aside class="card rrail">${tplRail()}</aside><section class="card" style="padding:14px">${strip()}${V.tpl==='daily'?cal():list()}</section><aside class="card">${V.tpl==='daily'?dayPrev():`<div class="rprev"><p>${L(t.d[0],t.d[1])}</p></div>`}</aside></div>`;
 if(V.opt==='B')main=`${tplTabs()}${strip()}${list()}`;
 if(V.opt==='C')main=`${tplCards()}<div class="lc2"><div>${feed()}</div><aside class="card" style="padding:14px"><h6 class="h6">${L('Manpower · this week','العمالة · هذا الأسبوع')}</h6>${bars()}</aside></div>`;
 return head+main+detail()+create()+pdf()+(V.toast?`<div class="toast"><i class="ti ti-circle-check"></i>${V.toast}</div>`:'')}
function bind(root,R){let tt;const flash=m=>{V.toast=m;R();clearTimeout(tt);tt=setTimeout(()=>{V.toast=null;R()},2200)};
 root.addEventListener('click',e=>{const b=e.target.closest('[data-opt],[data-tpl],[data-day],[data-open],[data-new],[data-close],[data-role],[data-do],[data-act],[data-sec],[data-wx],[data-st],[data-rm]');if(!b||b.closest('.hd,.tabs,.sb'))return;const d=b.dataset;
  if(d.close!==undefined){if(e.target.closest('[data-stop]')&&!b.closest('button'))return;V.open=null;V.form=null;V.ask=false;return R()}
  if(d.opt){V.opt=d.opt;return R()}if(d.tpl){V.tpl=d.tpl;return R()}if(d.day){V.sel=+d.day;return R()}
  if(d.open){V.open=d.open;V.ask=false;V.role=reps.find(r=>r.id===d.open)?.st==='submitted'?'cns':V.role;return R()}
  if(d.new){const dd=d.new==='today'?31:+d.new;V.open=null;V.form={d:dd,w:'sun',temp:44,lost:0,mp:MP.map((m,i)=>[m[0],m[1],0]),done:[]};V.step=0;return R()}
  if(d.role){V.role=d.role;V.ask=false;return R()}
  if(d.do){const r=V.open==='w1'?W1:V.open==='h1'?HSE1:reps.find(x=>x.id===V.open);r.st=d.do;r.wk=d.do==='affirmed'?0:1;const x=days[r.d-1];if(x)x.st=d.do;return flash(L(`${r.no} → ${ST[d.do][0]}`,`${r.no} ← ${ST[d.do][1]}`))}
  if(d.sec){V.form.done=[...new Set([...V.form.done,V.step])];V.step=+d.sec;return R()}
  if(d.wx){V.form.w=d.wx;return R()}
  if(d.st){const [i,v]=d.st.split(':').map(Number);V.form.mp[i][2]=Math.max(0,V.form.mp[i][2]+v);return R()}
  if(d.rm!==undefined){V.form.mp.splice(+d.rm,1);return R()}
  const a=d.act;
  if(a==='ask'){V.ask=!V.ask;return R()}
  if(a==='sendq'){const r=reps.find(x=>x.id===V.open);r.st='returned';V.ask=false;return flash(L('Question sent — report returned to contractor','أُرسل السؤال — أُعيد التقرير للمقاول'))}
  if(a==='pdf'){V.pdf=true;return R()}if(a==='pdfx'){if(e.target.closest('[data-stop]')&&!b.closest('button'))return;V.pdf=false;return R()}if(a==='dl')return flash(L('PDF downloaded','تم تنزيل PDF'));
  if(a==='wk'){V.open='w1';return R()}if(a==='ign'){V.ign=true;return R()}
  if(a==='copy'){const y=rep(28)||rep(27);V.form.mp.forEach((m,i)=>m[2]=y.mp[i]);return flash(L('Copied from yesterday','تم النسخ من الأمس'))}
  if(a==='addrow'){V.form.mp.push(['Carpenters','نجّارون',0]);return R()}
  if(a==='next'){V.form.done=[...new Set([...V.form.done,V.step])];V.step++;return R()}if(a==='prev'){V.step--;return R()}
  if(a==='draft'){V.form=null;return flash(L('Saved as draft','حُفظ كمسودة'))}
  if(a==='send'){const f=V.form;const x=days[f.d-1];x.st='review';reps.push({id:'r'+f.d,tpl:'daily',no:'TWR-TMC-DSR-0'+(240+f.d),d:f.d,st:'review',by:'Hafiz Hamdan',wk:0,mp:f.mp.slice(0,4).map(m=>m[2]),eq:rep(7).eq,temp:f.temp,w:f.w,lost:f.lost,inc:0,iss:[]});V.form=null;V.sel=f.d;return flash(L('Sent to Ali Sonour (Contractor PM)','أُرسل إلى علي سنور'))}
 });
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){V.open=null;V.form=null;V.pdf=false;R()}});
}
window.RP2={V,view,bind};
})();
