// Snag List — sample data. Exposes window.SD.
(function(){
const STG={open:{en:'Open',ar:'مفتوح',tone:'orange'},prog:{en:'In Progress',ar:'قيد التنفيذ',tone:'blue'},hold:{en:'On Hold',ar:'معلّق',tone:'gray'},res:{en:'Resolved',ar:'تم الحل',tone:'violet'},closed:{en:'Closed',ar:'مغلق',tone:'green'}};
const SORDER=['open','prog','hold','res','closed'];
const TYP={snag:{en:'Snag',ar:'ملاحظة',pl:['Snags','الملاحظات'],ic:'ti-alert-triangle',tone:'red',code:'SNG'},cmt:{en:'Comment',ar:'تعليق',pl:['Comments','التعليقات'],ic:'ti-message-circle',tone:'blue',code:'CMT'},qst:{en:'Question',ar:'سؤال',pl:['Questions','الأسئلة'],ic:'ti-help-circle',tone:'violet',code:'QST'}};
const TR={EL:['Electrical','كهرباء','cyan'],AR:['Finishes','تشطيبات','violet'],FS:['Firestopping','عزل الحريق','orange'],PL:['Plumbing','سباكة','blue'],CV:['Civil','مدني','amber']};
const CO={tmc:['TMC Constructions','تي إم سي للمقاولات','#f8552f','TMC','Contractor','مقاول'],gdl:['Gulf Dryliners','الخليج للألواح الجافة','#7a5af0','GDL','Subcontractor · TMC','مقاول باطن · TMC'],fss:['FireSafe Systems','فاير سيف للأنظمة','#e98b45','FSS','Contractor','مقاول'],dcl:['Design Consultants LLC','ديزاين للاستشارات','#3d6db5','DCL','Consultant','استشاري']};
const PPL={nasser:['Nasser Al Kaabi','ناصر الكعبي','tmc','#e98b45'],ahmed:['Ahmed bin Said','أحمد بن سعيد','tmc','#3d6db5'],omar:['Omar Al Blooshi','عمر البلوشي','gdl','#1fae66'],khalid:['Khalid Al Dhaheri','خالد الظاهري','fss','#6b5ad8'],shamsi:['Mohammed Al Shamsi','محمد الشامسي','dcl','#b5455a'],sara:['Sara Al Mansoori','سارة المنصوري','dcl','#7a5c3a']};
const ROLES={tmc:{en:'Contractor · TMC Constructions',ar:'مقاول · تي إم سي',co:'tmc',me:'nasser',sees:['tmc','gdl'],can:['start','hold','resolve']},dcl:{en:'Consultant · Design Consultants',ar:'استشاري · ديزاين',co:'dcl',me:'shamsi',sees:null,can:['close','reopen','hold']},admin:{en:'Project Admin',ar:'مسؤول المشروع',co:'dcl',me:'sara',sees:null,can:['start','hold','resolve','close','reopen']}};
const LOCS={'02':['Floor 02','الطابق ٠٢'],'01':['Floor 01','الطابق ٠١'],'03':['Floor 03','الطابق ٠٣'],gf:['Ground Floor','الطابق الأرضي'],rf:['Roof','السطح']};
const SPACES=[['Riser 01','الرايزر ٠١'],['Corridor','الممر'],['Apt 201','شقة 201'],['Apt 203','شقة 203'],['Lift lobby','بهو المصاعد'],['Plant room','غرفة المعدات'],['Apt 105','شقة 105']];
const SRC={
 mar041:{kind:'sub',no:'TWR-TMC-EL-MAR-041',t:['Lighting Fixtures','وحدات الإنارة'],code:'B',by:'shamsi'},
 sar012:{kind:'sub',no:'TWR-TMC-EL-SAR-012',t:['Cable Containment Shop Drawing','مخطط حوامل الكابلات'],code:'B',by:'sara'},
 mar038:{kind:'sub',no:'TWR-GDL-AR-MAR-038',t:['Gypsum Board System','نظام ألواح الجبس'],code:'C',by:'shamsi'},
 ir045:{kind:'insp',no:'TWR-TMC-EL-IR-045',t:['First-fix electrical — Floor 02','التمديدات الكهربائية الأولى — الطابق ٠٢'],failed:['Earthing continuity','استمرارية التأريض'],by:'sara'},
 ir051:{kind:'insp',no:'TWR-GDL-AR-IR-051',t:['Ceiling boarding — Floor 01','ألواح السقف — الطابق ٠١'],failed:['Board fixing centres','مسافات تثبيت الألواح'],by:'shamsi'},
 dsr:{kind:'dsr',no:'DSR-2026-09-18',t:['Daily Site Report · 18 Sep','تقرير الموقع اليومي · 18 سبتمبر'],by:'sara'}
};
const I=[];let n=0;
const add=(o)=>{n++;I.push(Object.assign({id:'s'+n,photos:0,after:null,pin:null,chat:[],internal:[],d:n},o))};
// comments from MAR-041 (5: 3 closed)
add({no:'TWR-DCL-EL-CMT-003',type:'cmt',t:['Provide IP65 certificate for corridor fittings','تقديم شهادة IP65 لوحدات إنارة الممر'],q:['Corridor fittings must be IP65 — submit the test certificate from the manufacturer.','يجب أن تكون وحدات الممر بدرجة IP65 — قدّم شهادة الاختبار من المصنّع.'],tr:'EL',f:'02',sp:1,co:'tmc',who:'nasser',stage:'res',wk:1,src:'mar041',after:{note:['IP65 certificate from Thorn uploaded (ref TH-IP65-2291).','تم رفع شهادة IP65 من Thorn (مرجع TH-IP65-2291).'],photos:0,files:1}});
add({no:'TWR-DCL-EL-CMT-004',type:'cmt',t:['Update luminaire schedule to Rev C','تحديث جدول وحدات الإنارة إلى Rev C'],q:['Schedule still shows Rev B fittings for Level 02. Update to the Rev C lighting layout.','لا يزال الجدول يعرض وحدات Rev B للطابق ٠٢. حدّثه وفق مخطط الإنارة Rev C.'],tr:'EL',f:'02',sp:1,co:'tmc',who:'ahmed',stage:'open',wk:2,src:'mar041'});
add({no:'TWR-DCL-EL-CMT-005',type:'cmt',t:['Confirm emergency lighting duration (3h)','تأكيد مدة إنارة الطوارئ (3 ساعات)'],q:['Confirm emergency packs provide 3 hours duration per NFPA 101.','أكّد أن وحدات الطوارئ توفر 3 ساعات وفق NFPA 101.'],tr:'EL',f:'02',sp:4,co:'tmc',who:'nasser',stage:'closed',wk:1,src:'mar041'});
add({no:'TWR-DCL-EL-CMT-006',type:'cmt',t:['Add photometric calc for lift lobby','إضافة حساب الإضاءة لبهو المصاعد'],q:['Provide photometric calculation showing 200 lux at lift lobby floor level.','قدّم حساب الإضاءة الذي يبيّن 200 لوكس عند أرضية بهو المصاعد.'],tr:'EL',f:'02',sp:4,co:'tmc',who:'ahmed',stage:'closed',wk:1,src:'mar041'});
add({no:'TWR-DCL-EL-CMT-007',type:'cmt',t:['Match finish colour to ID sample','مطابقة لون التشطيب لعينة التصميم الداخلي'],q:['Trim finish to match approved ID sample RAL 9003.','يجب أن يطابق لون الإطار عينة التصميم المعتمدة RAL 9003.'],tr:'EL',f:'02',sp:2,co:'tmc',who:'nasser',stage:'closed',wk:1,src:'mar041'});
// named snags
add({no:'TWR-TMC-EL-SNG-014',type:'snag',t:['Cable tray not bonded','حامل الكابلات غير موصول بالتأريض'],desc:['Bonding jumpers missing across 3 tray joints in Riser 01 between L02 and L03. Earth continuity test failed at 1.8 Ω.','وصلات التأريض مفقودة عبر 3 وصلات للحامل في الرايزر ٠١ بين الطابقين ٠٢ و٠٣. رسب اختبار الاستمرارية عند 1.8 أوم.'],tr:'EL',f:'02',sp:0,co:'tmc',who:'nasser',stage:'open',wk:3,photos:2,src:'ir045',pin:[712,520]});
add({no:'TWR-GDL-AR-SNG-015',type:'snag',t:['Ceiling plasterboard – rework needed','ألواح الجبس في السقف – تتطلب إعادة عمل'],desc:['Joints cracked along the corridor; boards fixed at 600 mm centres instead of 400 mm.','تشققات في الوصلات على طول الممر؛ الألواح مثبتة على 600 مم بدلًا من 400 مم.'],tr:'AR',f:'01',sp:1,co:'gdl',who:'omar',stage:'prog',wk:2,photos:3,src:'ir051',pin:[520,400]});
add({no:'TWR-FSS-FS-SNG-016',type:'snag',t:['SVP firestopping – potential rework','عزل حريق أنبوب الصرف – قد يتطلب إعادة عمل'],desc:['Collar looks undersized for 110 mm SVP. Waiting for manufacturer data before re-work.','الطوق يبدو أصغر من المطلوب لأنبوب 110 مم. بانتظار بيانات المصنّع قبل إعادة العمل.'],tr:'FS',f:'02',sp:0,co:'fss',who:'khalid',stage:'hold',wk:1,photos:1,src:'dsr',pin:[730,560]});
// more comments
add({no:'TWR-DCL-EL-CMT-008',type:'cmt',t:['Show tray separation from LV cables','توضيح فصل الحوامل عن كابلات الجهد المنخفض'],q:['Section C–C: show 300 mm separation between power and data trays.','المقطع C–C: وضّح مسافة 300 مم بين حوامل الطاقة والبيانات.'],tr:'EL',f:'03',sp:1,co:'tmc',who:'nasser',stage:'prog',wk:1,src:'sar012'});
add({no:'TWR-DCL-EL-CMT-009',type:'cmt',t:['Add support details at riser penetrations','إضافة تفاصيل الدعامات عند اختراقات الرايزر'],q:['Provide support detail where trays pass through riser slab openings.','قدّم تفصيلة الدعم عند مرور الحوامل عبر فتحات بلاطة الرايزر.'],tr:'EL',f:'03',sp:0,co:'tmc',who:'ahmed',stage:'open',wk:4,src:'sar012'});
add({no:'TWR-DCL-AR-CMT-010',type:'cmt',t:['Acoustic rating missing for party walls','تصنيف العزل الصوتي مفقود للجدران الفاصلة'],q:['Party wall system must achieve Rw 55 — provide test report.','يجب أن يحقق نظام الجدار الفاصل Rw 55 — قدّم تقرير الاختبار.'],tr:'AR',f:'01',sp:6,co:'gdl',who:'omar',stage:'open',wk:2,src:'mar038'});
add({no:'TWR-DCL-AR-CMT-011',type:'cmt',t:['Moisture-resistant board in wet areas','ألواح مقاومة للرطوبة في المناطق الرطبة'],q:['Use MR board in all bathrooms and kitchens.','استخدم ألواح MR في جميع الحمامات والمطابخ.'],tr:'AR',f:'01',sp:6,co:'gdl',who:'omar',stage:'res',wk:1,src:'mar038',after:{note:['Board schedule updated — MR board for all wet areas.','تم تحديث جدول الألواح — ألواح MR لكل المناطق الرطبة.'],photos:0,files:1}});
// questions
add({no:'TWR-TMC-EL-QST-002',type:'qst',t:['Socket height in kitchens — 1100 or 1200?','ارتفاع المقابس في المطابخ — 1100 أم 1200؟'],desc:['ID drawing shows 1100 mm, MEP drawing 1200 mm. Please confirm.','يبين مخطط التصميم الداخلي 1100 مم ومخطط الكهروميكانيك 1200 مم. يرجى التأكيد.'],tr:'EL',f:'02',sp:2,co:'tmc',who:'ahmed',stage:'open',wk:1,src:null});
add({no:'TWR-FSS-FS-QST-001',type:'qst',t:['Approved sealant for PVC pipes?','المانع المعتمد لأنابيب PVC؟'],desc:['Which sealant brand is approved for PVC penetrations at L02?','ما نوع المانع المعتمد لاختراقات PVC في الطابق ٠٢؟'],tr:'FS',f:'02',sp:0,co:'fss',who:'khalid',stage:'prog',wk:1,src:null});
// generated snags
const G=[['EL','Socket outlet loose','مقبس كهربائي غير مثبت','tmc','nasser'],['EL','Missing cable labels','ملصقات الكابلات مفقودة','tmc','ahmed'],['EL','Light fitting misaligned','وحدة إنارة غير مستقيمة','tmc','nasser'],['AR','Paint drips on skirting','قطرات دهان على النعلة','gdl','omar'],['AR','Door frame out of plumb','إطار الباب غير رأسي','gdl','omar'],['PL','Leak at WC connector','تسرب عند وصلة المرحاض','tmc','ahmed'],['FS','Firestopping incomplete at riser','عزل الحريق غير مكتمل عند الرايزر','fss','khalid'],['EL','Conduit not capped','أنبوب التمديد غير مغلق','tmc','nasser'],['AR','Tile lippage over 2 mm','بروز البلاط أكثر من 2 مم','gdl','omar'],['CV','Honeycomb at column base','تعشيش عند قاعدة العمود','tmc','ahmed'],['EL','DB door does not close','باب لوحة التوزيع لا يغلق','tmc','nasser'],['AR','Ceiling access panel missing','لوحة وصول السقف مفقودة','gdl','omar'],['FS','Fire damper access blocked','الوصول لمخمد الحريق مسدود','fss','khalid'],['PL','Floor drain level wrong','منسوب مصرف الأرضية خاطئ','tmc','ahmed'],['EL','Earth bar not labelled','قضيب التأريض غير مُعلَّم','tmc','nasser'],['AR','Scratched glazing — Apt 203','خدش في الزجاج — شقة 203','gdl','omar'],['CV','Slab edge spalling','تقشر حافة البلاطة','tmc','ahmed']];
const st=['open','open','prog','open','res','closed','open','prog','hold','open','closed','prog','open','res','open','open','closed'];
const fls=['02','02','01','03','01','02','02','gf','01','rf','02','01','03','02','02','03','gf'];
const seqs={};
G.forEach((g,i)=>{const co=g[3],k=CO[co][3]+'-'+g[0];seqs[k]=(seqs[k]||16)+1+(i%2);add({no:'TWR-'+k+'-SNG-'+String(seqs[k]).padStart(3,'0'),type:'snag',t:[g[1],g[2]],desc:[g[1]+'. Found during walkdown; fix and upload an after photo.',g[2]+'. تم رصدها أثناء الجولة؛ يرجى الإصلاح ورفع صورة بعد الإصلاح.'],tr:g[0],f:fls[i],sp:i%7,co,who:g[4],stage:st[i],wk:1+(i*3)%5,photos:(i%3)?1+(i%3):0,src:i%4===0?'dsr':null,pin:[160+(i*97)%880,110+(i*61)%560],after:st[i]==='res'?{note:['Fixed and re-checked on site.','تم الإصلاح وإعادة الفحص في الموقع.'],photos:1}:null})});
// sample chat + history for key items
const H=(it)=>{const base=[{a:'create',by:it.src&&SRC[it.src].kind==='sub'?SRC[it.src].by:(it.src==='ir045'||it.src==='ir051')?SRC[it.src].by:'sara',w:it.wk+1}];if(['prog','hold','res','closed'].includes(it.stage))base.push({a:'prog',by:it.who,w:it.wk+0.5});if(it.stage==='hold')base.push({a:'hold',by:it.who,w:it.wk});if(['res','closed'].includes(it.stage))base.push({a:'res',by:it.who,w:it.wk});if(it.stage==='closed')base.push({a:'closed',by:'shamsi',w:it.wk-0.5});return base};
I.forEach(it=>{it.hist=H(it)});
I.find(x=>x.no==='TWR-TMC-EL-SNG-014').chat=[{by:'sara',t:['Earth continuity failed at 1.8 Ω on the L02–L03 run. Please add bonding jumpers at each joint.','رسب اختبار الاستمرارية عند 1.8 أوم على مسار ٠٢–٠٣. يرجى إضافة وصلات تأريض عند كل وصلة.'],w:3},{by:'nasser',t:['Noted — jumpers ordered, install planned for Sunday.','تمت الملاحظة — تم طلب الوصلات والتركيب مخطط يوم الأحد.'],w:2}];
I.find(x=>x.no==='TWR-TMC-EL-SNG-014').internal=[{by:'ahmed',t:['Charge the jumpers to the containment sub — their install.','تُحمّل تكلفة الوصلات على مقاول الحوامل — من تركيبهم.'],w:2}];
I.find(x=>x.no==='TWR-DCL-EL-CMT-004').chat=[{by:'ahmed',t:['Rev C schedule is with the supplier, expect it next week.','جدول Rev C لدى المورّد، متوقع الأسبوع القادم.'],w:1}];
window.SD={STG,SORDER,TYP,TR,CO,PPL,ROLES,LOCS,SPACES,SRC,I};
})();
