// Snag List — mobile (one-handed).
(function(){
const S=RS.S;try{Object.assign(S,JSON.parse(localStorage.getItem('rb-shell-v1')||'{}'))}catch(e){}
const {STG,SORDER,TYP,TR,CO,PPL,LOCS,SPACES,SRC,I}=SD;const {L,T,ty,stp,trc,cdb,age,av,loc,srcShort,visible,esc}=SN;
const M={scr:'list',type:'all',st:new Set(),mine:false,sheet:false,det:null,flow:null,toast:null,sw:null};
const ROLE='tmc';
const ls=()=>I.filter(i=>visible(i,ROLE)&&(M.type==='all'||i.type===M.type)&&(!M.st.size||M.st.has(i.stage))&&(!M.mine||i.who==='nasser')).sort((a,b)=>SORDER.indexOf(a.stage)-SORDER.indexOf(b.stage)||b.wk-a.wk);
const photo=(it,h)=>`<div class="sm-ph" style="height:${h}px">${it.img?`<img src="${it.img}" alt="">`:`<i class="ti ${it.photos?'ti-photo':'ti-photo-off'}"></i>${it.photos?`<span>${it.photos}</span>`:''}`}</div>`;
function card(it){const can=['open','prog','hold'].includes(it.stage);return `<div class="sm-sw" data-sw="${it.id}">${can?`<div class="sm-acts"><button data-mres="${it.id}" style="background:var(--tone-violet-solid)"><i class="ti ti-circle-check"></i>${L('Resolve','حل')}</button><button data-mhold="${it.id}" style="background:var(--tone-gray-solid)"><i class="ti ti-player-pause"></i>${L('Hold','تعليق')}</button></div>`:''}<div class="sm-card" data-mopen="${it.id}" style="${M.sw===it.id?'transform:translateX(var(--swx))':''}">${photo(it,86)}<div class="tx"><div class="r1"><i class="ti ${TYP[it.type].ic}" style="color:var(--tone-${TYP[it.type].tone}-solid)"></i><span class="num">${it.no.replace('TWR-','')}</span></div><b>${T(it.t)}</b><div class="r2">${stp(it.stage)}${age(it.wk)}</div><small>${loc(it)}</small></div></div></div>`}
function list(){const a=ls();return `<div class="sm-hd"><button class="m-btn bk"><i class="ti ti-arrow-left"></i></button><div><b>${L('Snag List','قائمة الملاحظات')}</b><small>${L('Tower 1 · TMC Constructions','البرج ١ · تي إم سي')}</small></div><button class="m-btn" data-m="filters"><i class="ti ti-adjustments-horizontal"></i>${M.st.size+(M.mine?1:0)?`<span class="n">${M.st.size+(M.mine?1:0)}</span>`:''}</button></div>
 <div class="m-chips" style="padding-top:4px">${['all','snag','cmt','qst'].map(k=>`<button class="m-chip${M.type===k?' on':''}" data-mt="${k}">${k==='all'?L('All','الكل'):`<i class="ti ${TYP[k].ic}"></i>${L(TYP[k].pl[0],TYP[k].pl[1])}`}</button>`).join('')}<button class="m-chip${M.mine?' on':''}" data-m="mine"><i class="ti ti-user-circle"></i>${L('Mine','لي')}</button></div>
 <div class="sm-hint"><i class="ti ti-arrow-back-up"></i>${L('Swipe a card to Resolve or Hold','اسحب البطاقة للحل أو التعليق')}</div>
 <div class="sm-list">${a.map(card).join('')||`<div class="empty2" style="border:0"><span class="ic"><i class="ti ti-circle-check"></i></span><h2>${L('No snags. Nice work.','لا توجد ملاحظات. عمل رائع.')}</h2></div>`}</div>
 <button class="m-fab" data-m="new" style="bottom:34px"><i class="ti ti-plus"></i></button>
 ${M.sheet?`<div class="sm-scrim" data-m="closesheet"></div><div class="m-sheet" style="height:430px"><div class="m-grab" data-m="closesheet"><i></i></div><div class="m-sh-hd"><b>${L('Filters','التصفية')}</b></div><div class="m-body"><div class="m-fld"><label>${L('Stage','المرحلة')}</label><div class="m-tr">${SORDER.map(k=>`<button class="${M.st.has(k)?'on':''}" data-mst="${k}"><i style="border-radius:50%;background:var(--tone-${STG[k].tone}-solid)"></i>${L(STG[k].en,STG[k].ar)}</button>`).join('')}</div></div><label style="display:flex;align-items:center;gap:10px;font-size:15px;font-weight:600;min-height:48px" data-m="mine"><span class="swc${M.mine?' on':''}" style="width:44px;height:26px;border-radius:13px"></span>${L('Assigned to me','مسند إليّ')}</label><button class="m-big pri" data-m="closesheet">${L(`Show ${a.length} items`,`عرض ${a.length} عنصر`)}</button></div></div>`:''}`}
function detail(){const it=I.find(x=>x.id===M.det);const s=it.src&&SRC[it.src];const can=['open','prog','hold'].includes(it.stage);
 return `<div class="sm-hd"><button class="m-btn bk" data-m="back"><i class="ti ti-arrow-left"></i></button><div><small class="num" style="font-weight:700">${it.no}</small></div><span></span></div><div class="sm-det">
 ${photo(it,190)}<div class="row">${ty(it.type)}${stp(it.stage)}${age(it.wk,1)}</div><h2>${T(it.t)}</h2>${it.desc?`<p>${T(it.desc)}</p>`:''}
 <div class="m-kv"><span>${L('Trade','التخصص')}</span><b>${trc(it.tr)}</b><span>${L('Location','الموقع')}</span><b>${loc(it)}</b><span>${L('Assigned','مسند')}</span><b>${av(it.who,22)}${T(PPL[it.who])}</b></div>
 ${s?`<div class="box" style="padding:12px"><h6><i class="ti ti-link"></i>${L('Raised from','المصدر')}</h6><div style="display:flex;align-items:center;gap:8px"><span class="num" style="font-size:12.5px;font-weight:700;color:var(--tone-blue-fg)">${srcShort(s)}</span><span style="flex:1;font-size:13.5px">${T(s.t)}</span>${s.code?cdb(s.code):''}</div>${it.q?`<blockquote class="quote">“${T(it.q)}”</blockquote>`:s.failed?`<div class="failed"><i class="ti ti-x"></i>${T(s.failed)}</div>`:''}</div>`:''}
 ${it.after?`<div class="fnote">${T(it.after.note)}</div>`:''}</div>
 ${can?`<div class="m-drop"><button class="m-big sec" data-mhold="${it.id}"><i class="ti ti-player-pause"></i></button><button class="m-big pri" data-mres="${it.id}" style="flex:1"><i class="ti ti-circle-check"></i>${L('Mark Resolved','تحديد كمحلول')}</button></div>`:`<div class="m-drop"><div class="m-big sec" style="flex:1;cursor:default">${it.stage==='res'?L('Waiting for consultant','بانتظار الاستشاري'):L('Closed','مغلقة')}</div></div>`}`}
const STEPS=['cam','pin','title','assign'];
function flow(){const f=M.flow,i=STEPS.indexOf(f.step);const dots=`<div class="sm-steps">${STEPS.map((s,j)=>`<i class="${j<=i?'on':''}"></i>`).join('')}</div>`;const draft=`<span class="sm-draft"><i class="ti ti-check"></i>${L('Draft saved','تم حفظ المسودة')}</span>`;
 if(f.step==='cam')return `<div class="m-cam"><div class="vf">${f.shot?`<img src="${f.shot}" alt="">`:`<div class="grid"></div><div class="lbl"><i class="ti ti-camera"></i>${L('Point at the defect','وجّه الكاميرا نحو العيب')}</div>`}<div class="top"><button data-m="cancelflow"><i class="ti ti-x"></i></button><span>${L('New snag · 1 of 4','ملاحظة جديدة · 1 من 4')}</span><button><i class="ti ti-bolt"></i></button></div></div><div class="bar"><button data-m="lib"><span class="lib"><i class="ti ti-photo"></i></span>${L('Library','المعرض')}</button><button data-m="shoot"><span class="shut"></span></button><button data-m="next"><span class="lib"><i class="ti ti-arrow-right"></i></span>${f.shot?L('Next','التالي'):L('Skip','تخطي')}</button></div></div>`;
 const hd=(t)=>`<div class="sm-hd"><button class="m-btn bk" data-m="prev"><i class="ti ti-arrow-left"></i></button><div><b>${t}</b>${dots}</div>${draft}</div>`;
 if(f.step==='pin')return `${hd(L('Where is it?','أين هي؟'))}<div class="sm-det"><div class="m-tr">${Object.keys(LOCS).map(k=>`<button class="${f.f===k?'on':''}" data-mf="${k}">${L(LOCS[k][0],LOCS[k][1])}</button>`).join('')}</div><div class="sm-plan" data-mpin="1">${PD.drawing({no:'A-102',en:'Plan',rev:'C',date:''})}${f.pin?`<span class="mp" style="left:${f.pin[0]}%;top:${f.pin[1]}%"></span>`:''}</div><small style="color:var(--ui-muted);text-align:center">${f.pin?L('Pinned. Tap again to move.','تم التثبيت. انقر مجددًا للنقل.'):L('Tap the plan to pin it.','انقر على المخطط للتثبيت.')}</small></div><div class="m-drop"><button class="m-big pri" data-m="next" style="flex:1">${L('Next','التالي')}</button></div>`;
 if(f.step==='title')return `${hd(L('What’s wrong?','ما المشكلة؟'))}<div class="sm-det">${f.shot?`<div class="sm-ph" style="height:120px"><img src="${f.shot}" alt=""></div>`:''}<div class="m-fld"><input id="mt" class="${f.err?'err':''}" value="${esc(f.title)}" placeholder="${L('e.g. Cable tray not bonded','مثال: حامل الكابلات غير موصول')}"></div><div class="m-chips" style="padding:0;flex-wrap:wrap">${['Cable tray not bonded','Socket outlet loose','Missing cable labels'].map(s=>`<button class="m-chip" data-msug="${s}">${s}</button>`).join('')}</div><div class="m-fld"><label>${L('Trade','التخصص')}</label><div class="m-tr">${Object.keys(TR).map(k=>`<button class="${f.tr===k?'on':''}" data-mtr="${k}"><i style="background:var(--tone-${TR[k][2]}-solid)"></i>${L(TR[k][0],TR[k][1])}</button>`).join('')}</div></div></div><div class="m-drop"><button class="m-big pri" data-m="next" style="flex:1">${L('Next','التالي')}</button></div>`;
 return `${hd(L('Assign to','إسناد إلى'))}<div class="sm-det"><div class="m-types">${['tmc','gdl'].map(k=>`<button class="m-type${f.co===k?' on':''}" data-mco="${k}" style="${f.co===k?'box-shadow:inset 0 0 0 2px var(--btn-pri)':''}"><span class="av" style="width:34px;height:34px;font-size:12px;background:${CO[k][2]}">${CO[k][3]}</span><span><b style="display:block">${L(CO[k][0],CO[k][1])}</b><small style="font-size:12px;color:var(--ui-muted)">${L(CO[k][4],CO[k][5])}</small></span></button>`).join('')}</div><small style="color:var(--ui-muted)">${L('You can only assign within your company and its subcontractors.','يمكنك الإسناد فقط داخل شركتك ومقاوليها من الباطن.')}</small></div><div class="m-drop"><button class="m-big pri" data-m="save" style="flex:1"><i class="ti ti-check"></i>${L('Save snag','حفظ الملاحظة')}</button></div>`}
function screen(){return `<div class="notch"></div><div class="sbar" style="background:var(--ui-surface)"><span>9:41</span><span class="ic"><i class="ti ti-antenna-bars-5"></i><i class="ti ti-wifi"></i><i class="ti ti-battery-3"></i></span></div><div class="sm-root">${M.flow?flow():M.det?detail():list()}</div>${M.toast?`<div class="m-toast"><i class="ti ti-circle-check"></i>${M.toast}</div>`:''}<div class="m-home"></div>`}
function render(){const el=document.getElementById('scr');const l=el.querySelector('.sm-list');const y=l?l.scrollTop:0;el.innerHTML=screen();const n=el.querySelector('.sm-list');if(n)n.scrollTop=y}
function all(){document.documentElement.lang=S.lang;document.documentElement.dir=S.lang==='ar'?'rtl':'ltr';document.getElementById('scr').className='scr'+(S.mode==='dark'?' theme-dark':'');
 document.getElementById('demo').innerHTML=`<span class="segv">${[['list',L('List','القائمة')],['det',L('Detail','التفاصيل')],['new',L('Create flow','إنشاء')]].map(s=>`<button data-demo="${s[0]}">${s[1]}</button>`).join('')}</span><span class="segv"><button class="${S.lang==='en'?'on':''}" data-lang="en">EN</button><button class="${S.lang==='ar'?'on':''}" data-lang="ar">عربي</button></span><a class="cb" href="snag-list.html" style="text-decoration:none"><i class="ti ti-device-desktop"></i>${L('Desktop','سطح المكتب')}</a>`;render()}
let tt;const flash=m=>{M.toast=m;render();clearTimeout(tt);tt=setTimeout(()=>{M.toast=null;render()},2000)};
const file=document.createElement('input');file.type='file';file.accept='image/*';file.style.display='none';document.body.appendChild(file);
file.addEventListener('change',()=>{const f=file.files[0];file.value='';if(!f)return;const rd=new FileReader();rd.onload=()=>{M.flow.shot=rd.result;render()};rd.readAsDataURL(f)});
const keep=()=>{const t=document.getElementById('mt');if(t&&M.flow)M.flow.title=t.value};
const setSt=(id,st)=>{const it=I.find(x=>x.id===id);it.stage=st;it.wk=0.2;if(st==='res'&&!it.after)it.after={note:['Fixed on site — photo attached.','تم الإصلاح في الموقع — الصورة مرفقة.'],photos:1};M.sw=null;flash(L(`${it.no.replace('TWR-','')} → ${STG[st].en}`,`${it.no.replace('TWR-','')} ← ${STG[st].ar}`))};
document.addEventListener('click',e=>{const b=e.target.closest('[data-m],[data-mt],[data-mst],[data-mopen],[data-mres],[data-mhold],[data-mf],[data-mpin],[data-mtr],[data-mco],[data-msug],[data-demo],[data-lang]');if(!b)return;const d=b.dataset;keep();
 if(d.lang){S.lang=d.lang;try{const o=JSON.parse(localStorage.getItem('rb-shell-v1')||'{}');o.lang=d.lang;localStorage.setItem('rb-shell-v1',JSON.stringify(o))}catch(x){}return all()}
 if(d.demo){M.flow=null;M.det=null;M.sheet=false;if(d.demo==='det')M.det=I.find(x=>x.no==='TWR-TMC-EL-SNG-014').id;if(d.demo==='new')M.flow={step:'cam',shot:null,f:'02',pin:null,title:'',tr:'EL',co:'tmc'};return render()}
 if(d.mt){M.type=d.mt;return render()}
 if(d.mst){M.st.has(d.mst)?M.st.delete(d.mst):M.st.add(d.mst);return render()}
 if(d.mopen){if(M.sw){M.sw=null;return render()}M.det=d.mopen;return render()}
 if(d.mres)return setSt(d.mres,'res');
 if(d.mhold)return setSt(d.mhold,'hold');
 if(d.mf){M.flow.f=d.mf;return render()}
 if(d.mpin){const r=b.getBoundingClientRect();M.flow.pin=[(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100];return render()}
 if(d.mtr){M.flow.tr=d.mtr;return render()}
 if(d.mco){M.flow.co=d.mco;return render()}
 if(d.msug){M.flow.title=d.msug;M.flow.err=false;return render()}
 const a=d.m;
 if(a==='filters'){M.sheet=true;return render()}if(a==='closesheet'){M.sheet=false;return render()}
 if(a==='mine'){M.mine=!M.mine;return render()}
 if(a==='back'){M.det=null;return render()}
 if(a==='new'){M.flow={step:'cam',shot:null,f:'02',pin:null,title:'',tr:'EL',co:'tmc'};return render()}
 if(a==='cancelflow'){M.flow=null;return flash(L('Draft kept — finish it any time','تم الاحتفاظ بالمسودة'))}
 if(a==='shoot'||a==='lib'){file.toggleAttribute('capture',a==='shoot');if(a==='shoot')file.setAttribute('capture','environment');return file.click()}
 if(a==='prev'){const i=STEPS.indexOf(M.flow.step);M.flow.step=STEPS[Math.max(0,i-1)];return render()}
 if(a==='next'){if(M.flow.step==='title'&&!M.flow.title.trim()){M.flow.err=true;return render()}const i=STEPS.indexOf(M.flow.step);M.flow.step=STEPS[i+1];return render()}
 if(a==='save'){const f=M.flow;const k=CO[f.co][3]+'-'+f.tr+'-SNG';const it={id:'m'+Date.now(),no:'TWR-'+k+'-'+String(I.filter(i=>i.no.startsWith('TWR-'+k)).length+40).padStart(3,'0'),type:'snag',t:[f.title,f.title],tr:f.tr,f:f.f,sp:0,co:f.co,who:f.co==='gdl'?'omar':'nasser',stage:'open',wk:0.2,photos:f.shot?1:0,img:f.shot,src:null,pin:f.pin,chat:[],internal:[],hist:[]};I.unshift(it);M.flow=null;M.det=it.id;return flash(L(`${it.no.replace('TWR-','')} saved`,`تم حفظ ${it.no.replace('TWR-','')}`))}
});
document.addEventListener('input',e=>{if(e.target.id==='mt'&&M.flow){M.flow.title=e.target.value;if(M.flow.err){M.flow.err=false;e.target.classList.remove('err')}}});
// swipe
let P=null;
document.addEventListener('pointerdown',e=>{const c=e.target.closest('.sm-card');if(!c)return;P={id:c.closest('[data-sw]').dataset.sw,x:e.clientX,el:c,dx:0}});
addEventListener('pointermove',e=>{if(!P)return;const rtl=document.documentElement.dir==='rtl';let dx=e.clientX-P.x;dx=rtl?Math.max(0,Math.min(170,dx)):Math.min(0,Math.max(-170,dx));P.dx=dx;if(Math.abs(dx)>6){P.el.style.transition='none';P.el.style.transform=`translateX(${dx}px)`}});
addEventListener('pointerup',()=>{if(!P)return;const p=P;P=null;p.el.style.transition='';if(Math.abs(p.dx)>70){M.sw=p.id;document.getElementById('scr').style.setProperty('--swx',(document.documentElement.dir==='rtl'?150:-150)+'px');p.el.style.transform='';render();document.addEventListener('click',ev=>{ev.stopPropagation()},{once:true,capture:true})}else if(Math.abs(p.dx)>6){p.el.style.transform='';document.addEventListener('click',ev=>{ev.stopPropagation()},{once:true,capture:true})}else p.el.style.transform=''});
window.SM={M,all};
})();
