// Snag List module (desktop) + shared helpers (SN).
(function(){
const S=RS.S,{STG,SORDER,TYP,TR,CO,PPL,ROLES,LOCS,SPACES,SRC,I}=SD;
const L=(e,a)=>S.lang==='ar'?a:e;const esc=RS.esc;const T=x=>esc(L(x[0],x[1]));
/* ---- shared ---- */
const ty=k=>`<span class="ty" style="background:var(--tone-${TYP[k].tone}-tint);color:var(--tone-${TYP[k].tone}-fg)"><i class="ti ${TYP[k].ic}"></i>${L(TYP[k].en,TYP[k].ar)}</span>`;
const stp=k=>`<span class="stp" style="background:var(--tone-${STG[k].tone}-tint);color:var(--tone-${STG[k].tone}-fg)"><i></i>${L(STG[k].en,STG[k].ar)}</span>`;
const trc=k=>`<span class="chip" style="height:22px;font-size:11.5px;background:var(--tone-${TR[k][2]}-tint);color:var(--tone-${TR[k][2]}-fg)">${L(TR[k][0],TR[k][1])}</span>`;
const CODE={A:['var(--tone-green-solid)','#fff','ti-check'],B:['var(--tone-green-tint)','var(--tone-green-fg)','ti-message-circle'],C:['var(--tone-orange-tint)','var(--tone-orange-fg)','ti-refresh'],D:['var(--tone-red-tint)','var(--tone-red-fg)','ti-x']};
const cdb=c=>`<span class="cdb" style="background:${CODE[c][0]};color:${CODE[c][1]}"><i class="ti ${CODE[c][2]}"></i>Code ${c}</span>`;
const DOT=['#9aa0ad','#9aa0ad','#ee964b','#e5484d'];
const age=(w,lbl)=>{const n=Math.min(4,Math.max(1,Math.round(w)));const c=n>=4?'#e5484d':DOT[n-1];return `<span class="age" title="${L(n+(n>=4?'+':'')+' weeks at this step',n+' أسابيع في هذه الخطوة')}">${[1,2,3,4].map(i=>`<i style="${i<=n?`background:${c};box-shadow:none`:''}"></i>`).join('')}${lbl?`<em>${n}${n>=4?'+':''}${L('w','أ')}</em>`:''}</span>`};
const av=(p,s)=>`<span class="av" style="width:${s||24}px;height:${s||24}px;font-size:${Math.round((s||24)*.38)}px;background:${PPL[p][3]}">${RS.ini(PPL[p][0])}</span>`;
const loc=it=>L(LOCS[it.f][0],LOCS[it.f][1])+' · '+T(SPACES[it.sp]);
const srcShort=s=>s.no.split('-').slice(-2).join('-');
function visible(it,role){const r=ROLES[role];return !r.sees||r.sees.includes(it.co)}
const thm=it=>`<span class="thm">${it.img?`<img src="${it.img}" alt="">`:`<i class="ti ${it.photos?'ti-photo':'ti-photo-off'}"></i>`}${it.photos>1?`<b>${it.photos}</b>`:''}</span>`;
window.SN={L,T,ty,stp,trc,cdb,age,av,loc,srcShort,visible,thm,esc};
/* ---- state ---- */
const V={fsel:{},gb:'stage',role:'admin',view:'list',type:'all',F:{tr:new Set(),fl:new Set(),co:new Set(),st:new Set(),mine:false,src:''},q:'',open:{},sel:new Set(),menu:null,det:null,tab:'det',act:null,draft:null,create:null,modal:null,empty:false,toast:null,cm:''};
const R0=()=>ROLES[V.role];
function list(){if(V.empty)return [];const q=V.q.trim().toLowerCase();const F=V.fsel,has=(k,v)=>!F[k]||!F[k].length||F[k].includes(v);return I.filter(it=>visible(it,V.role)&&has('type',it.type)&&has('stage',it.stage)&&has('tr',it.tr)&&has('fl',it.f)&&has('co',it.co)&&has('src',it.src||'manual')&&(!F.age||!F.age.length||it.wk>=+F.age[0])&&(V.type==='all'||it.type===V.type)&&(!V.F.tr.size||V.F.tr.has(it.tr))&&(!V.F.fl.size||V.F.fl.has(it.f))&&(!V.F.co.size||V.F.co.has(it.co))&&(!V.F.st.size||V.F.st.has(it.stage))&&(!V.F.mine||it.who===R0().me||(V.role==='tmc'&&it.who==='nasser'))&&(!V.F.src||it.src===V.F.src)&&(!q||(it.no+' '+it.t[0]+' '+it.t[1]).toLowerCase().includes(q)))}
/* ---- toolbar ---- */
function dd(key,label,opts){const set=V.F[key];const n=set.size;return `<span class="rel"><button class="cb fbtn${n?' set':''}" data-menu="f-${key}">${label}<span class="v">${n?': '+(n===1?opts.find(o=>set.has(o[0]))[1]:n):''}</span><i class="ti ti-chevron-down"></i></button>${V.menu==='f-'+key?`<div class="pop" data-stop style="min-width:220px"><h6>${label}</h6>${opts.map(o=>`<button class="mi${set.has(o[0])?' on':''}" data-fk="${key}:${o[0]}">${o[2]||''}${o[1]}${set.has(o[0])?'<i class="ti ti-check ck"></i>':''}</button>`).join('')}</div>`:''}</span>`}
const fc=()=>Object.values(V.fsel).filter(v=>v&&v.length).length;
function fields(){const r=R0(),all=I.filter(it=>visible(it,V.role));const cos=Object.keys(CO).filter(k=>!r.sees||r.sees.includes(k));const srcs=Object.keys(SRC).filter(k=>all.some(i=>i.src===k));
 return [{k:'type',n:L('Type','النوع'),a:L('النوع','Type'),mark:'ic',opts:Object.keys(TYP).map(k=>[k,TYP[k].ic,0,L(TYP[k].pl[0],TYP[k].pl[1])])},{k:'stage',n:L('Stage','المرحلة'),a:L('المرحلة','Stage'),mark:'dot',opts:SORDER.map(k=>[k,'var(--tone-'+STG[k].tone+'-solid)',0,L(STG[k].en,STG[k].ar)])},{k:'tr',n:L('Trade','التخصص'),a:L('التخصص','Trade'),mark:'chip',opts:Object.keys(TR).map(k=>[k,TR[k][2],k,L(TR[k][0],TR[k][1])])},{sep:1},{k:'fl',n:L('Location','الموقع'),a:L('الموقع','Location'),mark:'ic',opts:Object.keys(LOCS).map(k=>[k,'ti-stairs',0,L('Tower 1 · ','البرج ١ · ')+L(LOCS[k][0],LOCS[k][1])])},{k:'co',n:L('Company','الشركة'),a:L('الشركة','Company'),mark:'av',opts:cos.map(k=>{const o=[k,CO[k][2],0,L(CO[k][0],CO[k][1])];o.av=CO[k][0];return o})},{k:'src',n:L('Raised from','المصدر'),a:L('المصدر','Source'),mark:'ic',opts:[...srcs.map(k=>[k,SRC[k].kind==='sub'?'ti-file-text':SRC[k].kind==='insp'?'ti-clipboard-check':'ti-report',0,srcShort(SRC[k])+' · '+L(SRC[k].t[0],SRC[k].t[1])+(SRC[k].code?' · Code '+SRC[k].code:'')]),['manual','ti-hand-finger',0,L('Raised manually','يدوي')]]},{sep:1},{k:'age',n:L('Weeks at step','الأسابيع في الخطوة'),a:L('العمر','Age'),single:1,mark:'days',opts:[['2','g___',0,L('2+ weeks','2+ أسابيع')],['3','y___',0,L('3+ weeks','3+ أسابيع')],['4','rrrr',0,L('4+ weeks','4+ أسابيع')]]}]}
const SNSAVED={starred:['Code B comments · MAR-041','My open snags'],mine:['Failed inspections','Floor 02 · Electrical','Stuck 3+ weeks']};
const SNPRESET={'Code B comments · MAR-041':{type:['cmt'],src:['mar041']},'My open snags':{type:['snag'],stage:['open','prog']},'Failed inspections':{src:['ir045','ir051']},'Floor 02 · Electrical':{fl:['02'],tr:['EL']},'Stuck 3+ weeks':{age:['3']}};
function toolbar(){const r=R0();const GB=[['stage',L('Stage','المرحلة')],['type',L('Type','النوع')],['tr',L('Trade','التخصص')],['none',L('No grouping','بدون تجميع')]];
 return `<div class="sn-bar"><button class="cb pri" data-act="new"><i class="ti ti-plus"></i>${L('New Snag','ملاحظة جديدة')}</button>
 <label class="fsrch"><i class="ti ti-search"></i><input id="snq" placeholder="${L('Search number or title','ابحث بالرقم أو العنوان')}" value="${esc(V.q)}"><kbd>/</kbd></label>
 <button class="cb${fc()?' on':''}" data-fpop="sn"><i class="ti ti-filter"></i>${L('Filter','تصفية')}${fc()?`<span class="fcnt">${fc()}</span>`:''}<i class="ti ti-chevron-down"></i></button>
 <span class="rel"><button class="cb ic" data-menu="gset" title="${L('Settings','الإعدادات')}"><i class="ti ti-settings"></i></button>${V.menu==='gset'?`<div class="pop" data-stop style="min-width:220px"><h6>${L('Group by','تجميع حسب')}</h6>${GB.map(g=>`<button class="mi${V.gb===g[0]?' on':''}" data-gb="${g[0]}">${g[1]}${V.gb===g[0]?'<i class="ti ti-check ck"></i>':''}</button>`).join('')}</div>`:''}</span>
 <span class="tgl" data-act="mine"><span class="swc${V.F.mine?' on':''}"></span>${L('Assigned to me','مسند إليّ')}</span>
 ${fc()||V.q||V.F.mine?`<button class="cb ter sm" data-act="clearf">${L('Clear','مسح')}</button>`:''}
 <span class="sp"></span>
 <span class="rel"><button class="vis" data-menu="role"><i class="ti ti-eye"></i>${L(r.en,r.ar)}<i class="ti ti-chevron-down"></i></button>${V.menu==='role'?`<div class="pop end" data-stop style="min-width:280px"><h6>${L('Demo · view as','عرض توضيحي · العرض بصفة')}</h6>${Object.entries(ROLES).map(([k,x])=>`<button class="mi${V.role===k?' on':''}" data-role="${k}"><i class="ti ${k==='admin'?'ti-shield':k==='dcl'?'ti-user-check':'ti-user-circle'}"></i>${L(x.en,x.ar)}</button>`).join('')}</div>`:''}</span>
 <span class="segv"><button class="${V.view==='list'?'on':''}" data-view="list"><i class="ti ti-list"></i>${L('List','قائمة')}</button><button class="${V.view==='kanban'?'on':''}" data-view="kanban"><i class="ti ti-layout-grid"></i>${L('Kanban','كانبان')}</button><button data-view="plan"><i class="ti ti-vector"></i>${L('Plan','المخطط')}</button></span>
 <span class="rel"><button class="cb" data-menu="exp"><i class="ti ti-file-download"></i>${L('Export','تصدير')}<i class="ti ti-chevron-down"></i></button>${V.menu==='exp'?`<div class="pop end" data-stop><button class="mi" data-exp="pdf"><i class="ti ti-file-text"></i>${L('PDF snag report','تقرير الملاحظات PDF')}</button><button class="mi" data-exp="xls"><i class="ti ti-table"></i>Excel<small>.xls</small></button></div>`:''}</span>
 <span class="rel"><button class="cb ic" data-menu="demo"><i class="ti ti-dots"></i></button>${V.menu==='demo'?`<div class="pop end" data-stop><h6>${L('Demo states','حالات العرض')}</h6><button class="mi" data-demo="cmt"><i class="ti ti-message-circle"></i>${L('Comment from Code B submittal','تعليق من تقديم Code B')}</button><button class="mi" data-demo="resolve"><i class="ti ti-circle-check"></i>${L('Contractor marks Resolved','المقاول يحدد كمحلول')}</button><button class="mi" data-demo="verify"><i class="ti ti-user-check"></i>${L('Consultant verifies','الاستشاري يتحقق')}</button><button class="mi" data-demo="panel"><i class="ti ti-file-text"></i>${L('Submittal page · comments panel','صفحة التقديم · لوحة التعليقات')}</button><button class="mi" data-demo="empty"><i class="ti ti-mood-smile"></i>${L('Empty state','الحالة الفارغة')}</button><div class="sep"></div><a class="mi" href="snag-list-mobile.html"><i class="ti ti-device-mobile"></i>${L('Mobile version','نسخة الجوال')}</a></div>`:''}</span></div>`}
/* ---- list ---- */
function srcCell(it){if(!it.src)return `<span style="color:var(--ui-faint);font-size:12.5px">${L('Manual','يدوي')}</span>`;const s=SRC[it.src];return `<span style="display:inline-flex;gap:6px;align-items:center"><a class="src num" data-srcopen="${it.src}">${srcShort(s)}</a>${s.code?cdb(s.code):s.kind==='insp'?`<span class="cdb" style="background:var(--tone-red-tint);color:var(--tone-red-fg)"><i class="ti ti-x"></i>${L('Failed','راسب')}</span>`:''}</span>`}
function row(it){const on=V.sel.has(it.id),p=PPL[it.who];return `<tr class="${on?'sel':''}" data-open="${it.id}"><td class="c-chk"><span class="ck${on?' on':''}" data-sel="${it.id}">${on?'<i class="ti ti-check"></i>':''}</span></td><td><span class="num" style="font-size:12.5px;color:var(--ui-muted);font-weight:600">${it.no}</span></td><td><span class="ttl">${T(it.t)}</span></td><td>${ty(it.type)}</td><td>${trc(it.tr)}</td><td style="font-size:12.5px;color:var(--ui-text-2)">${loc(it)}</td><td>${srcCell(it)}</td><td><span class="asg">${av(it.who)}<span><b>${T(p)}</b><small>${CO[it.co][3]}</small></span></span></td><td>${age(it.wk,1)}</td><td>${thm(it)}</td></tr>`}
function listView(ls){const g={};const gk=it=>V.gb==='type'?it.type:V.gb==='tr'?it.tr:V.gb==='none'?'all':it.stage;ls.forEach(it=>(g[gk(it)]=g[gk(it)]||[]).push(it));const GO=V.gb==='type'?Object.keys(TYP):V.gb==='tr'?Object.keys(TR):V.gb==='none'?['all']:SORDER;const ghead=k=>V.gb==='type'?ty(k):V.gb==='tr'?trc(k):V.gb==='none'?`<b>${L('All items','كل العناصر')}</b>`:stp(k);const nsel=V.sel.size;
 return `<div class="tw">${nsel?`<div class="bulk">${nsel} ${L('selected','محدد')}<span class="sp"></span><span class="rel"><button class="cb sm" data-menu="b-re"><i class="ti ti-user"></i>${L('Reassign','إعادة إسناد')}<i class="ti ti-chevron-down"></i></button>${V.menu==='b-re'?`<div class="pop end" data-stop><h6>${L('Within ','ضمن ')}${L(CO[R0().co==='dcl'&&V.role!=='admin'?'dcl':'tmc'][0],CO[R0().co==='dcl'&&V.role!=='admin'?'dcl':'tmc'][1])}</h6>${Object.keys(PPL).filter(k=>PPL[k][2]===(V.role==='dcl'?'dcl':'tmc')).map(k=>`<button class="mi" data-bre="${k}">${av(k,20)}${T(PPL[k])}</button>`).join('')}</div>`:''}</span><span class="rel"><button class="cb sm" data-menu="b-st"><i class="ti ti-arrows-sort"></i>${L('Move stage','نقل المرحلة')}<i class="ti ti-chevron-down"></i></button>${V.menu==='b-st'?`<div class="pop end" data-stop>${SORDER.map(k=>`<button class="mi" data-bst="${k}">${stp(k)}</button>`).join('')}</div>`:''}</span><button class="cb sm" data-exp="xls"><i class="ti ti-file-download"></i>${L('Export','تصدير')}</button><button class="cb sm ter" data-act="clrsel">${L('Clear','مسح')}</button></div>`:''}
 <div class="ts" style="max-height:none"><table class="lv"><thead><tr><th class="c-chk"><span class="ck${nsel&&nsel===ls.length?' on':''}" data-act="selall">${nsel?`<i class="ti ti-${nsel===ls.length?'check':'minus'}"></i>`:''}</span></th><th style="min-width:180px">${L('Number','الرقم')}</th><th style="min-width:240px">${L('Title','العنوان')}</th><th>${L('Type','النوع')}</th><th>${L('Trade','التخصص')}</th><th style="min-width:160px">${L('Location','الموقع')}</th><th style="min-width:150px">${L('Raised from','المصدر')}</th><th style="min-width:170px">${L('Assigned to','مسند إلى')}</th><th>${L('Age','العمر')}</th><th>${L('Photo','صورة')}</th></tr></thead><tbody>
 ${GO.filter(k=>g[k]).map(k=>{const open=V.open[k]!==false;return `<tr class="gh${open?' open':''}" data-grp="${k}"><td colspan="10"><span class="ghi"><i class="ti ti-chevron-right"></i>${ghead(k)}<small>${g[k].length} ${L('items','عنصر')}</small></span></td></tr>${open?g[k].map(row).join(''):''}`}).join('')}
 </tbody></table></div></div>`}
function card(it){return `<div class="skc" data-open="${it.id}"><div class="r1"><i class="ti ${TYP[it.type].ic}" style="color:var(--tone-${TYP[it.type].tone}-solid);font-size:16px"></i><span class="num">${it.no}</span>${thm(it)}</div><b>${T(it.t)}</b><div class="r2"><span class="lc"><i class="ti ti-map-pin"></i>${loc(it)}</span>${trc(it.tr)}</div><div class="r3">${av(it.who,22)}${T(PPL[it.who]).split(' ')[0]}${age(it.wk)}</div></div>`}
function kanban(ls){return `<div class="skb">${SORDER.map(k=>{const a=ls.filter(i=>i.stage===k);return `<section class="kcol" data-colst="${k}"><div class="kch"><span class="d" style="background:var(--tone-${STG[k].tone}-solid)"></span>${L(STG[k].en,STG[k].ar)}<span class="n">${a.length}</span></div><div class="klist">${a.map(card).join('')||`<div class="kempty">${L('Nothing here','لا شيء هنا')}</div>`}</div></section>`}).join('')}</div>`}
/* ---- detail ---- */
const HA={create:['ti-plus','Raised','أُنشئت','gray'],prog:['ti-player-play','Started work','بدأ العمل','blue'],hold:['ti-player-pause','Put on hold','عُلّقت','gray'],res:['ti-circle-check','Marked Resolved','حُدّدت كمحلولة','violet'],closed:['ti-lock','Verified & closed','تم التحقق والإغلاق','green'],reopen:['ti-refresh','Re-opened','أُعيد فتحها','orange']};
function actions(it){const c=R0().can,mine=V.role==='admin'||(R0().sees&&R0().sees.includes(it.co));const b=[];
 if(it.stage==='open'&&c.includes('start')&&mine)b.push(`<button class="cb" data-do="prog"><i class="ti ti-player-play"></i>${L('Start work','بدء العمل')}</button>`);
 if(['open','prog'].includes(it.stage)&&c.includes('hold'))b.push(`<button class="cb" data-do="hold"><i class="ti ti-player-pause"></i>${L('Put On Hold','تعليق')}</button>`);
 if(it.stage==='hold'&&c.includes('start')&&mine)b.push(`<button class="cb" data-do="prog"><i class="ti ti-player-play"></i>${L('Resume','استئناف')}</button>`);
 if(['open','prog','hold'].includes(it.stage)&&c.includes('resolve')&&mine)b.push(`<button class="cb pri" data-act="resolveform"><i class="ti ti-circle-check"></i>${L('Mark Resolved','تحديد كمحلول')}</button>`);
 if(it.stage==='res'&&c.includes('close'))b.push(`<button class="cb" data-act="reopenform"><i class="ti ti-refresh"></i>${L('Re-open','إعادة فتح')}</button><button class="cb pri" data-do="closed"><i class="ti ti-lock"></i>${L('Close','إغلاق')}</button>`);
 if(it.stage==='closed'&&c.includes('reopen'))b.push(`<button class="cb" data-act="reopenform"><i class="ti ti-refresh"></i>${L('Re-open','إعادة فتح')}</button>`);
 if(!b.length)return `<div class="wait"><i class="ti ti-clock"></i>${it.stage==='res'?L('Waiting for the consultant to verify.','بانتظار تحقق الاستشاري.'):it.stage==='closed'?L('Closed — no further action.','مغلقة — لا إجراء إضافي.'):L('Waiting for the contractor.','بانتظار المقاول.')}</div>`;return `<div class="acts">${b.join('')}</div>`}
const ph=(tag,c,src,i)=>`<div class="ph">${src?`<img src="${src}" alt="">`:`<i class="ti ti-photo"></i>${L('Photo','صورة')} ${i}`}${tag?`<span class="tg" style="background:${c}">${tag}</span>`:''}</div>`;
function actForm(it){if(V.act==='resolve'){const d=V.draft;return `<div class="actf"><h4><i class="ti ti-circle-check" style="color:var(--btn-pri)"></i>${L('Mark as Resolved','تحديد كمحلول')}</h4><textarea id="fixnote" rows="3" class="${d.err?'err':''}" placeholder="${L('What did you fix? (required)','ما الذي تم إصلاحه؟ (مطلوب)')}">${esc(d.note)}</textarea><div class="ba"><div><small>${L('Before','قبل')}</small><div class="gal">${Array.from({length:Math.max(1,it.photos)},(_,i)=>ph('',0,null,i+1)).join('')}</div></div><div><small>${L('After','بعد')}</small><div class="gal">${d.photos.map(s=>ph(L('After','بعد'),'var(--tone-green-solid)',s)).join('')}<button class="phadd" data-act="afterphoto"><i class="ti ti-camera"></i>${L('Add after photo','إضافة صورة بعد')}</button></div></div></div><div class="row"><button class="cb" data-act="cancelact">${L('Cancel','إلغاء')}</button><button class="cb pri" data-act="doresolve"><i class="ti ti-check"></i>${L('Submit for verification','إرسال للتحقق')}</button></div></div>`}
 if(V.act==='reopen'){const d=V.draft;return `<div class="actf" style="border-color:var(--tone-orange-solid)"><h4><i class="ti ti-refresh" style="color:var(--tone-orange-solid)"></i>${L('Re-open with a note','إعادة الفتح مع ملاحظة')}</h4><textarea id="ronote" rows="3" class="${d.err?'err':''}" placeholder="${L('Tell the contractor what is still wrong (required)','أخبر المقاول بما لا يزال خاطئًا (مطلوب)')}">${esc(d.note)}</textarea><div class="row"><button class="cb" data-act="cancelact">${L('Cancel','إلغاء')}</button><button class="cb pri" data-act="doreopen" style="background:var(--tone-orange-solid)"><i class="ti ti-refresh"></i>${L('Re-open','إعادة فتح')}</button></div></div>`}return ''}
function raised(it){if(!it.src)return `<div class="box"><h6>${L('Raised from','المصدر')}</h6><div style="font-size:13px;color:var(--ui-muted)">${L('Raised manually on site.','أُنشئت يدويًا في الموقع.')}</div></div>`;const s=SRC[it.src];
 if(s.kind==='sub')return `<div class="box"><h6><i class="ti ti-link"></i>${L('Raised from submittal','مصدرها التقديم')}</h6><div class="rf"><span class="ic" style="background:var(--tone-green-tint);color:var(--tone-green-fg)"><i class="ti ti-file-text"></i></span><div class="tx"><span class="num">${s.no}</span><b>${T(s.t)}</b></div>${cdb(s.code)}</div>${it.q?`<blockquote class="quote">“${T(it.q)}”<small>— ${T(PPL[s.by])} · ${L('Consultant review','مراجعة الاستشاري')}</small></blockquote>`:''}<div><button class="cb sm" data-srcopen="${it.src}"><i class="ti ti-external-link"></i>${L('Open submittal','فتح التقديم')}</button></div></div>`;
 if(s.kind==='insp')return `<div class="box"><h6><i class="ti ti-link"></i>${L('Raised from inspection','مصدرها الفحص')}</h6><div class="rf"><span class="ic" style="background:var(--tone-red-tint);color:var(--tone-red-fg)"><i class="ti ti-clipboard-check"></i></span><div class="tx"><span class="num">${s.no}</span><b>${T(s.t)}</b></div></div><div class="failed"><i class="ti ti-x"></i>${L('Failed checklist item: ','بند فحص راسب: ')}${T(s.failed)}</div><div class="gal">${ph(L('Inspection','الفحص'),'var(--tone-red-solid)',null,1)}</div><div><button class="cb sm" data-srcopen="${it.src}"><i class="ti ti-external-link"></i>${L('Open inspection','فتح الفحص')}</button></div></div>`;
 return `<div class="box"><h6><i class="ti ti-link"></i>${L('Raised from daily report','مصدرها التقرير اليومي')}</h6><div class="rf"><span class="ic" style="background:var(--tone-gray-tint);color:var(--ui-muted)"><i class="ti ti-report"></i></span><div class="tx"><span class="num">${s.no}</span><b>${T(s.t)}</b></div><button class="cb sm" data-srcopen="${it.src}">${L('Open','فتح')}</button></div></div>`}
function miniPlan(it){return `<div class="mini">${PD.drawing({no:'A-10'+(it.f==='02'?2:1),en:'Plan',rev:'C',date:''})}${it.pin?`<span class="mp" style="left:${it.pin[0]/12}%;top:${it.pin[1]/8}%"></span>`:''}</div>`}
function detail(){const it=I.find(x=>x.id===V.det);if(!it)return '';const p=PPL[it.who];const own=R0().co;const intl=it.internal.filter(m=>PPL[m.by][2]===own||(own==='tmc'&&PPL[m.by][2]==='gdl')||V.role==='admin'&&false);
 let body='';
 if(V.tab==='det')body=`${actForm(it)}${raised(it)}
  ${it.after?`<div class="box"><h6><i class="ti ti-circle-check"></i>${L('Contractor response','رد المقاول')}<span class="r">${av(it.who,20)}</span></h6><div class="fnote">${T(it.after.note)}</div><div class="ba"><div><small>${L('Before','قبل')}</small><div class="gal">${it.photos?Array.from({length:Math.min(2,it.photos)},(_,i)=>ph('',0,null,i+1)).join(''):`<div class="ph"><i class="ti ti-photo-off"></i></div>`}</div></div><div><small>${L('After','بعد')}</small><div class="gal">${(it.after.imgs||[]).map(s=>ph(L('After','بعد'),'var(--tone-green-solid)',s)).join('')||(it.after.photos?ph(L('After','بعد'),'var(--tone-green-solid)',null,1):`<div class="ph" style="font-size:11.5px">${it.after.files?L('Document attached','مستند مرفق'):L('No photo','لا صورة')}</div>`)}</div></div></div></div>`:''}
  <div class="box"><h6>${L('Details','التفاصيل')}</h6>${it.desc?`<div style="font-size:13.5px;line-height:1.55;color:var(--ui-text)">${T(it.desc)}</div>`:''}<div class="kv2"><span>${L('Trade','التخصص')}</span><b>${trc(it.tr)}</b><span>${L('Assigned to','مسند إلى')}</span><b>${av(it.who,20)}${T(p)} · ${L(CO[it.co][0],CO[it.co][1])}</b><span>${L('Stage','المرحلة')}</span><b>${stp(it.stage)}${age(it.wk,1)}</b></div>
  <div class="locrow">${miniPlan(it)}<div class="kv2" style="grid-template-columns:auto 1fr;align-content:start"><span>${L('Zone','المنطقة')}</span><b>${L('Zone A – North Wing','المنطقة أ')}</b><span>${L('Building','المبنى')}</span><b>${L('Tower 1','البرج ١')}</b><span>${L('Floor','الطابق')}</span><b>${L(LOCS[it.f][0],LOCS[it.f][1])}</b><span>${L('Space','المساحة')}</span><b>${T(SPACES[it.sp])}</b><span></span><b><a class="src" href="plan-view.html?fl=${it.f}"><i class="ti ti-vector"></i>${L('Open on plan','فتح على المخطط')}</a></b></div></div></div>
  ${it.photos?`<div class="box"><h6>${L('Photos','الصور')}<span class="r">${it.photos}</span></h6><div class="gal">${Array.from({length:it.photos},(_,i)=>it.img&&i===0?ph('',0,it.img):ph('',0,null,i+1)).join('')}</div></div>`:''}
  <div class="box"><h6>${L('Attachments','المرفقات')}</h6><div class="files">${it.type==='cmt'?`<div class="fl"><i class="ti ti-file-text"></i>${L('Review comments sheet.pdf','ورقة ملاحظات المراجعة.pdf')}<small>240 KB</small></div>`:''}${it.after&&it.after.files?`<div class="fl"><i class="ti ti-file-text"></i>TH-IP65-2291.pdf<small>1.1 MB</small></div>`:''}${it.type!=='cmt'&&!(it.after&&it.after.files)?`<div style="font-size:12.5px;color:var(--ui-faint)">${L('No attachments','لا مرفقات')}</div>`:''}</div></div>
  <div class="box"><h6>${L('History','السجل')}</h6><div class="hist">${it.hist.slice().reverse().map(h=>{const a=HA[h.a];return `<div class="hi"><span class="dt" style="background:var(--tone-${a[3]}-solid)"><i class="ti ${a[0]}"></i></span><div class="tx"><b>${T(PPL[h.by])}</b> ${L(a[1].toLowerCase(),a[2])}${h.note?`: “${esc(h.note)}”`:''}<small>${h.w<=0?L('Just now','الآن'):L(Math.round(h.w)+' week'+(Math.round(h.w)===1?'':'s')+' ago','منذ '+Math.round(h.w)+' أسابيع')} · ${L(CO[PPL[h.by][2]][0],CO[PPL[h.by][2]][1])}</small></div></div>`}).join('')}</div></div>`;
 const msgs=a=>`<div class="msgs">${a.map(m=>`<div class="msg${m.by===R0().me?' me':''}">${av(m.by,30)}<div class="bb"><small><b>${T(PPL[m.by])}</b> · ${m.w?L(m.w+'w ago','منذ '+m.w+' أ'):L('now','الآن')}</small>${m.t[0]===m.t[1]?esc(m.t[0]):T(m.t)}</div></div>`).join('')||`<div style="text-align:center;color:var(--ui-faint);font-size:13px;padding:30px">${L('No messages yet','لا رسائل بعد')}</div>`}</div>`;
 if(V.tab==='chat')body=msgs(it.chat);
 if(V.tab==='int')body=`<div class="lockb"><i class="ti ti-lock"></i>${L(`Only people at ${CO[own][0]} can see these notes.`,`هذه الملاحظات مرئية فقط لموظفي ${CO[own][1]}.`)}</div>${msgs(intl)}`;
 const WM={open:'o',prog:'p',hold:'p',res:'c',closed:'eA'};if(V.tab==='wf'){const cur=WM[it.stage];const path=['o','p','c','r'].slice(0,{o:1,p:2,c:3,eA:3}[cur]||1);const sc={},ec={};Object.keys(WF.SNAGWF.S).forEach(k=>sc[k]=k===cur?'cur':path.includes(k)||cur==='eA'?'done':'fade');Object.entries(WF.SNAGWF.T).forEach(([k,t])=>ec[k]=t.f===cur?'next info':(path.includes(t.to)||cur==='eA')&&path.includes(t.f)?'done':'fade');body=`<div class="lockb" style="background:var(--tone-blue-tint);color:var(--tone-blue-fg)"><i class="ti ti-git-branch"></i><b>${L('Now: ','الآن: ')}${L(WF.SNAGWF.S[cur]?.en||'Closed',WF.SNAGWF.S[cur]?.ar||'مغلق')}</b> · ${L('Snag – fix & confirm · v1','الملاحظة – إصلاح وتأكيد · v1')}</div><div class="wcv" style="height:300px"><div class="wstage"><div style="transform:translate(4px,-60px) scale(.44);transform-origin:0 0">${WF.renderDiagram({L,S:WF.SNAGWF.S,T:WF.SNAGWF.T,scls:sc,ecls:ec,hideOut:1})}</div></div></div>`}
 return `<div class="scrim" data-close="1"><div class="drw" data-stop><div class="dh"><div class="t1">${ty(it.type)}<span class="num">${it.no}</span>${stp(it.stage)}${age(it.wk,1)}<button class="cb ter sm ic x" data-close="1"><i class="ti ti-x"></i></button></div><h2>${T(it.t)}</h2>${actions(it)}<div class="dtabs">${[['det',L('Details','التفاصيل')],['wf',L('Workflow','سير العمل')],['chat',L('Chat','المحادثة'),it.chat.length],['int',L('Internal Communication','التواصل الداخلي'),intl.length]].map(t=>`<button class="${V.tab===t[0]?'on':''}" data-dtab="${t[0]}">${t[0]==='int'?'<i class="ti ti-lock" style="font-size:14px"></i>':''}${t[1]}${t[2]?`<span class="n">${t[2]}</span>`:''}</button>`).join('')}</div></div><div class="db" id="dbody">${body}</div>${V.tab==='chat'||V.tab==='int'?`<div class="compose"><input id="cmsg" placeholder="${V.tab==='int'?L('Internal note — only your company sees this','ملاحظة داخلية — مرئية لشركتك فقط'):L('Message everyone on this item','رسالة لكل المشاركين في هذا العنصر')}" value="${esc(V.cm)}"><button class="cb pri" data-act="send"><i class="ti ti-send"></i></button></div>`:''}</div></div>`}
/* ---- create ---- */
function create(){const c=V.create;if(!c)return '';const r=R0();const cos=Object.keys(CO).filter(k=>k!=='dcl'&&(!r.sees||r.sees.includes(k)));
 return `<div class="scrim" data-close="1"><div class="drw" data-stop><div class="dh" style="padding-bottom:12px"><div class="t1"><b style="font-size:17px">${L('New item','عنصر جديد')}</b><span style="font-size:12px;color:var(--ui-muted)">${c.saved?`<i class="ti ti-check"></i> ${L('Draft saved','تم حفظ المسودة')}`:''}</span><button class="cb ter sm ic x" data-close="1"><i class="ti ti-x"></i></button></div></div><div class="db"><div class="cf">
 <label>${L('Type','النوع')}<span class="chs">${Object.keys(TYP).map(k=>`<button class="${c.type===k?'on':''}" data-ctype="${k}"><i class="ti ${TYP[k].ic}"></i>${L(TYP[k].en,TYP[k].ar)}</button>`).join('')}</span></label>
 <label>${L('Title','العنوان')} *<input id="ct" class="${c.err?'err':''}" value="${esc(c.title)}" placeholder="${L('e.g. Cable tray not bonded','مثال: حامل الكابلات غير موصول')}"></label>
 <label>${L('Description','الوصف')}<textarea id="cd" rows="3">${esc(c.desc)}</textarea></label>
 <label>${L('Trade','التخصص')}<span class="chs">${Object.keys(TR).map(k=>`<button class="${c.tr===k?'on':''}" data-ctr="${k}"><i class="d" style="background:var(--tone-${TR[k][2]}-solid)"></i>${L(TR[k][0],TR[k][1])}</button>`).join('')}</span></label>
 <label>${L('Location','الموقع')}<span class="g3"><select><option>${L('Zone A – North Wing','المنطقة أ')}</option></select><select><option>${L('Tower 1','البرج ١')}</option></select><select id="cf">${Object.keys(LOCS).map(k=>`<option value="${k}"${c.f===k?' selected':''}>${L(LOCS[k][0],LOCS[k][1])}</option>`).join('')}</select></span></label>
 <div class="pinb">${miniPlan({f:c.f,pin:c.pin})}<div style="flex:1;font-size:13px;color:var(--ui-text-2)">${c.pin?L('Pinned on sheet A-102 Rev C','مثبّت على المخطط A-102 Rev C'):L('No pin yet — place it on the floor plan.','لا يوجد دبوس بعد — ضعه على مخطط الطابق.')}</div><button class="cb sm" data-act="pinit"><i class="ti ti-map-pin"></i>${c.pin?L('Move pin','نقل الدبوس'):L('Pin on plan','تثبيت على المخطط')}</button></div>
 <label>${L('Photos','الصور')}<span class="gal">${c.photos.map(s=>ph('',0,s)).join('')}<button class="phadd" data-act="cphoto"><i class="ti ti-camera"></i>${L('Add photo','إضافة صورة')}</button></span></label>
 <label>${L('Assign to company','إسناد إلى شركة')}<select id="cco">${cos.map(k=>`<option value="${k}"${c.co===k?' selected':''}>${L(CO[k][0],CO[k][1])} · ${L(CO[k][4],CO[k][5])}</option>`).join('')}</select></label>
 </div></div><div class="compose" style="justify-content:flex-end"><button class="cb" data-close="1">${L('Save as draft','حفظ كمسودة')}</button><button class="cb pri" data-act="save"><i class="ti ti-check"></i>${L('Create','إنشاء')}</button></div></div></div>`}
function panel(){if(V.modal!=='panel')return '';const s=SRC.mar041;const cs=I.filter(i=>i.src==='mar041'&&visible(i,V.role));const cl=cs.filter(i=>i.stage==='closed').length;
 return `<div class="scrim" data-close="1"><div class="mdl" data-stop><div class="mh"><i class="ti ti-file-text" style="color:var(--ui-muted)"></i><span class="num" style="font-size:12.5px;color:var(--ui-muted);font-weight:600">${s.no}</span><b>${T(s.t)}</b>${cdb('B')}<button class="cb ter sm ic x" data-close="1"><i class="ti ti-x"></i></button></div><div class="mb"><div class="fake box"><h6>${L('Submittal page (context)','صفحة التقديم (سياق)')}</h6>${[90,70,82,60,76,40].map(w=>`<span class="ln" style="width:${w}%"></span>`).join('')}</div>
 <div class="box"><h6><i class="ti ti-message-circle"></i>${L('Comments from Code B','التعليقات من Code B')}</h6><div style="display:flex;align-items:baseline;gap:8px"><b style="font:700 24px var(--font-ui)">${cl} ${L('of','من')} ${cs.length}</b><span style="font-size:13px;color:var(--ui-muted)">${L('closed','مغلقة')}</span></div><div class="pbar"><i style="width:${cs.length?cl/cs.length*100:0}%"></i></div>
 <div>${cs.map(i=>`<div class="cl" data-open="${i.id}"><i class="ti ti-message-circle" style="color:var(--tone-blue-solid)"></i><span class="t">${T(i.t)}</span>${stp(i.stage)}</div>`).join('')}</div><button class="cb sm" data-src="mar041" data-act="closemodal"><i class="ti ti-list"></i>${L('Open in Snag List','فتح في قائمة الملاحظات')}</button></div></div></div></div>`}
function view(){const ls=list();const empty=!ls.length;
 return `${toolbar()}${empty?(V.empty||!I.some(i=>visible(i,V.role))?`<div class="empty2"><span class="ic"><i class="ti ti-circle-check"></i></span><h2>${L('No snags. Nice work.','لا توجد ملاحظات. عمل رائع.')}</h2><p>${L('Snags and comments appear here when they’re raised on site, from failed inspections or from Code B reviews.','تظهر الملاحظات والتعليقات هنا عند تسجيلها في الموقع أو من الفحوصات الراسبة أو من مراجعات Code B.')}</p><div style="display:flex;gap:8px"><button class="cb pri" data-act="new"><i class="ti ti-plus"></i>${L('New Snag','ملاحظة جديدة')}</button>${V.empty?`<button class="cb" data-act="unempty">${L('Show sample data','عرض البيانات التجريبية')}</button>`:''}</div></div>`:`<div class="empty2"><span class="ic" style="background:var(--tone-gray-tint);color:var(--ui-muted)"><i class="ti ti-filter"></i></span><h2>${L('Nothing matches these filters','لا شيء يطابق التصفية')}</h2><button class="cb" data-act="clearf">${L('Clear filters','مسح التصفية')}</button></div>`):V.view==='kanban'?kanban(ls):listView(ls)}${detail()}${create()}${panel()}${V.toast?`<div class="toast"><i class="ti ti-circle-check"></i>${V.toast}</div>`:''}`}
/* ---- bind ---- */
function bind(root,R){SNV.R=R;let tt;const flash=m=>{V.toast=m;R();clearTimeout(tt);tt=setTimeout(()=>{V.toast=null;R()},2400)};
 const file=document.createElement('input');file.type='file';file.accept='image/*';file.multiple=true;file.style.display='none';document.body.appendChild(file);let fileT=null;
 file.addEventListener('change',()=>{[...file.files].forEach(f=>{const rd=new FileReader();rd.onload=()=>{(fileT==='after'?V.draft.photos:V.create.photos).push(rd.result);R()};rd.readAsDataURL(f)});file.value=''});
 const keep=()=>{const g=id=>document.getElementById(id);if(V.draft){const n=g('fixnote')||g('ronote');if(n)V.draft.note=n.value}if(V.create){if(g('ct'))V.create.title=g('ct').value;if(g('cd'))V.create.desc=g('cd').value;if(g('cf'))V.create.f=g('cf').value;if(g('cco'))V.create.co=g('cco').value}const m=g('cmsg');if(m)V.cm=m.value};
 const hist=(it,a,note)=>{it.hist.push({a,by:R0().me,w:0,note});it.wk=0.2};
 root.addEventListener('click',e=>{const b=e.target.closest('[data-menu],[data-fk],[data-type],[data-role],[data-view],[data-exp],[data-demo],[data-src],[data-act],[data-sel],[data-grp],[data-open],[data-close],[data-dtab],[data-do],[data-bre],[data-bst],[data-ctype],[data-ctr],[data-srcopen],[data-gb]');
  if(!b){if(V.menu&&!e.target.closest('[data-stop]')){V.menu=null;R()}return}
  if(b.closest('.hd,.tabs,.sb'))return;const d=b.dataset;keep();
  if(d.close!==undefined){if(e.target.closest('[data-stop]')&&!b.closest('button'))return;V.det=null;V.create=null;V.modal=null;V.act=null;return R()}
  if(d.menu){e.stopPropagation();V.menu=V.menu===d.menu?null:d.menu;return R()}
  if(d.fk){const [k,v]=d.fk.split(':');V.F[k].has(v)?V.F[k].delete(v):V.F[k].add(v);return R()}
  if(d.type){V.type=d.type;return R()}
  if(d.gb){V.gb=d.gb;V.menu=null;return R()}
  if(d.role){V.role=d.role;V.menu=null;V.sel.clear();V.F.co=new Set();return R()}
  if(d.view){if(d.view==='plan'){location.href='plan-view.html';return}V.view=d.view;return R()}
  if(d.exp){V.menu=null;if(d.exp==='pdf')return flash(L('Snag report PDF is being prepared…','جارٍ إعداد تقرير الملاحظات PDF…'));const ls=V.sel.size?list().filter(i=>V.sel.has(i.id)):list();const rows=[['Number','Title','Type','Trade','Location','Raised from','Assigned to','Company','Stage','Weeks'],...ls.map(i=>[i.no,i.t[0],TYP[i.type].en,TR[i.tr][0],LOCS[i.f][0]+' / '+SPACES[i.sp][0],i.src?SRC[i.src].no:'Manual',PPL[i.who][0],CO[i.co][0],STG[i.stage].en,Math.round(i.wk)])];const x=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;');const xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Snag List"><Table>${rows.map(r=>`<Row>${r.map(c=>`<Cell><Data ss:Type="String">${x(c)}</Data></Cell>`).join('')}</Row>`).join('')}</Table></Worksheet></Workbook>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([xml],{type:'application/vnd.ms-excel'}));a.download='rabaed-snag-list.xls';document.body.appendChild(a);a.click();a.remove();return flash(L(`Exported ${ls.length} items`,`تم تصدير ${ls.length} عنصر`))}
  if(d.src!==undefined&&!d.srcopen){V.fsel={src:d.src?[d.src]:[]};V.menu=null;if(d.act==='closemodal')V.modal=null;return R()}
  if(d.srcopen){e.stopPropagation();return flash(L(`Opening ${SRC[d.srcopen].no}…`,`جارٍ فتح ${SRC[d.srcopen].no}…`))}
  if(d.sel){e.stopPropagation();V.sel.has(d.sel)?V.sel.delete(d.sel):V.sel.add(d.sel);return R()}
  if(d.grp){V.open[d.grp]=V.open[d.grp]===false;return R()}
  if(d.open){V.det=d.open;V.tab='det';V.act=null;V.modal=null;V.cm='';return R()}
  if(d.dtab){V.tab=d.dtab;V.cm='';return R()}
  if(d.do){const it=I.find(x=>x.id===V.det);it.stage=d.do;hist(it,d.do);return flash(L(`${it.no} → ${STG[d.do].en}`,`${it.no} ← ${STG[d.do].ar}`))}
  if(d.bre){V.menu=null;const n=V.sel.size;list().filter(i=>V.sel.has(i.id)).forEach(i=>{i.who=d.bre;i.co=PPL[d.bre][2]});V.sel.clear();return flash(L(`Reassigned ${n} to ${PPL[d.bre][0]}`,`تمت إعادة إسناد ${n} إلى ${PPL[d.bre][1]}`))}
  if(d.bst){V.menu=null;const n=V.sel.size;list().filter(i=>V.sel.has(i.id)).forEach(i=>{i.stage=d.bst;hist(i,d.bst==='open'?'reopen':d.bst)});V.sel.clear();return flash(L(`Moved ${n} to ${STG[d.bst].en}`,`تم نقل ${n} إلى ${STG[d.bst].ar}`))}
  if(d.ctype){V.create.type=d.ctype;return R()}
  if(d.ctr){V.create.tr=d.ctr;return R()}
  if(d.demo){V.menu=null;V.empty=false;const f=no=>I.find(x=>x.no===no).id;
   if(d.demo==='cmt'){V.role='admin';V.det=f('TWR-DCL-EL-CMT-004');V.tab='det';V.act=null}
   if(d.demo==='resolve'){V.role='tmc';const it=I.find(x=>x.no==='TWR-TMC-EL-SNG-014');if(it.stage==='res'||it.stage==='closed')it.stage='open';V.det=it.id;V.tab='det';V.act='resolve';V.draft={note:'Bonding jumpers installed at all 3 joints; continuity re-tested at 0.05 Ω.',photos:[],err:false}}
   if(d.demo==='verify'){V.role='dcl';V.det=f('TWR-DCL-EL-CMT-003');V.tab='det';V.act=null}
   if(d.demo==='panel'){V.modal='panel';V.det=null}
   if(d.demo==='empty'){V.empty=true;V.det=null}
   return R()}
  const a=d.act;
  if(a==='mine'){V.F.mine=!V.F.mine;return R()}
  if(a==='clearf'){V.F={tr:new Set(),fl:new Set(),co:new Set(),st:new Set(),mine:false,src:''};V.fsel={};V.type='all';V.q='';FPop.close();return R()}
  if(a==='selall'){const ls=list();if(V.sel.size===ls.length)V.sel.clear();else ls.forEach(i=>V.sel.add(i.id));return R()}
  if(a==='clrsel'){V.sel.clear();return R()}
  if(a==='unempty'){V.empty=false;return R()}
  if(a==='new'){V.create={type:'snag',title:'',desc:'',tr:'EL',f:'02',pin:null,photos:[],co:R0().sees?R0().sees[0]:'tmc',err:false,saved:false};return R()}
  if(a==='pinit'){V.create.pin=[300+Math.round(Math.random()*600),120+Math.round(Math.random()*500)];V.create.saved=true;return R()}
  if(a==='cphoto'){fileT='create';return file.click()}
  if(a==='afterphoto'){fileT='after';return file.click()}
  if(a==='save'){const c=V.create;if(!c.title.trim()){c.err=true;R();document.getElementById('ct').focus();return}const k=CO[c.co][3]+'-'+c.tr+'-'+TYP[c.type].code;const nn=I.filter(i=>i.no.startsWith('TWR-'+k)).length+30;
   const it={id:'n'+Date.now(),no:'TWR-'+k+'-'+String(nn).padStart(3,'0'),type:c.type,t:[c.title,c.title],desc:c.desc?[c.desc,c.desc]:null,tr:c.tr,f:c.f,sp:0,co:c.co,who:Object.keys(PPL).find(p=>PPL[p][2]===c.co),stage:'open',wk:0.2,photos:c.photos.length,img:c.photos[0],src:null,pin:c.pin,chat:[],internal:[],hist:[{a:'create',by:R0().me,w:0}]};I.unshift(it);V.create=null;V.det=it.id;V.tab='det';return flash(L(`${it.no} created`,`تم إنشاء ${it.no}`))}
  if(a==='resolveform'){V.act='resolve';V.draft={note:'',photos:[],err:false};return R()}
  if(a==='reopenform'){V.act='reopen';V.draft={note:'',err:false};return R()}
  if(a==='cancelact'){V.act=null;return R()}
  if(a==='doresolve'){if(!V.draft.note.trim()){V.draft.err=true;return R()}const it=I.find(x=>x.id===V.det);it.stage='res';it.after={note:[V.draft.note,V.draft.note],photos:V.draft.photos.length,imgs:V.draft.photos};hist(it,'res');V.act=null;return flash(L('Sent to the consultant for verification','أُرسلت للاستشاري للتحقق'))}
  if(a==='doreopen'){if(!V.draft.note.trim()){V.draft.err=true;return R()}const it=I.find(x=>x.id===V.det);it.stage='open';hist(it,'reopen',V.draft.note);it.chat.push({by:R0().me,t:[V.draft.note,V.draft.note],w:0});V.act=null;return flash(L(`${it.no} re-opened`,`أُعيد فتح ${it.no}`))}
  if(a==='send'){if(!V.cm.trim())return;const it=I.find(x=>x.id===V.det);(V.tab==='int'?it.internal:it.chat).push({by:R0().me,t:[V.cm,V.cm],w:0});V.cm='';R();const db=document.getElementById('dbody');if(db)db.scrollTop=db.scrollHeight;return}
 });
 root.addEventListener('input',e=>{if(e.target.id==='snq'){V.q=e.target.value;const p=e.target.selectionStart;R();const n=document.getElementById('snq');n.focus();n.setSelectionRange(p,p)}if(e.target.id==='ct'&&V.create){V.create.saved=true}});
 root.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='cmsg'){keep();root.querySelector('[data-act=send]')?.click()}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&(V.det||V.create||V.modal||V.menu)){V.det=null;V.create=null;V.modal=null;V.menu=null;R()}});
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-fpop="sn"]');if(!b)return;e.stopPropagation();if(FPop.isOpen()){FPop.close();return}FPop.open(b,{L,fields:fields(),saved:SNSAVED,preset:SNPRESET,sel:JSON.parse(JSON.stringify(V.fsel)),onChange:(sel)=>{V.fsel=JSON.parse(JSON.stringify(sel));V.sel.clear();SNV.R&&SNV.R();const nb=document.querySelector('[data-fpop="sn"]');if(nb){FPop.btn=nb;FPop.place()}}})},true);
document.addEventListener('keydown',e=>{if(e.key==='/'&&!(e.target.closest&&e.target.closest('input,textarea'))){const i=document.getElementById('snq');if(i){e.preventDefault();i.focus()}}});
window.SNV={V,view,bind};
})();
