// Rabaed SaaS pages. Exposes window.RP[page](ctx) → {title, sub, html}
(function(){
const {esc,av}=RS;const L=(e,a)=>RS.S.lang==='ar'?a:e;
const PROJECTS=[
 {id:'dmt',l:'D',c:'#f8552f',n:'Dubai Marina Tower – Phase 2',na:'برج دبي مارينا – المرحلة ٢',co:'Al Futtaim Construction Co.',coa:'شركة الفطيم للمقاولات',p:62,st:'ok',sub:48,mine:6,snag:12,due:'Mar 2027'},
 {id:'yas',l:'Y',c:'#3d6db5',n:'Yas Bay Residences',na:'مساكن ياس باي',co:'Aldar Properties',coa:'الدار العقارية',p:35,st:'pend',sub:31,mine:3,snag:4,due:'Nov 2027'},
 {id:'shj',l:'S',c:'#1fae66',n:'Sharjah Waterfront Mall',na:'مول واجهة الشارقة المائية',co:'Arada',coa:'أرادَ',p:81,st:'ok',sub:112,mine:1,snag:27,due:'Jan 2027'},
 {id:'rak',l:'R',c:'#6b5ad8',n:'RAK Hospital Extension',na:'توسعة مستشفى رأس الخيمة',co:'RAK Health',coa:'رأس الخيمة الصحية',p:12,st:'sub',sub:9,mine:2,snag:0,due:'Aug 2028'},
 {id:'alq',l:'A',c:'#e98b45',n:'Al Qudra Villas – Cluster B',na:'فلل القدرة – المجموعة ب',co:'Meraas',coa:'مِراس',p:100,st:'mut',sub:204,mine:0,snag:0,due:'Handed over'}
];
const STL={ok:['On track','ضمن الجدول'],pend:['At risk','معرّض للتأخير'],sub:['Mobilising','قيد التجهيز'],rej:['Delayed','متأخر'],mut:['Completed','مكتمل']};
const pill=(k,txt)=>`<span class="pill p-${k}"><span class="d"></span>${txt}</span>`;
const stp=k=>pill(k,L(STL[k][0],STL[k][1]));
const hd=(h1,p,act)=>`<div class="pg-hd"><div><h1>${h1}</h1>${p?`<p>${p}</p>`:''}</div>${act?`<div class="act">${act}</div>`:''}</div>`;
const prjCard=p=>`<button class="prj" data-project="${p.id}"><div class="prj-t"><span class="l" style="background:${p.c}">${p.l}</span><div><b>${esc(L(p.n,p.na))}</b><small>${esc(L(p.co,p.coa))}</small></div>${stp(p.st)}</div>
 <div><div class="prj-m" style="margin-bottom:6px"><span>${L('Progress','نسبة الإنجاز')}</span><b>${p.p}%</b></div><div class="bar"><i style="width:${p.p}%"></i></div></div>
 <div class="prj-s"><span><i class="ti ti-file-text"></i>${p.sub} ${L('submittals','تقديم')}</span><span><i class="ti ti-user-circle"></i>${p.mine} ${L('need my action','بحاجة لإجرائي')}</span><span><i class="ti ti-calendar"></i>${esc(p.due)}</span></div></button>`;
const RP={PROJECTS};
RP.home=()=>({title:L('Home','الرئيسية'),sub:L('Thursday, 26 September 2026','الخميس، ٢٦ سبتمبر ٢٠٢٦'),html:
 hd(L('Good morning, Mohamed','صباح الخير، محمد'),L('Here’s what needs you across your projects today.','إليك ما يحتاج إلى إجرائك في مشاريعك اليوم.'),`<button class="bp" data-nav="projects"><i class="ti ti-plus"></i>${L('New project','مشروع جديد')}</button>`)+
 `<div class="grid g4" style="margin-bottom:18px">
  <div class="pc kpi"><span class="ic" style="background:var(--tone-tomato-tint);color:var(--tone-tomato-solid)"><i class="ti ti-buildings"></i></span><b>5</b><span>${L('Active projects','مشاريع نشطة')}</span></div>
  <div class="pc kpi"><span class="ic" style="background:var(--tone-blue-tint);color:var(--tone-blue-solid)"><i class="ti ti-user-circle"></i></span><b>12</b><span>${L('Submittals need my action','تقديمات بحاجة لإجرائي')}</span></div>
  <div class="pc kpi"><span class="ic" style="background:var(--tone-amber-tint);color:var(--tone-amber-solid)"><i class="ti ti-clipboard-list"></i></span><b>3</b><span>${L('Payment requests pending','طلبات دفع معلّقة')}</span></div>
  <div class="pc kpi"><span class="ic" style="background:var(--tone-red-tint);color:var(--tone-red-solid)"><i class="ti ti-clock"></i></span><b>4</b><span>${L('Overdue 8+ days','متأخرة ٨+ أيام')}</span></div>
 </div>
 <div class="grid g21">
  <div class="pc"><div class="pc-hd"><h3>${L('Needs my action','بحاجة لإجرائي')}</h3><button class="ln" data-project="dmt">${L('Open board','فتح اللوحة')}</button></div><div class="pc-bd" style="padding-top:4px;padding-bottom:4px">
   ${[['Fire Suppression System','نظام إطفاء الحريق','12789331 · R2','dmt',pill('pend',L('Pending approval','بانتظار الاعتماد'))],['HVAC Ducting','مجاري التكييف','12789319','dmt',pill('rej',L('Overdue','متأخر'))],['Basement Waterproofing','العزل المائي للقبو','12789332 · R1','yas',pill('sub',L('Resubmitted','معاد تقديمه'))],['Payment request #PR-0142','طلب دفع رقم PR-0142','AED 1,240,000','shj',pill('pend',L('Awaiting review','بانتظار المراجعة'))]].map(r=>`<div class="act-it"><span class="ic"><i class="ti ti-file-text"></i></span><div><b>${esc(L(r[0],r[1]))}</b><small class="num" style="font-family:var(--font-ui)">${r[2]} · ${esc(L(PROJECTS.find(p=>p.id===r[3]).n,PROJECTS.find(p=>p.id===r[3]).na))}</small></div><span class="r">${r[4]}</span></div>`).join('')}
  </div></div>
  <div class="pc"><div class="pc-hd"><h3>${L('Recent activity','آخر النشاطات')}</h3></div><div class="pc-bd" style="padding-top:4px;padding-bottom:4px">
   ${[['Sarah Al Mansoori','#b5455a',L('approved Lighting Fixtures (Code B)','اعتمدت وحدات الإنارة (Code B)'),'10m'],['Nasser Al Kaabi','#e98b45',L('resubmitted Fire Suppression System','أعاد تقديم نظام إطفاء الحريق'),'1h'],['Khalid Al Dhaheri','#6b5ad8',L('rejected Non-Compliant Materials','رفض مواد غير مطابقة'),'3h'],['Omar Al Blooshi','#1fae66',L('requested to join Al Futtaim','طلب الانضمام إلى الفطيم'),'5h']].map(a=>`<div class="act-it">${av(a[0],a[1],34)}<div><b style="font-weight:500">${esc(a[0])} <span style="color:var(--mut)">${a[2]}</span></b><small class="num">${a[3]} ${L('ago','مضت')}</small></div></div>`).join('')}
  </div></div>
 </div>
 <div class="pg-hd" style="margin:28px 0 14px"><div><h1 style="font-size:18px">${L('Your projects','مشاريعك')}</h1></div><div class="act"><button class="bs bsm" data-nav="projects">${L('View all','عرض الكل')}</button></div></div>
 <div class="grid g3">${PROJECTS.slice(0,3).map(prjCard).join('')}</div>`});
RP.projects=()=>{const f=RP._pf||'all';const list=PROJECTS.filter(p=>f==='all'||(f==='active'?p.st!=='mut':p.st==='mut'));return {title:L('Projects','المشاريع'),sub:L('5 projects · Al Futtaim Construction Co.','٥ مشاريع · شركة الفطيم للمقاولات'),html:
 hd(L('Projects','المشاريع'),L('All projects you are a member of.','جميع المشاريع التي أنت عضو فيها.'),`<button class="bp"><i class="ti ti-plus"></i>${L('New project','مشروع جديد')}</button>`)+
 `<div style="display:flex;gap:10px;margin-bottom:18px;flex-wrap:wrap;align-items:center"><label class="fin"><i class="ti ti-search"></i><input placeholder="${L('Search projects','ابحث في المشاريع')}"></label>${[['all','All','الكل'],['active','Active','نشطة'],['done','Completed','مكتملة']].map(c=>`<button class="chipf${f===c[0]?' on':''}" data-pf="${c[0]}">${L(c[1],c[2])}</button>`).join('')}</div>
 <div class="grid g3">${list.map(prjCard).join('')}</div>`}};
RP.payments=()=>({title:L('Payment Requests','طلبات الدفع'),sub:L('Interim payment applications across projects','طلبات الدفع المرحلية لجميع المشاريع'),html:
 hd(L('Payment Requests','طلبات الدفع'),L('Track interim payment applications from submission to certification.','تتبّع طلبات الدفع المرحلية من التقديم حتى الاعتماد.'),`<button class="bs"><i class="ti ti-download"></i>${L('Export','تصدير')}</button><button class="bp"><i class="ti ti-plus"></i>${L('New request','طلب جديد')}</button>`)+
 `<div class="pc"><div class="tbar"><label class="fin"><i class="ti ti-search"></i><input placeholder="${L('Search by reference or project','ابحث بالمرجع أو المشروع')}"></label>${[['All','الكل',1],['Pending','معلّقة'],['Certified','معتمدة'],['Returned','مُعادة']].map(c=>`<button class="chipf${c[2]?' on':''}">${L(c[0],c[1])}</button>`).join('')}</div>
 <div class="ovx"><table class="tbl"><thead><tr><th>${L('Reference','المرجع')}</th><th>${L('Project','المشروع')}</th><th>${L('Period','الفترة')}</th><th>${L('Amount (AED)','المبلغ (درهم)')}</th><th>${L('Status','الحالة')}</th><th>${L('Submitted','تاريخ التقديم')}</th></tr></thead><tbody>
 ${[['PR-0142','shj','Aug 2026','1,240,000','pend','Awaiting review','بانتظار المراجعة','22 Sep 2026'],['PR-0141','dmt','Aug 2026','3,815,500','ok','Certified','معتمد','15 Sep 2026'],['PR-0139','yas','Jul 2026','960,250','rej','Returned','مُعاد','02 Sep 2026'],['PR-0137','dmt','Jul 2026','2,904,000','ok','Certified','معتمد','14 Aug 2026'],['PR-0135','rak','Jul 2026','418,700','sub','Submitted','مُقدَّم','09 Aug 2026']].map(r=>{const p=PROJECTS.find(x=>x.id===r[1]);return `<tr><td class="num" style="font-weight:600">${r[0]}</td><td>${esc(L(p.n,p.na))}</td><td class="num">${r[2]}</td><td class="num" style="font-weight:600">${r[3]}</td><td>${pill(r[4],L(r[5],r[6]))}</td><td class="num" style="color:var(--mut)">${r[7]}</td></tr>`}).join('')}
 </tbody></table></div></div>`});
RP.map=()=>({title:L('Map View','عرض الخريطة'),sub:L('Project locations','مواقع المشاريع'),html:hd(L('Map View','عرض الخريطة'),'')+`<div class="map-ph"><i class="ti ti-map"></i><b style="color:var(--ink)">${L('Map view','عرض الخريطة')}</b><span>${L('Not designed yet — placeholder.','لم يُصمَّم بعد — مساحة مؤقتة.')}</span></div>`});
RP.profile=()=>({title:L('Company Profile','ملف الشركة'),sub:L('My Company · general information for all modules','شركتي · معلومات عامة لجميع الوحدات'),html:
 `<div class="pc" style="margin-bottom:18px"><div class="co-hd"><span class="co-lg">AF</span><div><h2>${L('Al Futtaim Construction Co.','شركة الفطيم للمقاولات')}</h2><p>${L('Main contractor · Dubai, UAE · Member since 2024','مقاول رئيسي · دبي، الإمارات · عضو منذ ٢٠٢٤')}</p></div><div style="margin-inline-start:auto;display:flex;gap:10px"><button class="bs"><i class="ti ti-edit"></i>${L('Edit profile','تعديل الملف')}</button></div></div></div>
 <div class="grid g21"><div class="pc"><div class="pc-hd"><h3>${L('Company information','معلومات الشركة')}</h3></div><div class="pc-bd"><div class="kv">
  ${[['Legal name','الاسم القانوني','Al Futtaim Construction Co. LLC'],['Trade licence','الرخصة التجارية','DED-704512'],['TRN','الرقم الضريبي','100 2345 6789 0003'],['Company type','نوع الشركة',L('Main contractor','مقاول رئيسي')],['Headquarters','المقر الرئيسي',L('Festival City, Dubai','دبي فستيفال سيتي')],['Phone','الهاتف','+971 4 213 4000'],['Email','البريد الإلكتروني','projects@alfuttaim.ae'],['Website','الموقع','alfuttaim.ae']].map(k=>`<div><small>${L(k[0],k[1])}</small><b class="${/\d|@|\./.test(k[2])?'num':''}">${esc(k[2])}</b></div>`).join('')}
 </div></div></div>
 <div class="pc"><div class="pc-hd"><h3>${L('Company documents','مستندات الشركة')}</h3><button class="ln">${L('Upload','رفع')}</button></div><div class="pc-bd" style="display:flex;flex-direction:column;gap:10px">
  ${[['Trade licence','الرخصة التجارية','PDF · 1.2 MB','ok','Valid','سارية'],['VAT certificate','شهادة ضريبة القيمة المضافة','PDF · 640 KB','ok','Valid','سارية'],['ISO 9001','ISO 9001','PDF · 2.1 MB','pend','Expires in 30d','تنتهي خلال ٣٠ يومًا']].map(d=>`<div class="doc"><span class="ic"><i class="ti ti-file-text"></i></span><div><b>${L(d[0],d[1])}</b><small>${d[2]}</small></div>${pill(d[3],L(d[4],d[5]))}</div>`).join('')}
 </div></div></div>`});
const ROLES=[['Contractor Engineer','مهندس المقاول','var(--tone-blue-solid)','var(--tone-blue-tint)',14,[1,1,0,1,0]],['Contractor Project Manager','مدير مشروع المقاول','var(--tone-violet-solid)','var(--tone-violet-tint)',4,[1,1,1,1,1]],['Consultant','الاستشاري','var(--tone-green-solid)','var(--tone-green-tint)',6,[1,0,1,0,1]],['Client Representative','ممثل المالك','var(--tone-orange-solid)','var(--tone-orange-tint)',2,[1,0,1,0,0]],['Company Admin','مسؤول الشركة','var(--tone-gray-fg)','var(--tone-gray-tint)',1,[1,1,1,1,1]]];
RP.roles=()=>{const i=RP._role||0,r=ROLES[i];const perms=[['View','عرض'],['Create','إنشاء'],['Approve','اعتماد'],['Edit','تعديل'],['Delete','حذف']];const mods=[['Submittals','التقديمات'],['Packages','الحزم'],['Daily Site Report','تقرير الموقع اليومي'],['Snag List','قائمة الملاحظات'],['Payment Requests','طلبات الدفع'],['Files','الملفات']];
 return {title:L('Roles','الأدوار'),sub:L('My Company · who can do what, in every module','شركتي · من يستطيع ماذا في كل وحدة'),html:
 hd(L('Roles','الأدوار'),L('Roles apply to every project and module in the company.','تنطبق الأدوار على جميع المشاريع والوحدات في الشركة.'),`<button class="bp"><i class="ti ti-plus"></i>${L('New role','دور جديد')}</button>`)+
 `<div class="grid g-roles"><div class="pc"><div class="rl">${ROLES.map((x,j)=>`<button class="${j===i?'on':''}" data-roleview="${j}"><span class="ic" style="background:${x[3]};color:${x[2]}"><i class="ti ti-shield"></i></span><div><b>${L(x[0],x[1])}</b><small>${x[4]} ${L('members','أعضاء')}</small></div></button>`).join('')}</div></div>
 <div class="pc"><div class="pc-hd"><h3>${L(r[0],r[1])}</h3><span class="pill p-mut">${r[4]} ${L('members','أعضاء')}</span><button class="ln">${L('Edit permissions','تعديل الصلاحيات')}</button></div><div class="pc-bd ovx"><table class="pm"><thead><tr><th>${L('Module','الوحدة')}</th>${perms.map(p=>`<th>${L(p[0],p[1])}</th>`).join('')}</tr></thead><tbody>
 ${mods.map((m,mi)=>`<tr><td>${L(m[0],m[1])}</td>${perms.map((p,pi)=>{const on=pi===0||(r[5][pi]&&(mi+pi)%4!==3);return `<td><i class="ti ${on?'ti-circle-check y':'ti-minus n'}"></i></td>`}).join('')}</tr>`).join('')}
 </tbody></table></div></div></div>`}};
RP._reqs=RP._reqs||[['Omar Al Blooshi','omar@arabtec.ae','#1fae66','Consultant','الاستشاري','Arabtec','2h'],['Layla Al Qasimi','layla@alec.ae','#b5455a','Contractor Engineer','مهندس المقاول','ALEC','5h'],['Hassan Al Marri','hassan@aldar.ae','#3a3f4b','Client Representative','ممثل المالك','Aldar','1d'],['Fatima Al Mazrouei','fatima@alfuttaim.ae','#e98b45','Contractor Engineer','مهندس المقاول','Al Futtaim','2d'],['Yousef Al Nuaimi','yousef@meraas.ae','#3d6db5','Contractor Project Manager','مدير مشروع المقاول','Meraas','3d']];
RP.join=()=>({title:L('Request To Join','طلبات الانضمام'),sub:L('My Company · people asking to join your workspace','شركتي · أشخاص يطلبون الانضمام إلى مساحة العمل'),html:
 hd(L('Request To Join','طلبات الانضمام'),L('Approve to add them as users with the requested role.','وافق لإضافتهم كمستخدمين بالدور المطلوب.'))+
 `<div class="pc">${RP._reqs.length?RP._reqs.map((q,i)=>`<div class="req">${av(q[0],q[2],42)}<div><b>${esc(q[0])}</b><small class="num">${q[1]}</small></div><div class="meta"><span><i class="ti ti-shield"></i>${L(q[3],q[4])}</span><span><i class="ti ti-building"></i>${q[5]}</span><span class="num" style="color:var(--mut)"><i class="ti ti-clock"></i>${q[6]}</span></div><div class="ac"><button class="bno" data-req="no:${i}">${L('Decline','رفض')}</button><button class="bok" data-req="ok:${i}"><i class="ti ti-check"></i>${L('Approve','موافقة')}</button></div></div>`).join(''):`<div class="empty"><div class="ic"><i class="ti ti-user-plus"></i></div><b>${L('No pending requests','لا توجد طلبات معلّقة')}</b>${L('New requests will appear here.','ستظهر الطلبات الجديدة هنا.')}</div>`}</div>`});
RP.users=()=>({title:L('Users','المستخدمون'),sub:L('My Company · 27 users','شركتي · ٢٧ مستخدمًا'),html:
 hd(L('Users','المستخدمون'),L('Everyone in your company workspace.','جميع أعضاء مساحة عمل شركتك.'),`<button class="bp"><i class="ti ti-user-plus"></i>${L('Invite user','دعوة مستخدم')}</button>`)+
 `<div class="pc"><div class="tbar"><label class="fin"><i class="ti ti-search"></i><input placeholder="${L('Search by name or email','ابحث بالاسم أو البريد')}"></label></div><div class="ovx"><table class="tbl"><thead><tr><th>${L('Name','الاسم')}</th><th>${L('Role','الدور')}</th><th>${L('Projects','المشاريع')}</th><th>${L('Status','الحالة')}</th><th>${L('Last active','آخر نشاط')}</th></tr></thead><tbody>
 ${[['Mohamed Al Hashimi','mohamed@alfuttaim.ae','#6b5ad8',0,5,'ok','Active','نشط','Now'],['Ahmed bin Said','ahmed@alfuttaim.ae','#3d6db5',0,3,'ok','Active','نشط','12m'],['Abdullah Al Saadi','abdullah@alfuttaim.ae','#7a5c3a',1,4,'ok','Active','نشط','1h'],['Nasser Al Kaabi','nasser@alfuttaim.ae','#e98b45',0,2,'ok','Active','نشط','3h'],['Sarah Al Mansoori','sarah@consult.ae','#b5455a',2,2,'pend','Invited','مدعو','—'],['Khalid Al Dhaheri','khalid@alfuttaim.ae','#6b5ad8',0,1,'mut','Deactivated','معطّل','30d']].map(u=>`<tr><td><div class="who">${av(u[0],u[2],36)}<div><b>${esc(u[0])}</b><small>${u[1]}</small></div></div></td><td>${L(ROLES[u[3]][0],ROLES[u[3]][1])}</td><td class="num">${u[4]}</td><td>${pill(u[5],L(u[6],u[7]))}</td><td class="num" style="color:var(--mut)">${u[8]}</td></tr>`).join('')}
 </tbody></table></div></div>`});
RP.subs=()=>({title:L('Subscription Management','إدارة الاشتراك'),sub:L('My Company · plan, usage and billing','شركتي · الخطة والاستخدام والفوترة'),html:
 hd(L('Subscription','الاشتراك'),'')+
 `<div class="pc plan" style="margin-bottom:18px"><div><div class="tag">${L('Current plan','الخطة الحالية')}</div><h2>${L('Business','الأعمال')}</h2><p>${L('Renews on 01 Jan 2027 · billed yearly','تتجدد في ٠١ يناير ٢٠٢٧ · فوترة سنوية')}</p></div><div class="pr"><b>AED 18,000</b><small>${L('per year','سنويًا')}</small></div><div style="display:flex;gap:10px"><button class="bs">${L('Manage billing','إدارة الفوترة')}</button><button class="bp">${L('Upgrade','ترقية')}</button></div></div>
 <div class="grid g21"><div class="pc"><div class="pc-hd"><h3>${L('Usage','الاستخدام')}</h3></div><div class="pc-bd" style="display:flex;flex-direction:column;gap:18px">
  ${[['Projects','المشاريع',5,10],['Users','المستخدمون',27,50],['Storage','التخزين',64,100,'GB']].map(u=>`<div class="use"><div class="h"><span>${L(u[0],u[1])}</span><b>${u[2]} / ${u[3]}${u[4]?' '+u[4]:''}</b></div><div class="bar"><i style="width:${u[2]/u[3]*100}%"></i></div></div>`).join('')}
 </div></div>
 <div class="pc"><div class="pc-hd"><h3>${L('Billing history','سجل الفواتير')}</h3></div><div class="pc-bd" style="padding-top:4px;padding-bottom:4px">
  ${[['INV-2026-001','01 Jan 2026','18,000'],['INV-2025-001','01 Jan 2025','15,000']].map(b=>`<div class="act-it"><span class="ic"><i class="ti ti-file-text"></i></span><div><b class="num">${b[0]}</b><small class="num">${b[1]}</small></div><span class="r num" style="font-weight:600">AED ${b[2]}</span></div>`).join('')}
 </div></div></div>`});
RP.project=(p,tab)=>{const tn=RS.t('tabs')[tab];
 if(tab===0)return `<div class="grid g4" style="margin-bottom:18px">${[[L('Progress','الإنجاز'),p.p+'%'],[L('Submittals','التقديمات'),p.sub],[L('Need my action','بحاجة لإجرائي'),p.mine],[L('Open snags','ملاحظات مفتوحة'),p.snag]].map(k=>`<div class="pc kpi"><span>${k[0]}</span><b>${k[1]}</b></div>`).join('')}</div><div class="pc"><div class="pc-hd"><h3>${L('Project details','تفاصيل المشروع')}</h3>${stp(p.st)}</div><div class="pc-bd"><div class="kv">${[[L('Client','المالك'),L(p.co,p.coa)],[L('Main contractor','المقاول الرئيسي'),L('Al Futtaim Construction Co.','شركة الفطيم للمقاولات')],[L('Completion','الإنجاز المتوقع'),p.due],[L('Location','الموقع'),L('Dubai, UAE','دبي، الإمارات')]].map(k=>`<div><small>${k[0]}</small><b>${esc(k[1])}</b></div>`).join('')}</div></div></div>`;
 if(tab===1)return `<div class="pc"><div class="empty"><div class="ic"><i class="ti ti-layout-grid"></i></div><b>${tn}</b>${L('The Kanban board is designed separately.','لوحة كانبان مصممة بشكل منفصل.')}<div style="margin-top:16px"><a class="bp" href="submittals-kanban.html" target="_blank" style="text-decoration:none"><i class="ti ti-external-link"></i>${L('Open Submittals board','فتح لوحة التقديمات')}</a></div></div></div>`;
 return `<div class="pc"><div class="empty"><div class="ic"><i class="ti ti-file-text"></i></div><b>${tn}</b>${L('Module not designed yet.','لم تُصمَّم هذه الوحدة بعد.')}</div></div>`};
window.RP=RP;
})();
