import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The Arabic font switch. Thmanyah Sans is licensed and never committed; when
 * its .woff2 files are present at build time (put there privately by CI, RP-211)
 * Arabic uses it, otherwise the free IBM Plex Sans Arabic. Storybook, the story
 * tests and the web build all call this before bundling CSS.
 */

const packageRoot = fileURLToPath(new URL("../../", import.meta.url));

/** Where the private Thmanyah Sans files go (git-ignored). */
export const defaultThmanyahDir = join(packageRoot, "fonts", "thmanyah");
/** The generated stylesheet imported by src/styles/index.css (git-ignored). */
export const defaultArabicFontCss = join(packageRoot, "src", "styles", "arabic-font.css");

const weights: Record<string, number> = { light: 300, regular: 400, medium: 500, bold: 700, black: 900 };
const thmanyahSansFile = /^thmanyahsans-(light|regular|medium|bold|black)\.woff2$/i;

export type ArabicFont = { font: "Thmanyah Sans" | "IBM Plex Sans Arabic"; faces: number };

export function prepareArabicFont({
  fontsDir = defaultThmanyahDir,
  outFile = defaultArabicFontCss,
}: { fontsDir?: string; outFile?: string } = {}): ArabicFont {
  const files = existsSync(fontsDir) ? readdirSync(fontsDir).filter((name) => thmanyahSansFile.test(name)) : [];
  const faces = files
    .map((name) => ({ name, weight: weights[thmanyahSansFile.exec(name)![1]!.toLowerCase()]! }))
    .sort((a, b) => a.weight - b.weight);

  const header = "/* Generated by prepareArabicFont (src/fonts/arabic-font.ts) at build time. Do not edit or commit. */";
  let css: string;
  if (faces.length === 0) {
    css = [header, "", ":root {", "  --font-arabic: 'IBM Plex Sans Arabic';", "}", ""].join("\n");
  } else {
    const fromCss = relative(dirname(outFile), fontsDir).split(sep).join("/");
    css = [
      header,
      "",
      ...faces.flatMap(({ name, weight }) => [
        "@font-face {",
        "  font-family: 'Thmanyah Sans';",
        "  font-style: normal;",
        `  font-weight: ${weight};`,
        "  font-display: swap;",
        `  src: url("${fromCss}/${name}") format("woff2");`,
        "}",
        "",
      ]),
      ":root {",
      "  --font-arabic: 'Thmanyah Sans', 'IBM Plex Sans Arabic';",
      "}",
      "",
    ].join("\n");
  }

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, css);
  return { font: faces.length > 0 ? "Thmanyah Sans" : "IBM Plex Sans Arabic", faces: faces.length };
}
