import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The Arabic font switch. Thmanyah Sans is licensed and never committed; when
 * its .woff2 files are present at build time (the deploy puts them there from
 * the private build assets bucket, RP-211) Arabic uses it, otherwise the free
 * IBM Plex Sans Arabic. Storybook, the story tests and the web build all call
 * this before bundling CSS.
 */

const packageRoot = fileURLToPath(new URL("../../", import.meta.url));

/** Where the private Thmanyah Sans files go (git-ignored). */
const defaultThmanyahDir = join(packageRoot, "fonts", "thmanyah");
/** The generated stylesheet imported by src/styles/index.css (git-ignored). */
const defaultArabicFontCss = join(packageRoot, "src", "styles", "arabic-font.css");

const weights: Record<string, number> = { light: 300, regular: 400, medium: 500, bold: 700, black: 900 };
const thmanyahSansFile = /^thmanyahsans-(light|regular|medium|bold|black)\.woff2$/i;

const fallback = "IBM Plex Sans Arabic";

export type ArabicFont = { font: "Thmanyah Sans" | typeof fallback; faces: number };

export function prepareArabicFont({
  fontsDir = defaultThmanyahDir,
  outFile = defaultArabicFontCss,
}: { fontsDir?: string; outFile?: string } = {}): ArabicFont {
  const files = existsSync(fontsDir) ? readdirSync(fontsDir).filter((name) => thmanyahSansFile.test(name)) : [];
  const faces = files
    .map((name) => ({ name, weight: weights[thmanyahSansFile.exec(name)![1]!.toLowerCase()]! }))
    .sort((a, b) => a.weight - b.weight);

  const font: ArabicFont["font"] = faces.length > 0 ? "Thmanyah Sans" : fallback;
  const fromCss = relative(dirname(outFile), fontsDir).split(sep).join("/");
  const css = [
    "/* Generated by prepareArabicFont (src/fonts/arabic-font.ts) at build time. Do not edit or commit. */",
    "",
    ...faces.flatMap(({ name, weight }) => [
      "@font-face {",
      `  font-family: '${font}';`,
      "  font-style: normal;",
      `  font-weight: ${weight};`,
      "  font-display: swap;",
      `  src: url("${fromCss}/${name}") format("woff2");`,
      "}",
      "",
    ]),
    ":root {",
    `  --font-arabic: ${(font === fallback ? [fallback] : [font, fallback]).map((f) => `'${f}'`).join(", ")};`,
    "}",
    "",
  ].join("\n");

  mkdirSync(dirname(outFile), { recursive: true });
  writeFileSync(outFile, css);
  return { font, faces: faces.length };
}
